### PR TITLE
#2728 updated launcher long-press icon options to remove dead-end zim…

### PR DESCRIPTION
**Pull request by jhbiggs**
#2728 disabled shortcut to eliminate option for dead-end zim manager activity

### CODE REVIEW

**Comment by gouri-panda** [comment]
@jhbiggs Thanks for the pull request. But This PR removes the shortcut. This is a good shortcut. It's nice if we fix this :)

**Comment by jhbiggs** [comment]
Ok, sounds good.  I will set it up to launch the main activity.  Had trouble finding the download activity but would gladly put it in if you like.

**Comment by gouri-panda** [comment]
@jhbiggs You can go to download fragment by shortcut intent action.

**Comment by gouri-panda** [comment]
@jhbiggs It just opens the application. We initially went to the Online fragment. We can achieve this by custom intent action. In short 
```
<intent
        android:action="com.your.packagename.custom.name"
        android:targetPackage="com.example"
        android:targetClass="com.example.Activity" />
```
and then getIntent().getAction() for intent action in the Activity specified in `android:targetClass:`
```
public void onCreate(Bundle savedInstanceState){
    if (CUSTOM_NAME.equals(getIntent().getAction())) {
        // do Fragment transactions here 
    }
}
```
more info [here](https://developer.android.com/guide/topics/ui/shortcuts/creating-shortcuts) & [here](https://developer.android.com/reference/android/content/Intent#setAction(java.lang.String))

**Comment by cdhiraj40** [comment]
any feedback @jhbiggs?

**Comment by jhbiggs** [comment]
Ok, understood. I'm having trouble finding the download fragment path.

**Comment by gouri-panda** [comment]
@jhbiggs Here is the path `app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt`

**Comment by jhbiggs** [comment]
Hello, I'm wondering if I need to do something about the failing checks here.

**Comment by gouri-panda** [comment]
@jhbiggs Nothing to worry about CI for now.

**Review by gouri-panda — APPROVED** [review]
@jhbiggs Thank you  for the contribution :)

**Comment by jhbiggs** [comment]
Woohoo! You’re welcome. Do you have suggestions for another issue I could work on?

>

**Comment by gouri-panda** [comment]
@jhbiggs We have a lot of good first issues. You can start with any issue. Pick an issue that interests you. Good luck!

**Pull request merged**
