### PR TITLE
Added country name in front of ZIM file language

### LINKED ISSUE #3215: Too many Phets book for language "muktiple language"
I see four books but it should be only one. What are rhe three others, why are they dispkayed?
Screenshot_20230124-190438

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #3215 

* Added country name in front of ZIM file language.
* We have a method (```iSO3ToLocale```) to get ```Local``` from ```iSO3``` , I have use that for getting country name from ```ISO 639-2 language code``` , most of ZIM files are using ```ISO 639-2``` for ZIM language and some file are using ```ISO 639-1``` language.
* For getting country name from ```ISO 639-1 language code``` i have used ```Locale(languageCode).displayCountry``` method of ```Local``` class.

**Screenshots** 

| Screenshot  | Screenshot | Screenshot |
| ------------- | ------------- | ------------- |
| Screenshot_2023-02-24-17-40-59-894_org kiwix kiwixmobile |  Screenshot_2023-02-24-17-41-06-893_org kiwix kiwixmobile | Screenshot_2023-02-24-17-41-12-653_org kiwix kiwixmobile |

### CODE REVIEW

**Comment by kelson42** [comment]
@MohitMaliFtechiz
* why this PR is still a draft?
* Does your fix impact somehow the language list (probably it should not)?
* Do the language without country variant are still printed properly?
* Do the country name are translated properly depending of UI language?

**Comment by MohitMaliFtechiz** [comment]
@kelson42 ,

> why this PR is still a draft?

I had ask a question over slack and waiting for reply, that's why this PR is in draft.

> Do the country name are translated properly depending of UI language?

we are translating country name from ISO code, which is inside the ZIM file.

**Comment by kelson42** [comment]
> @kelson42 ,
> 
> > why this PR is still a draft?
> 
> I had ask a question over slack and waiting for reply, that's why this PR is in draft.

I don't know what you mean, please handle ticket discussion on Github.

> > Do the country name are translated properly depending of UI language?
> 
> we are translating country name from ISO code, which is inside the ZIM file.

This does not answer my question.

**Comment by MohitMaliFtechiz** [comment]
@kelson42 , i have some questions.


* After placing the fix I have tested it, But i have found all the English zim files contains same ISO langauge code (eng) and it's returing zimbabwe country name(so is all english zim files in zimbabwe language?). 

*  I have check for phet ZIM files and i have found two 4.1 mb files these have same ISO code (eng), so i have downloaded both files and check both ZIM files are same, but these ZIM files are comming from diffrent urls(that's why both are showing in application). urls are below (both are different but in these urls they indicate different ISO code like `phet_en-ca_2023-01.zim` and it's Canada English but zim has eng ISO). 
   https://mirrors.dotsrc.org/kiwix/zim/phet/phet_en-ca_2023-01.zim
   https://mirrors.dotsrc.org/kiwix/zim/phet/phet_en-gb_2023-01.zim

* So can you please confirm (if i'm wrong here) is url containing ISO code is true or these are just for making ZIM files url different?. If i'm correct then these two zim files has wrong ISO code containing.

**Comment by kelson42** [comment]
> @kelson42 , i have some questions.
> 
> 
> * After placing the fix I have tested it, But i have found all the English zim files contains same ISO langauge code (eng) and it's returing zimbabwe country name(so is all english zim files in zimbabwe language?). 

Use zimdump to check what language metadata has a zim. Your question been not precise enough i can not answer.

> *  I have check for phet ZIM files and i have found two 4.1 mb files these have same ISO code (eng), so i have downloaded both files and check both ZIM files are same, but these ZIM files are comming from diffrent urls(that's why both are showing in application). urls are below (both are different but in these urls they indicate different ISO code like `phet_en-ca_2023-01.zim` and it's Canada English but zim has eng ISO). 
>    https://mirrors.dotsrc.org/kiwix/zim/phet/phet_en-ca_2023-01.zim
>    https://mirrors.dotsrc.org/kiwix/zim/phet/phet_en-gb_2023-01.zim

Interesting, but not sure this is a bug. Please open a ticket in openzim/phet repository.

> * So can you please confirm (if i'm wrong here) is url containing ISO code is true or these are just for making ZIM files url different?. If i'm correct then these two zim files has wrong ISO code containing.

never rely on filename, trust metadata. AFAIK, there language code is correct, bit maybe not precise enough. It should not anyway impact directly this PR.

>  **Edited:-** if i'm wrong then it's online content side issue, there same file uploaded with different names.

Please open a ticket on the scraper side.

You still don't have answered to my secobd question.

**Comment by MohitMaliFtechiz** [comment]
> Does your fix impact somehow the language list (probably it should not)?

No it's not impacting language list.

> Do the language without country variant are still printed properly?

yes it's printed properly.

> Do the country name are translated properly depending of UI language?

Yes country name is translated depending of UI language.

language

**Comment by kelson42** [comment]
@MohitMaliDeveloper But you have indeed a bug, most of language should simply be "English" or "French" without any country variant. This is the case at least for the "3D printing" ZIM because its language is `eng` (see https://library.kiwix.org/raw/3dprinting.stackexchange.com_en_all_2023-01/meta/Language) so it should juste write `English`.

**Comment by MohitMaliFtechiz** [comment]
> eng

hi @kelson42 , one thing i observe while passing ```eng``` as ISO on android it always return ```zimbawe``` as country not sure why ?

also what is link of scrapper repo ?

**Comment by kelson42** [comment]
> hi @kelson42 , one thing i observe while passing `eng` as ISO on android it always return `zimbawe` as country not sure why ?

No clue, how should I know? Is that a function of libkiwix which returns something wrong?

**Comment by MohitMaliFtechiz** [comment]
Now, I got it why it's returning ```Zimbabwe``` from ```eng``` ISO code. 
we are using ```LanguageUtils.iSO3ToLocale(languageCode)``` method for getting country name from ```ISO```. it is using ```Locale.getAvailableLocales()``` from device. it is returning the list of available locales from this we are getting the country name according to ISO code.

```
{AFR=af_ZA, AGQ=agq_CM, AKA=ak_GH, AMH=am_ET, ARA=ar_YE, ASM=as_IN, ASA=asa_TZ, AST=ast_ES, AZE=az_AZ_#Latn, BAS=bas_CM, BEL=be_BY, BEM=bem_ZM, BEZ=bez_TZ, BUL=bg_BG, BAM=bm_ML, BEN=bn_IN, BOD=bo_IN, BRE=br_FR, BRX=brx_IN, BOS=bs_BA_#Latn, CAT=ca_IT, CCP=ccp_IN, CHE=ce_RU, CEB=ceb_PH, CGG=cgg_UG, CHR=chr_US, CKB=ckb_IR, CES=cs_CZ, CYM=cy_GB, DAN=da_GL, DAV=dav_KE, DEU=de_LU, DJE=dje_NE, DOI=doi_IN, DSB=dsb_DE, DUA=dua_CM, DYO=dyo_SN, DZO=dz_BT, EBU=ebu_KE, EWE=ee_TG, ELL=el_GR, ENG=en_ZW, EPO=eo_001, SPA=es_VE, EST=et_EE, EUS=eu_ES, EWO=ewo_CM, FAS=fa_IR, FUL=ff_SN_#Latn, FIN=fi_FI, FIL=fil_PH, FAO=fo_FO, FRA=fr_YT, FUR=fur_IT, FRY=fy_NL, GLE=ga_IE, GLA=gd_GB, GLG=gl_ES, GSW=gsw_LI, GUJ=gu_IN, GUZ=guz_KE, GLV=gv_IM, HAU=ha_NG, HAW=haw_US, HEB=iw_IL, HIN=hi_IN, HRV=hr_HR, HSB=hsb_DE, HUN=hu_HU, HYE=hy_AM, INA=ia_001, IND=in_ID, IBO=ig_NG, III=ii_CN, ISL=is_IS, ITA=it_VA, JPN=ja_JP, JGO=jgo_CM, JMC=jmc_TZ, JAV=jv_ID, KAT=ka_GE, KAB=kab_DZ, KAM=kam_KE, KDE=kde_TZ, KEA=kea_CV, KHQ=khq_ML, KIK=ki_KE, KAZ=kk_KZ, KKJ=kkj_CM, KAL=kl_GL, KLN=kln_KE, KHM=km_KH, KAN=kn_IN, KOR=ko_KR, KOK=kok_IN, KAS=ks_IN_#Arab, KSB=ksb_TZ, KSF=ksf_CM, KSH=ksh_DE, KUR=ku_TR, COR=kw_GB, KIR=ky_KG, LAG=lag_TZ, LTZ=lb_LU, LUG=lg_UG, LKT=lkt_US, LIN=ln_CG, LAO=lo_LA, LRC=lrc_IR, LIT=lt_LT, LUB=lu_CD, LUO=luo_KE, LUY=luy_KE, LAV=lv_LV, MAI=mai_IN, MAS=mas_TZ, MER=mer_KE, MFE=mfe_MU, MLG=mg_MG, MGH=mgh_MZ, MGO=mgo_CM, MRI=mi_NZ, MKD=mk_MK, MAL=ml_IN, MON=mn_MN, MNI=mni_IN_#Beng, MAR=mr_IN, MSA=ms_SG, MLT=mt_MT, MUA=mua_CM, MYA=my_MM, MZN=mzn_IR, NAQ=naq_NA, NOB=nb_SJ, NDE=nd_ZW, NEP=ne_NP, NLD=nl_SX, NMG=nmg_CM, NNO=nn_NO, NNH=nnh_CM, NUS=nus_SS, NYN=nyn_UG, ORM=om_KE, ORI=or_IN, OSS=os_RU, PAN=pa_IN_#Guru, PCM=pcm_NG, POL=pl_PL, PUS=ps_PK, POR=pt_TL, QUE=qu_PE, ROH=rm_CH, RUN=rn_BI, RON=ro_RO, ROF=rof_TZ, RUS=ru_UA, KIN=rw_RW, RWK=rwk_TZ, SAN=sa_IN, SAH=sah_RU, SAQ=saq_KE, SAT=sat_IN_#Olck, SBP=sbp_TZ, SND=sd_IN_#Deva, SME=se_SE, SEH=seh_MZ, SES=ses_ML, SAG=sg_CF, SHI=shi_MA_#Tfng, SIN=si_LK, SLK=sk_SK, SLV=sl_SI, SMN=smn_FI, SNA=sn_ZW, SOM=so_SO, SQI=sq_XK, SRP=sr_XK_#Latn, SUN=su_ID_#Latn, SWE=sv_SE, SWA=sw_UG, TAM=ta_SG, TEL=te_IN, TEO=teo_UG, TGK=tg_TJ, THA=th_TH, TIR=ti_ET, TUK=tk_TM, TON=to_TO, TUR=tr_TR, TAT=tt_RU, TWQ=twq_NE, TZM=tzm_MA, UIG=ug_CN, UKR=uk_UA, URD=ur_PK, UZB=uz_UZ_#Latn, VAI=vai_LR_#Vaii, VIE=vi_VN, VUN=vun_TZ, WAE=wae_CH, WOL=wo_SN, XHO=xh_ZA, XOG=xog_UG, YAV=yav_CM, YID=ji_001, YOR=yo_NG, YUE=yue_HK_#Hant, ZGH=zgh_MA, ZHO=zh_TW_#Hant, ZUL=zu_ZA}
```

in this list ```eng``` returning ```en_ZW``` which is ```Zimbabwe``` . that'why it's showing ```Zimbabwe``` on most of the zim files.

**Comment by kelson42** [comment]
@MohitMaliDeveloper I finally understand that I have massively mislead you. ZIM `Language` should not have a Country variant because this is not supported by https://en.wikipedia.org/wiki/ISO_639-3. So if a ZIM has one, this is a bug in the ZIM.

**Pull request closed without merging**
