### PR TITLE
Removed the restriction popup from PS variant which was showing at start.

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
* Since now we have a way to load the sideloaded zim files in the application(https://github.com/kiwix/kiwix-android/pull/3979) so this popup does not make sense. Therefore, we are removing this.
* Removed all the code from the project related to this popup.
* Refactored the test cases, and removed the unnecessary test cases.
* Removed the restriction message showing on the `Help Screen`.

### CODE REVIEW

**Comment by kelson42** [comment]
@MohitMaliFtechiz Can younplease rebase?

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz Can younplease rebase?

@kelson42 Sure.

We have this same message in our help screen, should we remove this from there also? IMO we should improve this message to tell about the restriction(That directly scanning will not work due to Play Store restriction, but you can load your existing zim files via file picker).

Screenshot from 2024-09-30 18-07-55

**Comment by kelson42** [comment]
> > @MohitMaliFtechiz Can younplease rebase?
> 
> 
> 
> @kelson42 Sure.
> 
> 
> 
> We have this same message in our help screen, should we remove this from there also? IMO we should improve this message to tell about the restriction(That directly scanning will not work due to Play Store restriction, but you can load your existing zim files via file picker).
> 
> 
> 
> Screenshot from 2024-09-30 18-07-55
> 
> 

yes please

**Comment by kelson42** [comment]
@MohitMaliFtechiz CI does not pass... it seems the CI is getting unstable to me.

**Comment by MohitMaliFtechiz** [comment]
Yes, The emualtor sometimes does not boot for custom app test cases https://github.com/kiwix/kiwix-android/actions/runs/11110754116/job/30871013812?pr=4010. I have fixed this in https://github.com/kiwix/kiwix-android/pull/4006/commits/05eecc2218053203bb0eaf9863e819cd5b2479d2.

**Comment by kelson42** [comment]
@MohitMaliFtechiz To me this is not fixed, if we see it still hanging!

**Comment by kelson42** [comment]
@MohitMaliFtechiz Please remove the whole message because this is too complicated that anyone really understand how this scanning function work (actually this is meanwhile so complicated to scan the fs, that we should maybe consider to remove it fully).

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz To me this is not fixed, if we see it still hanging!

@kelson42, I re-ran the job, so it is running. Also, I have improved the CI in https://github.com/kiwix/kiwix-android/pull/4006, which helps prevent test cases from hanging. (I will analyze the CI behavior in upcoming PRs if it still hangs; for this, we have a ticket: https://github.com/kiwix/kiwix-android/issues/4001.)

> @MohitMaliFtechiz Please remove the whole message because this is too complicated for anyone really understand how this scanning function works

I agree with your point. So, should we remove the whole message and show only about the file picker only? The better message would be "To read your existing zim file from storage, use the file picker(+) icon in the library screen.".

> (actually this is meanwhile so complicated to scan the fs, that we should maybe consider to remove it fully).

@kelson42 I do not properly get it, are you talking about removing the scanning functionality or you are talking about removing the message we are showing?

**Review by kelson42 — CHANGES_REQUESTED** [review]
* This is a "ZIM" file, not a "zim" file
* We can keep this message even if I believe this is pretty useless (feature is self explaining)

**Comment by MohitMaliFtechiz** [comment]
@kelson42 Changes are done as you requested.

**Pull request merged**
