### PR TITLE
Gptshubham595 patch webviewimprove (bymistake i clicked close) 

### PR DESCRIPTION
**Pull request by gptshubham595**
Enhancement of Kiwixwebview.java file to load dat faster and store values in cache so to reload it is much faster

### CODE REVIEW

**Comment by gptshubham595** [comment]
@abdulwd @mhutti1 @sonusourav @kelson42 review it pleade

**Comment by gptshubham595** [comment]
@soloturn review this once

**Comment by prajurock** [comment]
Squash your commits

**Comment by mhutti1** [comment]
Please submit a single commit for this.

**Pull request closed without merging**
