### PR TITLE
Made language selection dialog more compact #342

### LINKED ISSUE #342: More "compact" language selection dialog
The current language selection dialog looks currently like this:

screenshot

Not so many languages are displayed at the same time which forces quite a bit of scrolling. I think we should but the language name in the language itself into parenthesis juste behind the language name in UI language. So everything on one line. This would allow to display more languages at the same time and need less scrolling.

### PR DESCRIPTION
**Pull request by Ryan10145**
The current language selection dialog does not display a lot of languages at the same time, making scrolling tedious. This makes each language only take up 1 line, causing the list to become more compact. Additionally, more fonts were added so all localized language names are now displayed. Fixes #342

### CODE REVIEW

**Comment by kelson42** [comment]
@Ryan10145 I have rebased against master to avoid your merge on the feature branch (and also resync the branch against last master commit).

**Comment by divadsn** [comment]
About those font files, are those from Google Fonts? If not, what's the license?

**Comment by Ryan10145** [comment]
Lohit-Punjabi, DDC_Uchen  - SIL OpenFontLicense
Does OFL require attribution?

Kaputa - I found a version under GPL 3.0 from https://github.com/textualworks/kaputa-font.
I'll update the font file, update the credits, and make a new pull request

Digohweli - This one is bothering me. At first, I thought it was free, but I just relooked it and I can't tell. I think I'll remove this one for now and try to find another one.

**Comment by kelson42** [comment]
@Ryan10145 This is not an open-source font. But it seems we are allowed to distribute it. See http://scriptsource.org/cms/scripts/page.php?item_id=entry_detail&uid=kstzk8hbg4. I would re-introduce it and put that link as "proof". If at some point we have any problem, we could proove our good faith and removed it if needed.

**Pull request merged**
