### PR TITLE
Fixed: Create only one reader and use it everywhere.

### LINKED ISSUE #3536: Create only one reader and use it everywhere
During the migration from access ZIM file via path to access ZIM file via filedescriptor, it appears that each feature has its own way to access the ZIM files. This is seems wrong because yhis is uselessly complicated and bug prone (what actually happened).

It should be like this:
* One handler/reader per ZIM file for the whole app and all its features
* Once place to open a file/create/destroy this handler

See also: https://github.com/kiwix/kiwix-android/pull/3535

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #3536 

* Now we are creating only one reader for both `zimFile`, and `assetFileDescriptor` and using it for all the features. We have created a helper class to handle all the creation of `filehandler` whether we have opened the ZIM File via `FileDescriptor` or `FilePath`. It handles all the related details inside it and avoids the rewriting of code(one for filePath, and the second for fileDescriptor) which is bug-prone like we have faced in https://github.com/kiwix/kiwix-android/pull/3535.
* Also we have introduced a new method in this helper class called `canOpenInLibkiwix()` which ensures that the zim file can be opened in libkiwix or not before passing it to the libkiwix to avoid any crash thrown by the libkiwix see https://github.com/kiwix/kiwix-android/issues/3636#issuecomment-1876742791.

### CODE REVIEW

**Comment by kelson42** [comment]
@MohitMaliFtechiz I had onlt a quick overview and my feelings are a bit mixed... I don't have a definitive opinion, but none of history, notes or bookmarks should actually still deal - at this level fd/path - with the ZIM files.

**Comment by kelson42** [comment]
The architecture is weak, you don't need to open a file with libkiwix to know if it will be a success or not. So don't do it. Exactly the same kind of misconception like I have explained in length in #3649 (which has not been updated following my instructions). We are running out of time.

**Comment by MohitMaliFtechiz** [comment]
> The architecture is weak, you don't need to open a file with libkiwix to know if it will be a success or not. So don't do it.  If you really need a method canOpenInLibkiwix(), which I really doubt, don't use libkiwix to do that. You already have all the information you need to know if it will work or not.

@kelson42 We are not opening the file/fileDescriptor in libkiwix to check if it can open or not in libkiwix. `canOpenInLibkiwix()`  is an Android method that is created by us, it is not a libkiwix function. We know how `libkiwix` opens a `file` or `fileDescriptor`, so in this function, we are validating that. e.g. for a file, it should be readable, and `fileDecriptor` should able to open via path. so this function is checking this for both before passing anything to libkiwix.


> in addition, I see no reason why we have two different class to open a handle a ZIM via path or fd, it should be one class with two differrent constructors.

I have done this to make it a well-structured/separate concern and reduce the complexity of methods inside the class since both have different ways to open and manage the ZIM files. If you want to make it one class so okay I am making the changes.

**Comment by gouri-panda** [comment]
@MohitMaliDeveloper small conflicts are here. @kelson42 what do you think about the @MohitMaliDeveloper latest comment?

**Comment by MohitMaliFtechiz** [comment]
@gouri-panda All the conflicts and project compilation errors have been resolved.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Please renase, this time I would really like to meege

**Pull request merged**
