### PR TITLE
Fixed: Automatically publish to PlayStore for internal testing team.

### LINKED ISSUE #3942: Automatically publish to PlayStore for internal testing team
Internal testers have to install manually the nightlies to be able to test latest codebase. At least to me, this is already a bit too cumbersome because:
* I have to be on the front of the workstation
* I have to actively do the operation

For macOS/iOS, we have an other model which is pretty good IMHO: Each Monday, during the night, latest dev version is published on Testflight. This allows me effortless to test and play with cutting edge version and test latest bug fixes/ features.

I would like to have the same with Kiwix Android.

Similar to #1777

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #3942

* Implemented a method to automatically generate a unique version code by calculating the number of days from the reference date (July 17, 2024) to the current date and adding this value to the base version code (231101) from the last release.
* Added a workflow that automatically generates the bundle and uploads it to internal testing every Monday at 12:00. This workflow will also trigger under the `internal_testing` tag.
* Since we are implementing this, it is necessary to directly release the bundle to internal testing instead of placing it in draft (to eliminate manual steps), so we have refactored our code accordingly.
* Updated the action versions to the latest ones in our workflows.

### CODE REVIEW

**Comment by kelson42** [comment]
@MohitMaliFtechiz Please use latest version of each action.

**Comment by MohitMaliFtechiz** [comment]
@kelson42 I have updated the action versions.

**Comment by MohitMaliFtechiz** [comment]
> Why you don't have kept a simple function like before? You should not name an object class like a function.

@kelson42 The previous code was written twice in both app and core Gradle files, which duplicating the main logic for generating the version code, and could increase the chances of errors. I have created this object class to put the main logic of generating version code in one place to avoid duplicity and potential errors/mistakes. Thanks for your suggestion, the `VersionCodeGenerator` would be a better name for this object class.

**Comment by kelson42** [comment]
@MohitMaliFtechiz We have no way to bundle functions in a file without creatinf an object class?

**Comment by MohitMaliFtechiz** [comment]
We are using this function in the core module for setting `buildConfigField`, and here this top-level function is not working. However, this is working on setting the version code to the app. For setting `buildConfigField` it is not working because Gradle trying to evaluate the build script before our Kotlin function can run. So direct top-level function is not working here. But a top-level extension function is working here so I have made changes according to it.

**Review by kelson42 — APPROVED** [review]
LGTM

**Pull request merged**
