### PR TITLE
Fixes changing title name on opening same file multiple times

### LINKED ISSUE #1004: Title of zim files changes when opened multiple times
**Describe the bug**
If the same file is opened in a new tab, the title of the file changes every time. The title is randomly chosen from one of the downloaded files. While the content remains the same, only the title of the file changes.

**Expected behavior**
The title of the file should remain the same.

**Steps to reproduce the behavior:**
1. Open a file and observe the file title.
2. Open the same file in a new tab and observe the file title again.
3. Do it multiple times and different names are observed each time.

**Screenshots**
title name issue

**Environment**
- Device : Redmi 4
- OS version : Android 7.1

### PR DESCRIPTION
**Pull request by sonusourav**
Fixes #1004 

Changes: 
Removed updateTitle() from webViewUrlFinishedLoading().

Screenshots/GIF for the change: 
title name fix

### CODE REVIEW

**Comment by sonusourav** [comment]
@mhutti1 could you please review?

**Comment by sonusourav** [comment]
@abdulwd Could you please review?

**Comment by sonusourav** [comment]
@mhutti1 could you please review this?

**Comment by sonusourav** [comment]
@abdulwd Could you please review this also?

**Comment by abdulwd** [comment]
@sonusourav Can you please squash your commits and force push the changes?

**Comment by sonusourav** [comment]
> 
> 
> @sonusourav Can you please squash your commits and force push the changes?

@abdulwd squash and force-push done.

**Pull request merged**
