### PR TITLE
Fixed App crash issue #975 [ while tapping download notification and changing or stopping the download ]

### PR DESCRIPTION
**Pull request by CodetoInvent**
Fixes #1161
I have fixed the bug issued by @siddharth2010 [  #975 ] 
This is the case 1 [ while tapping download notification and changing or stopping the download ]
which was issued by  @siddharth2010 at #975 

Notification Tap crash FIXED Link :
https://drive.google.com/file/d/1na4DFsWZuGRnI1acxJYZ8D20hJROYQSR/view?usp=sharing

### CODE REVIEW

**Comment by prajurock** [comment]
I will suggest instead of writing Fixed issue no.Give some proper heading.

**Comment by CodetoInvent** [comment]
sure ill mention it

**Comment by iadeelzafar** [comment]
I'll suggest you to not open multiple PRs for the same solution. Both issues can be fixed in one PR. 
Either close this one or #1162

**Comment by CodetoInvent** [comment]
Actually i was about to close this PR. But thanks for reminding me this

**Pull request closed without merging**
