### PR TITLE
#1447 Can't open zim from external download 

### LINKED ISSUE #1447: Can't open zim from external download
**Describe the bug**
When you click open on a download of a zim it says "error can't open zim file"

**Expected behavior**
The zim file should open

**Steps to reproduce the behavior:**
1. click on [this](https://download.kiwix.org/zim/stack_exchange/dsp.stackexchange.com_en_all_2019-01.zim ) in chrome
2. click "open" after download completes
3. See error

**Environment**
- Version of Kiwix Android : develop/3.0
- Device : Nexus 5X
- OS version : 8.1.0

**Logs**
```
2019-09-06 15:02:36.192 22182-22397/org.kiwix.kiwixmobile E/kiwix: Exception reading article null from zim file
    java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] org.kiwix.kiwixlib.JNIKiwixReader.getContent(org.kiwix.kiwixlib.JNIKiwixString, org.kiwix.kiwixlib.JNIKiwixString, org.kiwix.kiwixlib.JNIKiwixString, org.kiwix.kiwixlib.JNIKiwixInt)' on a null object reference
        at org.kiwix.kiwixmobile.data.ZimContentProvider$TransferThread.run(ZimContentProvider.java:486)
```

### PR DESCRIPTION
**Pull request by macgills**
Fixes #1447 

Introduce ZImSource concept so we no longer explicitly rely on files specifically to open a zim
TODO:
- handle db migrations
- ensure opening video assets works
- check navigation when app is closed, at other destinations, already open on reader
- give some thought about how we identify bookmarks/history, currently it is possible to open the same underlying resource through 2 different methods so you could create bookmarks/history that are for the same exact thing but may present to the user as duplicates
- remove local aar

### CODE REVIEW

**Comment by kelson42** [comment]
We need to be careful with this PR. I guess we will need the next official Libkwix release to be sure it works fine. Maybe not to merge immediatly when it will work.

**Comment by mhutti1** [comment]
@kelson42 Could you explain more about what is changing under the hood with libkiwix here.

**Comment by kelson42** [comment]
@mhutti1 In a nutshell, to fix the two kiwix-android tickets of https://github.com/orgs/kiwix/projects/9, we have patch the libzim and libkiwix to be able to open a ZIM file from a filehandler (so far it was only possible from a filepath).

**Comment by mhutti1** [comment]
Ah, yes I remember this. If no-one else is working on it by the weekend I can have a look then

**Comment by kelson42** [comment]
@mhutti1 Great, be in touc with @veloman to eta testlibkiwixwith fd support.

**Comment by veloman-yunkan** [comment]
IMPORTANT: before merging this PR its history must be rewritten so that that the *.aar files added under `core/libs` are forgotten:

1. the `aar` file must be removed from `core/libs` so that the latest build from `kiwix-lib-app` is used instead
2. removing all versions of the custom-built aar from the history will help to reduce the size of this repository (each aar is about 30MiB and there are several of them).

**Comment by mhutti1** [comment]
Ok, I have looked at this a bit and I don't think we have a published android libkiwix lib so we can remove the .aar yet. Did we get this being built automatically?

**Comment by kelson42** [comment]
@mhutti1 would you be able to join on slack please to deal with the details with @veloman-yunkan ?

**Comment by mhutti1** [comment]
So I played about a bit and I would have thought opening a file from for example gmail directly would now be supported but it seems it isn't yet. Is this something we are looking for here @kelson42 ?

**Comment by kelson42** [comment]
@mhutti1 Not sure if gmail is in the scope of tis ticket? Do you mean going to gmail with a Browser and then download a zim file in attachement? Why not just downloading fron download.kiwix.org directly in a Browser like described in the ticket?

**Comment by mhutti1** [comment]
Clicking the download link in chrome does work. Opening a Gmail attachment doesn't. I also had issues opening from the file browser. I think we should definitely get this working if possible.

**Comment by kelson42** [comment]
@mhutti1 Which part of the still failing things require a fd opening? I don't think this is necessary for opening files from the file browser?!

**Comment by mhutti1** [comment]
So it seems if you download from gmail it works but previewing gives an opaque error. It also wont open on my samsung file browser. But I think this is probably an intent detection issue.

**Comment by kelson42** [comment]
Superseeded by #3527

**Pull request closed without merging**
