### PR TITLE
Fixed Multiple Files Download Results in Wrong Content Title In The Notification

### LINKED ISSUE #997: Multiple Files Download Results in Wrong Content Title In The Notification
**Describe the bug**

* Download multiple files at the same time, when the download is complete, the notification will show name of the content that was started downloading most recently.

* For example if you clicked to download multiple files, first you clicked on "A" and then "B". After A is downloaded, it's notification title will show "B"'s title because B was started downloading most recently. And when B is done downloading, it's success notification will also show "B" because it was the most recent one that was started downloading.

**Expected behavior**

* The file whose downloading is complete, it's name should be in the success notification rather than the name of the file that was put on download most recently.

**Steps to reproduce the behavior:**

1.  Download multiple files.
2.  After files are downloaded, see the success notifications.

**Screenshots**

**Environment**

Galaxy Nexus API 24

### PR DESCRIPTION
**Pull request by iadeelzafar**
### Changes: 

* Using bundle, adding Extras to each notification object.
* In the extras, adding notificationTitle for each object.
* Then getting the notificationTitle for each notification using Bundle.
* Displaying the notificationTitle for each notification accordingly.

### CODE REVIEW

**Comment by soloturn** [comment]
@iadeelzafar i did not try this one but i like the code :)

**Comment by iadeelzafar** [comment]
@soloturn It feels good to know that my written come is helping the community. :)

**Comment by mhutti1** [comment]
@iadeelzafar I think this is also an issue with the action when attempting to click the notification. Could you test this and then make an issue if you think it is. It should be able to be fixed with the same sort of fix.

**Comment by iadeelzafar** [comment]
@mhutti1 sure. I'll look into it.

**Pull request merged**
