### PR TITLE
Comparison: 2.5.1 against Develop

### PR DESCRIPTION
**Pull request by macgills**

### CODE REVIEW

**Comment by kelson42** [comment]
@mhutti1 @abdulwd @siddharth2010 I have asked @macgills to think about a new release of Kiwix-Android happening before all the tickets in the 3.0 mileonste are done. The main reason are (1) we have a few quite annoying bugs on 2.5.0 (2) a lot of work done during 2.4 release does not have reached the end-users (3) It makes already 2 months since last release and I want to release worse case every 2 months. I wanted first to make a maintenance release base of 2.5 code but @macgills told me that a release of the `develop` branch might be doable too. What are your opinion about that. I would really like that one of you update the Changelog so I can have an overview about what has been done since 2.4/2.5, this is mandatory and will also help to figure out about the naming of the release: 2.5.1, 2.6.0 or 3.0.

**Comment by macgills** [comment]
these are the notes I was taking as I was skimming:

ErrorActivity
New databases, migration needed
New help & home page
History
Intro
LanguageActivity
Add notes
New Tabs?
Multi select delete/share
Updated translations
Bug fixes/layout updates

I think these are the key areas that were updated from a user perspective

**Comment by abdulwd** [comment]
@kelson42 I would love to see the develop branch released. In addition to what @macgills has mentioned these items may be added to the changelog:

- Create a new initial landing page with suggested ZIM files that a user might want to download.
- Make the switching of tabs more intuitively and also show the preview of tabs.
- Improve language selection functionality allowing users to find the supported languages easily.
- Improve the bottom toolbar to make it more user-friendly.
- Improve the bookmarks screen with an option to show bookmarks from the current ZIM file or from all ZIM files.
- Add a screen to show the history of pages visited by the user.
- Move help to a separate screen.

I have justed picked them from my GSoC archive so some of them might be duplicate of what @macgills has mentioned.

In my opinion, we should name the release as 3.0 but since from now onwards we plan to release frequently we can change our versioning scheme to **`<YYYY>.<MM>.<NUMBER OF COMMITS ON RELEASE BRANCH>`**. I'm not sure if the latter approach makes much sense. 😕

**Comment by macgills** [comment]
@abdulwd we are [semantically versioned](https://semver.org/) now
```
ext {
  versionMajor = 2
  versionMinor = 5
  versionPatch = 1
}

private String generateVersionName() {
  "${ext.versionMajor}.${ext.versionMinor}.${ext.versionPatch}"
}

/*
* max version code: 21-0-0-00-00-00
* our template    : UU-D-A-ZZ-YY-XX
* where:
* X = patch version
* Y = minor version
* Z = major version (+ 20 to distinguish from previous, non semantic, versions of the app)
* A = number representing ABI split
* D = number representing density split
* U = unused
*/

private Integer generateVersionCode() {
  20 * 10000 +
      (ext.versionMajor * 10000) +
      (ext.versionMinor * 100) +
      (ext.versionPatch)
}
```

**Comment by kelson42** [comment]
@macgills @abdulwd 3.0 has also my preference, regarding the amount work done. Please update the Changelof file. I will create a short list of things to do before the release.

**Comment by kelson42** [comment]
I don't think we are ready to carry one with this PR. I would prefer to solve the last pbs first on develop branch. Therfore, why keeping this PR open?

**Comment by macgills** [comment]
@kelson42 this pr has served its purpose of facilitating discussion, closing

**Pull request closed without merging**
