### PR TITLE
Share button is not working in Device Fragment #945

### PR DESCRIPTION
**Pull request by prajurock**
Share button is not working in Device Fragment #945

Changes:For API 24 file transfer changes so checking the api level.

### CODE REVIEW

**Comment by prajurock** [comment]
@siddharth2010 Can you review this?

**Comment by siddharth2010** [comment]
Sure

**Comment by prajurock** [comment]
Thanks. @siddharth2010

**Comment by soloturn** [comment]
@prajurock would you be able to rebase your test branch onto the current master so there is no conflict any more and the continuous integration runs through?

**Comment by prajurock** [comment]
Yes sure

**Comment by prajurock** [comment]
@soloturn please check pull request #963
I rebase the branch to master and pull new request.

**Comment by abdulwd** [comment]
@prajurock Please do not open multiple PRs for the same issue. You can always force push to the same branch. As of now please close any one of them.

**Pull request closed without merging**
