### PR TITLE
replaced the deprecated setHasOptionsMenu(true) with new API

### LINKED ISSUE #3245: Replace depreacted API with new ones
I suggested updating the deprecated methods with new API that google provided as deprecated methods cause problems in long run
**Describe the bug**

For Example :
```
Deprecated
androidx.activity.ComponentActivity now implements MenuHost, an interface that allows any component, including your activity itself, to add menu items by calling addMenuProvider(MenuProvider) without forcing all components through this single method override. Each MenuProvider then provides a consistent, optionally Lifecycle-aware, and modular way to handle menu item selection for the menu items created by that provider. Replace usages of this method with one or more calls to addMenuProvider(MenuProvider) in your Activity's onCreate(Bundle) method, delegating menu item selection to the individual MenuProvider that created the menu items you wish to handle.
```
**Expected behavior**
No Deprecation warning

-->

**Screenshots**

**Environment**
- Version of Kiwix Android : 3.6.0
- Device :  Emulator
- OS version : 12

**Logs**

### PR DESCRIPTION
**Pull request by criticalAY**
Google has deprecated the setHasOptionsMenu(true) in  early 2022 and we have new better API to handle menu 

Fixes #3245
I have replaced the deprecated method with new API which makes the flow more fluent

**Screenshots** 
Tested on OnePlus Nord CE

### CODE REVIEW

**Comment by criticalAY** [comment]
@kelson42  I made no change to default.json.bak but it's still in commit any reason why?

**Comment by kelson42** [comment]
@criticalAY Please clarify all of this with @MohitMaliDeveloper

**Comment by MohitMaliFtechiz** [comment]
> @kelson42 I made no change to default.json.bak but it's still in commit any reason why?

@criticalAY , Sorry for late reply, Your develop branch is outdated.
* Please update you develop branch first (most probably reason for changing default.json.bak file).
* Rebase this PR (so i can debug in more details why this is changing).
* Please fix the lint failure as well.

**Comment by criticalAY** [comment]
ok will do

**Comment by kelson42** [comment]
@criticalAY Please rebase and resolve conflicts

**Comment by criticalAY** [comment]
yes will do it tonight

**Comment by kelson42** [comment]
@criticalAY rebase, don’t merge

**Comment by kelson42** [comment]
@MohitMaliFtechiz @criticalAY Can we move forward her, lots of jabbering, but no concrete progresses.

**Comment by MohitMaliFtechiz** [comment]
> @kelson42 I made no change to default.json.bak but it's still in commit any reason why?

As i said your develop branch was outdated that time that's why ```default.json.bak``` showing as modified. Now i have fixed it.

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz @criticalAY Can we move forward her, lots of jabbering, but no concrete progresses.

Yes, 
* I have rebase the PR and removed unnecessary added ```default.json.bak``` file from this PR.
* Fixed the lint failure.
* Removed deprecated method and unused code.

Once CI will pass we are good to move forward with this PR.

**Review by MohitMaliFtechiz — APPROVED** [review]

**Pull request merged**
