### PR TITLE
Localisation updates from https://translatewiki.net.

### PR DESCRIPTION
**Pull request by kelson42**
We have setup a new way to sync UI translation with Translatewiki. The Kiwix Android UI strings will be directly import/export by Translatewiki bot in kiwix-android repository. To be precise, in the `translatewiki` branch. The PR having still to be done manually.

This is the first patch/batch. It looks good to us, except the `string-array` nodes which are missing. This is not supported so far by the Translatewiki bot, but I'm not sure if this is real problem or no.

### CODE REVIEW

**Comment by kelson42** [comment]
For some reason it seems the linting complains about `--` in the `strings.xml`. To me it sounds silly, but this problem will anyway vanish one time #1591 will be merged.

**Comment by macgills** [comment]
I'll await that being merged to dev and dev being merged in before approving

**Comment by kelson42** [comment]
We still have problems with the plurals forms and this seems really complicated to handle that properly. So I have decided to get rid of this stuff for the moment. PR blocked by #1606

**Comment by kelson42** [comment]
@nikerabbit @translatewiki a few commits ago in `develop` branch, we have removed the use of `plurals` nodes in the XML. The reason is that it was creating problems with the translated versions and there was no easy other way to fix them. Unfortunately, the last commit of @translatewiki still have plurals in the commits! Could you fix it?

**Comment by Nikerabbit** [comment]
> @Nikerabbit @translatewiki a few commits ago in `develop` branch, we have removed the use of `plurals` nodes in the XML. The reason is that it was creating problems with the translated versions and there was no easy other way to fix them. Unfortunately, the last commit of @translatewiki still have plurals in the commits! Could you fix it?

Sorry I was traveling/sick. Can you explain what kind of problems you were having? With our new plural validators there shouldn't be any syntax problems anymore.

**Comment by macgills** [comment]
@Nikerabbit 
```
  The first 3 errors (out of 42) were:
  /home/travis/build/[secure]/[secure]-android/core/src/main/res/values-cs/strings.xml:236: Error: The plurals "books_count" in values-cs has no declaration in the base values folder; this can lead to crashes when the resource is queried in a configuration that does not match this qualifier [MissingDefaultResource]
    <plurals name="books_count" fuzzy="[secure]">
```

We deleted the plurals resource `books_count` because we didn't want to deal with the amount of work pluralisation takes and have decided for the agnostic form string resource `%s book(s)`

Unfortunately other language resources still contain the plurals resource according to the build that ran yesterday as can be seen in the `cs` locale here.

**Comment by kelson42** [comment]
@Nikerabbit Unfortunatly, after the last commit https://github.com/kiwix/kiwix-android/pull/1590/commits/d4f5821321da272e39a26db84da482f44629e083, the plurals are still there and CI still fails https://travis-ci.com/kiwix/kiwix-android/builds/140804389#L2675.

**Comment by Nikerabbit** [comment]
Yeah, fixing that would require manually updating all those translations, which requires language skills.

I am doubtful that this change to not use proper plurals results in less work.

**Comment by kelson42** [comment]
@Nikerabbit Deleting a few articles on TW is not a big deal for me, but what is the alternative considering specific Android constraints? Is that documented somewhere?

**Comment by macgills** [comment]
@Nikerabbit I am unaware of how complete the translations are but we thought it would be easiest.
the English plurals resource looked like
```
  <plurals name="books_count">
    <item quantity="one">%s book</item>
    <item quantity="other">%s books</item>
  </plurals>
```
but another language might need
```
  <plurals name="books_count">
    <item quantity="zero">%s [zero form]</item>
    <item quantity="few">%s [few form]</item>
    <item quantity="many">%s [many form]</item>
  </plurals>
```
which has no overlap with the source english file at all. I still don't quite know how the translation works so maybe this case was supported but I think we got a lint warning that it wasn't

**Comment by Nikerabbit** [comment]
Can you find those lint warnings? I'd like to see if it is something that is taken care by our new validators, or can be taken care by them if not already done so. The idea is that you wouldn't need to worry about how plurals work in different languages, that knowledge is present in our system (for most common languages at least) and the output from us should be valid for android without any linting or build issues.

**Comment by macgills** [comment]
@Nikerabbit [this build](https://travis-ci.com/kiwix/kiwix-android/builds/138596143)
```

  The first 3 errors (out of 40) were:
2668
  /home/travis/build/[secure]/[secure]-android/core/src/main/res/values-cs/strings.xml:236: Error: For locale "cs" (Czech) the following quantities should also be defined: few [MissingQuantity]
2669
    <plurals name="books_count">
2670
    ^
2671
  /home/travis/build/[secure]/[secure]-android/core/src/main/res/values-ar/strings.xml:255: Error: For locale "ar" (Arabic) the following quantities should also be defined: few, many, two, zero [MissingQuantity]
2672
    <plurals name="books_count">
2673
    ^
2674
  /home/travis/build/[secure]/[secure]-android/core/src/main/res/values-tr/strings.xml:262: Error: For locale "tr" (Turkish) the following quantities should also be defined: one [MissingQuantity]
2675
    <plurals name="books_count">
2676
    ^
```
15 days old, I don't know if there has been a validator update since

**Comment by macgills** [comment]
@Nikerabbit do you want me to add the plural back in and address the missing quantities? Or we could try a different way, instead of mixed singular/plural `%s book(s) ` we could simply pluralise `books: %s` if that could be easier?

**Comment by macgills** [comment]
@Nikerabbit I'm back from holidays so if you need something from me don't hesitate to ask.
Latest build error:
```

  The first 3 errors (out of 41) were:
2743
  /home/travis/build/[secure]/[secure]-android/core/src/main/res/values-lb/strings.xml:120: Error: The plurals "books_count" in values-lb has no declaration in the base values folder; this can lead to crashes when the resource is queried in a configuration that does not match this qualifier [MissingDefaultResource]
2744
    <plurals name="books_count">
2745
             ~~~~~~~~~~~~~~~~~~
2746
  /home/travis/build/[secure]/[secure]-android/core/src/main/res/values-cs/strings.xml:236: Error: The plurals "books_count" in values-cs has no declaration in the base values folder; this can lead to crashes when the resource is queried in a configuration that does not match this qualifier [MissingDefaultResource]
2747
    <plurals name="books_count" fuzzy="[secure]">
2748
             ~~~~~~~~~~~~~~~~~~
2749
  /home/travis/build/[secure]/[secure]-android/core/src/main/res/values-sc/strings.xml:251: Error: The plurals "books_count" in values-sc has no declaration in the base values folder; this can lead to crashes when the resource is queried in a configuration that does not match this qualifier [MissingDefaultResource]
2750
    <plurals name="books_count" fuzzy="[secure]">
2751
             ~~~~~~~~~~~~~~~~~~
```

**Comment by macgills** [comment]
@Nikerabbit is there another method of communication you would prefer, perhaps something more synchronous? I am on the kiwix slack and available to call/chat Mon-Fri, 9-5(GMT)

**Comment by Abijeet** [comment]
Hello @macgills 

Sorry for the delay in responding to your queries. Niklas requested me to take a look at this issue. I work with him on Translatewiki.net. 

For now we've deleted the translations that had the old plural translation syntax (`lb`, `cs`, `fr`). We will be adding a plural validator to the project in the near future that will ensure that the number of plural forms for each language are added appropriately.

I see that the build is still failing. Let us know if there is anything else you need from us.

**Comment by macgills** [comment]
@Abijeet there are now 40 errors across 3 categories
image
image
image
image
image

While none of these lint errors are critical they would be nice to have. I can run automatic fixes in android studio to correct them but I think TW producing lint error free translations is the end goal. Another alternative is we can simply not check these specific lint issues

**Comment by Abijeet** [comment]
Hi @macgill,

Thanks for bringing this to our notice. We will look at adding another validator that checks translations for certain characters, and recommends that translator's use a "suggested" one instead. We expect that this will be useful for other projects as well.

This will take time though, so in the meantime, we recommend that you auto-fix this via Android Studio and merge this patch.

**Comment by macgills** [comment]
@Abijeet just before I merge this can you clarify why some strings have `fuzzy=true` as an attribute?
I wouldn't believe this would have any effect in app

**Comment by kelson42** [comment]
@macgills This is a tag added by the https://translatewiki.net/wiki/User:FuzzyBot, a kind of warning, most of the time because the master in English as changed and the local translation needs to be revalidated.

**Pull request merged**
