### PR TITLE
Fix lint warnings in bookmark package

### LINKED ISSUE #2020: Fix lint warnings in bookmark package
**Is your feature request related to a problem? Please describe.**

There are lint warnings and errors in bookmark package

**Describe the solution you'd like**

Fix all the lint warnings

**Additional context**

Parent issue #1274

### PR DESCRIPTION
**Pull request by sonusourav**
Fixes #2020

### CODE REVIEW

**Comment by macgills** [comment]
I feel like this should not have been done when you are converting bookmarkactivity to kotlin in another PR

**Comment by sonusourav** [comment]
Yeah @macgills . I agree but since I was doing package-wise so I thought why to leave it. In-fact the generic varargs warning could be resolved once this activity gets written in Kotlin, which is opened in another PR, so I was not bothered much.

**Comment by sonusourav** [comment]
> 
> 
> There's still a warning on `onCreate`.
> Two more other warnings are there check if you can get rid of them. Use Shift + F2 to find them in a file.

Changes done.

**Comment by macgills** [comment]
You are just going to have to port these changes to bookmarksActivity if you haven't already done so, there is really not much point in doing things twice especially when you are making a merge conflict for yourself

**Comment by sonusourav** [comment]
> 
> 
> You are just going to have to port these changes to bookmarksActivity if you haven't already done so, there is really not much point in doing things twice especially when you are making a merge conflict for yourself

Removed Bookmark Activity from this PR.

**Comment by sonusourav** [comment]
@macgills Please review this.

**Pull request merged**
