### PR TITLE
Add Ripple Effect to Get Content Button

### PR DESCRIPTION
**Pull request by MayankChuriwal**
Ripple effect #477

The ripple effect is more visible now and the button also now looks better with gradient styling and the ripple effect is more visible.

whatsapp-video-2018-02-25-at-3 48 17-pm

Please review @mhutti1

### CODE REVIEW

**Comment by ISNIT0** [comment]
👌 LGTM - I assume you've checked API versions etc?

**Comment by RajaVamsi11** [comment]
@MayankChuriwal  Adding ripple effect  requires minimum API level of 21(lollipop), but our minimum target level in our app 14. So adding this  will  be problem to users who have mobiles API level less than 21.
For detail you can checkout https://developer.android.com/reference/android/graphics/drawable/RippleDrawable.html

**Comment by MayankChuriwal** [comment]
@RajaVamsi11 Can we use other open source repo in the project? I mean there's a repo on GitHub to add ripple effect even in API version of less than 21.

**Comment by RajaVamsi11** [comment]
@MayankChuriwal I don't know ,you have to ask @mhutti1 @srv-twry .

**Comment by RajaVamsi11** [comment]
@mhutti1  Yes it is a duplicate of #484

**Comment by MayankChuriwal** [comment]
Fixed the issue of Ripple Effect in API < 21. Please review @mhutti1

**Comment by mhutti1** [comment]
@RajaVamsi11 was first with this. Closing as duplicate of #484

**Pull request closed without merging**
