### PR TITLE
Issue #365 Search Cancel button (X) must be aligned to right

### PR DESCRIPTION
**Pull request by Koundinyalanka**
This issue can be resolved using setMaxWidth

### CODE REVIEW

**Comment by Koundinyalanka** [comment]
Please check this @mhutti1

**Comment by Koundinyalanka** [comment]
Ok closing pull request

**Comment by srv-twry** [comment]
@Koundinyalanka Why did you close this ?

**Comment by Koundinyalanka** [comment]
@srv-twry  I will update my code, test it and submit pull request again... :)

**Comment by srv-twry** [comment]
@Koundinyalanka Then please update it in this PR only. Opening unnecessary PR's isn't recommended at all. As i said earlier, if you aren't comfortable with version control then take your time, learn it first and then do the necessary changes in this PR only. You just can't survive in software development specially OSS development without it. :smile:

**Comment by dhruv-smd** [comment]
@srv-twry dude, I have been observing you for the last couple of days. You are being too arrogant. Its good that you know stuff but this gives you no right to your arrogant behavior. Such arrogance so early in life will take you nowhere. No one is born with the knowledge of this stuff and people are here to learn and will learn from such experiences. So stop suggesting people when they start doing things and when not. I am not saying you are wrong . Dude but your tone, there is something wrong with it. I don't know you personally but I can tell you are full of arrogance.Stop poking your nose everywhere. This is not the right way to show that you have knowledge about the subject. I am telling these things for your own good. Remeber you are **NOT** the boss here. If the members find anything wrong they will tell themselves.

**Comment by mhutti1** [comment]
@srv-twry has been providing helpful suggestions across the project and making our lives as mentors easier. You are correct that sometimes the tone of these responses can seem harsh however constructive criticism is an essential part of any project and @srv-twry 's answers are normally both correct and insightful. If you have a problem with the way someone is speaking you should take it up personally with them by perhaps using the email address that they have provided (although unfortunately you have not) and if things do not change you can take the issue up with us. Posting this response was not in any way constructive.

**Comment by srv-twry** [comment]
@dhruv-smd 
> @srv-twry dude, I have been observing you for the last couple of days. You are being too arrogant. Its good that you know stuff but this gives you no right to your arrogant behavior. Such arrogance so early in life will take you nowhere. No one is born with the knowledge of this stuff and people are here to learn and will learn from such experiences. So stop suggesting people when they start doing things and when not. I am not saying you are wrong . Dude but your tone, there is something wrong with it. I don't know you personally but I can tell you are full of arrogance.Stop poking your nose everywhere. This is not the right way to show that you have knowledge about the subject. I am telling these things for your own good. Remeber you are NOT the boss here.

**No comments**

>  If the members find anything wrong they will tell themselves.

Exactly, if the mentors find anything wrong in my PR reviews or comments, they will tell me too.
Thanks.

**Pull request closed without merging**
