### PR TITLE
Fix #929 Add "Support Kiwix" item in options menu

### LINKED ISSUE #929: Add "Support Kiwix" item in app menu
It would be nice/useful to have a "Support Kiwix" list item in the menu (probably below "Settings")
screenshot_20190201-171427

The item would be an external link to https://www.kiwix.org/support

### PR DESCRIPTION
**Pull request by 287mdsahil**
#### Changes: 
1. Added _support_kiwix_ item in _menu_main.xml_.
2. Added a string resource for the item title.
3. Made changes in _MainActivity.xml_. When the "Support Kiwix" option is pressed, it opens an external link to https://www.kiwix.org/support

### CODE REVIEW

**Comment by abdulwd** [comment]
Please rebase your branch on master.

**Comment by abdulwd** [comment]
Also, format your code following https://github.com/kiwix/kiwix-android/blob/master/docs/codestyle.md.

**Comment by 287mdsahil** [comment]
@abdulwd why is it creating conflicts?
I did exactly what was told in the link you sent.
image

Is the above config correct?

**Comment by abdulwd** [comment]
@287mdsahil We are using continuation indent of 4 instead of 2 as per Square's code style. It was incorrectly mentioned and we have updated that in #959. You should pull the latest code from the master and then rebase your branch and squash the 2 commits into 1 and then force push the changes.

**Comment by 287mdsahil** [comment]
Okey, thanks.
On it

**Comment by 287mdsahil** [comment]
@abdulwd I messed up a bit initially. I think I have corrected it. Please review the changes.

**Comment by abdulwd** [comment]
@287mdsahil As you can see there are conflicting files. You should pull the latest changes from the master branch and then work on this issue. You can delete this branch and then work on it again. You can follow these steps:
* `git checkout master`
* `git remote add upstream https://github.com/kiwix/kiwix-android.git` - Run this command only if you have not added this remote before.
* `git pull upstream master`
* `git branch -D 287mdsahil/issue#929` - Before running this command make sure you have copied your changes somewhere, maybe in a `.txt` file as it will delete this branch.
* `git checkout -b 287mdsahil/issue#929`
* Paste the changes in the relevant files.
* Make sure you have imported the Square's code style and reformat the files which you have changed using `Ctrl + Shift + L`.
* Commit and then force push the changes using `git push -f origin 287mdsahil/issue#929`

If you need any help you search on stackoverflow.com, if you're not able to proceed further feel free to ping me.

**Comment by 287mdsahil** [comment]
@abdulwd Do I have to squash the extra commit (8fffc5e) ? Please review the changes.
Thanks.

**Comment by abdulwd** [comment]
@287mdsahil You can leave that for now but in future remember to make one commit per PR if there are not many changes.

**Pull request merged**
