### PR TITLE
Added the 'Export bookmarks' feature.

### LINKED ISSUE #822: Export bookmarks feature
A gentleman from Australia wrote to say that upon reinstall he'd lost all of his bookmarks. Maybe find a way to export it?

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #822

* The application now exports the 'bookmark.xml' file to the 'Downloads/org.kiwix...' folder.
* Introduced an export bookmark feature in the settings screen, allowing users to export all bookmarks with a simple click easily. A dialog prompt appears before exporting, indicating where the exported bookmarks will be saved.
* A test case for this change was added to our settings test.

https://github.com/kiwix/kiwix-android/assets/34593983/6d795cde-44a5-4a2b-af0e-1626f4cbba63

https://github.com/kiwix/kiwix-android/assets/34593983/ec2623ba-3a21-420b-b703-058792d2896b

### CODE REVIEW

**Comment by kelson42** [comment]
@MohitMaliFtechiz Thank younfor this PR:
* Does it mean bookamrks are handled now in libkiwix and not in Objectbox?
* Why exporting the library.xml? I see no vakue?
* would you be able to code the import as well so the user just has to choose the bookamrks.xml and the he recovers his bookmarks?

**Comment by MohitMaliFtechiz** [comment]
> Does it mean bookamrks are handled now in libkiwix and not in Objectbox?

@kelson42 Yes, now we are saving and retrieving the bookmarks in libkiwix.

> Why exporting the library.xml? I see no value?

`library.xml` contains the favicon and ZIM file path of the saved bookmarks so without exporting the `library.xml` we can't open the bookmark and the favicon will not be displayed on the bookmark screen.

> would you be able to code the import as well so the user just has to choose the bookamrks.xml and the he recovers his bookmarks?

@kelson42 Yes, we can implement functionality in our application and guide the user to select these two files when importing the bookmarks because we need these two files to properly import the bookmarks. I was also thinking about it and i purposed this in group for your feedback.

**Comment by kelson42** [comment]
I really see a peovlem that library.xnl is mandatory to import bookmark.xml. Please open an issue at kiwix/libkiwix.

**Comment by MohitMaliFtechiz** [comment]
@kelson42 I have opened a ticket in libkiwix https://github.com/kiwix/libkiwix/issues/1069 for this.

**Comment by kelson42** [comment]
@MohitMaliFtechiz I believe, at this time, you don't understand how the import of bookmarks will woek without having the library.xml exported/imported. Please complete the feature with only the export feature like requested first.

**Pull request merged**
