### PR TITLE
refactor: Package by feature

### LINKED ISSUE #469: Make package structure robust
**Is it a ?**

- [ ] Bug Report

- [ ] Feature Request

- [x] Refactor

#### Description

Right now the package structure isn't very good. Infact it isn't followed very well. It should be made robust and code should be packaged into different sections on the basis of features. It is crucial before trying to make the application testable.

@mhutti1 @brijeshshah13  views ?

### PR DESCRIPTION
**Pull request by srv-twry**
Fixes #469

Changes: New package structure

```
.
├── common
│   ├── base
│   │   ├── BaseActivity.java
│   │   ├── BasePresenter.java
│   │   └── contract
│   │       ├── Presenter.java
│   │       └── ViewCallback.java
│   ├── data
│   │   ├── content_provider
│   │   │   └── ZimContentProvider.java
│   │   ├── database
│   │   │   ├── BookDao.java
│   │   │   ├── BookmarksDao.java
│   │   │   ├── entity
│   │   │   │   ├── BookDataSource.java
│   │   │   │   ├── BookmarksSpec.java
│   │   │   │   ├── LibraryDataSource.java
│   │   │   │   ├── NetworkLanguageSpec.java
│   │   │   │   └── RecentSearchSpec.java
│   │   │   ├── KiwixDatabase.java
│   │   │   ├── NetworkLanguageDao.java
│   │   │   └── RecentSearchDao.java
│   │   └── network
│   │       ├── KiwixService.java
│   │       └── UserAgentInterceptor.java
│   ├── di
│   │   ├── components
│   │   │   └── ApplicationComponent.java
│   │   ├── modules
│   │   │   ├── ApplicationModule.java
│   │   │   ├── JNIModule.java
│   │   │   └── NetworkModule.java
│   │   └── PerActivity.java
│   ├── settings
│   │   ├── CustomSwitchPreference.java
│   │   └── KiwixSettingsActivity.java
│   ├── utils
│   │   ├── BookUtils.java
│   │   ├── Constants.java
│   │   ├── DimenUtils.java
│   │   ├── DocumentParser.java
│   │   ├── files
│   │   │   ├── FileReader.java
│   │   │   ├── FileSearch.java
│   │   │   └── FileUtils.java
│   │   ├── LanguageUtils.java
│   │   ├── NetworkUtils.java
│   │   ├── RateAppCounter.java
│   │   ├── StorageUtils.java
│   │   ├── StyleUtils.java
│   │   └── TestingUtils.java
│   └── views
│       ├── AnimatedProgressBar.java
│       ├── AutoCompleteAdapter.java
│       ├── bottom_tab
│       │   ├── PageBottomTab.java
│       │   ├── PageBottomTabLayout.java
│       │   └── TabDrawerAdapter.java
│       ├── CompatFindActionModeCallback.java
│       ├── KiwixActionBarDrawerToggle.java
│       ├── LanguageSelectDialog.java
│       ├── SliderPreference.java
│       ├── table
│       │   └── TableDrawerAdapter.java
│       └── web
│           ├── KiwixWebView.java
│           ├── ToolbarScrollingKiwixWebView.java
│           ├── ToolbarStaticKiwixWebView.java
│           └── WebViewCallback.java
├── KiwixApplication.java
├── KiwixMobileActivity.java
└── modules
    ├── bookmarks_view
    │   ├── BookmarksActivity.java
    │   ├── BookmarksPresenter.java
    │   └── contract
    │       └── BookmarksViewCallback.java
    ├── clients
    │   ├── KiwixWebChromeClient.java
    │   └── KiwixWebViewClient.java
    ├── downloader
    │   ├── Chunk.java
    │   ├── ChunkUtils.java
    │   ├── DownloadFragment.java
    │   ├── DownloadIntent.java
    │   └── DownloadService.java
    ├── library
    │   ├── entity
    │   │   ├── LibraryNetworkEntity.java
    │   │   └── MetaLinkNetworkEntity.java
    │   └── LibraryAdapter.java
    ├── main
    │   └── SplashActivity.java
    ├── search
    │   ├── contract
    │   │   └── SearchViewCallback.java
    │   ├── KiwixSearchWidget.java
    │   ├── SearchActivity.java
    │   └── SearchPresenter.java
    ├── text_to_speech
    │   └── KiwixTextToSpeech.java
    └── zim_manager
        ├── contract
        │   └── ZimManageViewCallback.java
        ├── fileselect_view
        │   ├── contract
        │   │   └── ZimFileSelectViewCallback.java
        │   ├── ZimFileSelectFragment.java
        │   └── ZimFileSelectPresenter.java
        ├── library_view
        │   ├── contract
        │   │   └── LibraryViewCallback.java
        │   ├── LibraryFragment.java
        │   ├── LibraryPresenter.java
        │   └── LibraryUtils.java
        ├── SectionsPagerAdapter.java
        ├── ZimManageActivity.java
        └── ZimManagePresenter.java
```

Nothing has changed semantically.

Screenshots/GIF for the change: NA

I would request everyone to download it locally and test it as much as they can since it is a large refactor involving number changes.

### CODE REVIEW

**Comment by srv-twry** [comment]
I wanted to move the ```KiwixMobileActivity``` inside the package ```main``` but i was advised not to touch it so i have left it unmoved.

**Comment by mhutti1** [comment]
The structure looks good. How long did this take (were there any major conflicts?) I would rather not merge this just now so we can get our pr number down so we don't end up with conflicts later. If this was just dragging and dropping then we can simply implement in the near future.

**Comment by srv-twry** [comment]
Yeah, it is simple drag and drop for the most part. We can manage it later.

**Comment by brijeshshah13** [comment]
@srv-twry The overall structure looks better, yet, I will test it rigorously and let you know.

**Comment by kelson42** [comment]
What is the status of this PR?

**Comment by mhutti1** [comment]
@kelson42 on hold until we have less open prs with merge conflicts as it would mean each would need editing.

**Comment by srv-twry** [comment]
Closing for now. Will reopen when it is feasible to implement this.

**Pull request closed without merging**
