### PR TITLE
Pass test for Android 21 in IntroFragment

### LINKED ISSUE #2741: Update IntroFragment test
```
org.kiwix.kiwixmobile.intro.IntroFragmentTest > viewIsSwipeableAndNavigatesToMain[test(AVD) - 5.0.2] FAILED 
	java.lang.RuntimeException: No view found with Id org.kiwix.kiwixmobile:id/get_started
	at org.kiwix.kiwixmobile.BaseRobot.isVisible(BaseRobot.kt:56)
```
This test fails sometimes with no valid reason. It's wasting resources and time. We can find the root cause of why it fails sometimes and then we can fix it.

### PR DESCRIPTION
**Pull request by gouri-panda**
Fixes #2741 
Sometimes For some reason, our test robot couldn't find the views we want to see.

### CODE REVIEW

**Comment by kelson42** [comment]
@gouri-panda What is the status here? You have asked review, but the PR is in draft! I have requested @MohitMaliFtechiz To have a look to these recurrent CI problems. You should talk together soon IMO to better collaborate.

**Review by MohitMaliFtechiz — DISMISSED** [review]
looks good to me changing method for getting id.

**Comment by gouri-panda** [comment]
@MohitMaliFtechiz It's ready now.

**Comment by gouri-panda** [comment]
@MohitMaliFtechiz Is there something you want to add here? The PR is ready to merger now.

**Review by MohitMaliFtechiz — APPROVED** [review]

**Pull request merged**
