### PR TITLE
Fixes Access A Deleted File After Closing All Tabs

### LINKED ISSUE #1034: Access A Deleted File After Closing All Tabs
**Describe the bug**
After you've deleted a ZIM file, you can re-access it by going to the tab overview, closing all tabs, and then clicking on the  button

**Expected behavior**
* It should not be possible to close all tabs as @mhutti1 suggested this earlier.
* When user tries to close the last opened tab, a new tab such as default tab that opens now after 1500ms should open immediately. So, that the user is not able to open the previous file using the  button.

**Steps to reproduce the behavior:**
1. Delete a ZIM File
2. Go to tab overview,
3. Close all tabs.
4. Click on  button
5. You will be able to access the deleted file.

**Screenshots**

**Environment**
Galaxy Nexus API 24

### PR DESCRIPTION
**Pull request by iadeelzafar**
Fixes #1034

### Changes: 
* Add a method to check if there are zero tabs.
* Call the method where required.
* Time of 1500ms removed.
* Now, when the user closes the last opened tab or tries to close all tabs at once using the CloseAllTab Floating Action Button, the default tab("HOME PAGE") opens immediately.

### CODE REVIEW

**Comment by iadeelzafar** [comment]
@soloturn @mhutti1 Have a look at this.

**Comment by sonusourav** [comment]
@iadeelzafar In my device, openDefaultTab works fine in for closeAllTabs() but I am getting weird issue for closeTab(int index). When I try to close the last open file by swiping down/up, a new default file opens but is not visible. If you tap on it ( invisible file), it works normally, just is not visible.

Device: Redmi 4
OS: Android Nougat 7.1

close_all_tab_issue

Notice the invisible file in the middle

invisible_file


If any of your friend has this device, could you please check?

**Comment by iadeelzafar** [comment]
@sonusourav I just checked it on Nougat API and it works fine. The issue you're facing seems to be device specific.

**Comment by iadeelzafar** [comment]
@sonusourav Thanks for writing. Check it now. I hope that issue is resolved now.

**Comment by soloturn** [comment]
@prajurock this builds on your commit, what you think?

**Comment by prajurock** [comment]
Yeah @soloturn @iadeelzafar reduces the time and its very small.

**Comment by iadeelzafar** [comment]
@prajurock Thanks for reviewing.

**Pull request merged**
