### PR TITLE
Reintroduced wifi hotspot feature in custom apps.

### LINKED ISSUE #1602: Reintroduce Hotspot feature in custom apps
It has been removed because of #1600

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #1602 

* Moved Wi-Fi hotspot-related files to the core module to use hotspot functionality in both the app and custom module.
* Moved permission in the core manifest to access them in both modules.
* Removed some unnecessary files which are now no longer in use.
* We moved our server functionality to the core module to enable its use in both our app and custom modules. However, this change posed a challenge. We had a functionality that, when the user clicks on a notification, it takes them to the hosted book screen. By moving this functionality to the core module, we lost direct access to the navigation graph and `KiwixMainActivity` or `CustomMainActivity`.
* To address this issue, we introduced some abstract variables, such as navGraphId and mainActivity, which we set from both `KiwixMainActivity` and `CustomMainActivity`. This allows us to retrieve the navigation graph ID and the main activity.
* Additionally, we implemented a new function in `CoreApp` to set the currently running `CoreMainActivity`, which we use to obtain the navigation graph ID and main activity to perform the user clicks on the notification.
* Improved code to show zim file information on the `ZimHostFragment` for the custom module as we are not adding additional information on the zim file while downloading the zim file in the custom module https://github.com/kiwix/kiwix-android/blob/27215b0541e07db5ebb77cbf13ca8a1462977a2c/custom/src/main/java/org/kiwix/kiwixmobile/custom/download/effects/DownloadCustom.kt#L30.
* Improved our code to address the issue, if we run 2 servers at once (if in `app` server is already running then we can not run the server on the `custom` module since we can not run 2 servers on the same IP.) So for this, we have improved our code to show the proper error message so the user will know why the server is not running.

https://github.com/kiwix/kiwix-android/assets/34593983/ffeeacb5-ba1b-4eab-9d3e-2a2deab71907

### CODE REVIEW

**Comment by kelson42** [comment]
@gouri-panda any feedback on this PR?

**Review by gouri-panda — COMMENTED** [review]
@MohitMaliDeveloper Code looks good. I tested with main and custom app. Looks good on the other device, but the same error is happening here also that we talked about in the #3218 . Also, one thing if we want to run 2 servers at once which is one for the main app and the other for is custom app then it won't work. We should add a message to show what's happening there.

**Comment by MohitMaliFtechiz** [comment]
> I tested with main and custom app. Looks good on the other device

@gouri-panda  Other devices mean the server is working fine with other devices. So it might be your device-specific problem, since you are able to reproduce the error can you please debug it and place a fix for it?

**Comment by MohitMaliFtechiz** [comment]
> Also, one thing if we want to run 2 servers at once which is one for the main app and the other for is custom app then it won't work. We should add a message to show what's happening there.

@gouri-panda I have improved the code to show the proper error message to the user, also updated the PR description with video.

**Comment by kelson42** [comment]
@gouri-panda Is this finally ready to merge?

**Comment by kelson42** [comment]
@MohitMaliFtechiz CI fails :(

**Comment by MohitMaliFtechiz** [comment]
@kelson42 It looks like emualtor was frozen, rerun makes it pass.

**Review by gouri-panda — APPROVED** [review]
@MohitMaliDeveloper @kelson42 LGTM 🎉  @MohitMaliFtechiz Thanks!!

**Pull request merged**
