### PR TITLE
Fixed: Mul file not recognized as such and listing pretty much all languages.

### LINKED ISSUE #3892: Mul file not recognized as such and listing pretty much all languages
Steps to reproduce:

- Download https://dev.library.kiwix.org/#lang=&q=anthropocene
- Open via Kiwix android
- result:
Screenshot_20240624-213904

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #3892 

 Showing zim files in all available languages.

https://github.com/user-attachments/assets/6d787658-1f8d-45c0-a1c8-4ed8484d9ea8

### CODE REVIEW

**Comment by kelson42** [comment]
There should not be a multilanguage category, the ZIM should appear as in English or French etc...

**Comment by MohitMaliFtechiz** [comment]
@kelson42 It is showing under the `mul` language on `library.kiwix.org`.

Screenshot from 2024-07-01 12-07-06

and also the book has multiple language tags. 

Screenshot_20240624-213904

Also, I have the [ted_mul_crowdsourcing_2024-03.zim](https://download.kiwix.org/zim/ted/ted_mul_crowdsourcing_2024-03.zim) which was showing under the "Multiple languages" since it has the `mul` language code.


https://github.com/kiwix/kiwix-android/assets/34593983/9bbf98d0-b63f-43ca-a81a-f7396adf214b

So due to these things, I thought it should show under the "Multiple languages".


> the ZIM should appear as in English or French etc...

We have a language code like this in this book (eng,fra,vie,ita,ara,por), we can list this type of book under the first language code that comes in the language tag. So it is better to list this type of book in the English language(Since the default articles are also shown in the English language in this zim file).



>  An visually we should have a way to list, in the book des ription that this is a multilanguage book.

@kelson42 I was thinking about this, and IMO we should show that this is a multiple-language book in tags instead of the book description. Since we are showing that this book has (picture, video, short text, etc) it shows the main information about the book, and if we show "Multiple languages" as a tag it will highlight to the user, and the user can easily know that this book is a multi-language book. 

>There should not be a multilanguage category,

Also, we can do the same with the `mul` language code books as they are currently showing under the "Multiple languages" category as shown in the above video. We can do the same for those zim files so that no "Multiple languages" category will be displayed on the library screen. @kelson42 What do you think?

**Comment by kelson42** [comment]
> @kelson42 It is showing under the `mul` language on `library.kiwix.org`.

Sorry for misguiding you actually. This is a bug there, see https://github.com/kiwix/libkiwix/issues/1098

... but this is an heritage of the past, the ZIM languages are ordered properly in eqch language supported.

**Comment by kelson42** [comment]
> > An visually we should have a way to list, in the book des ription that this is a multilanguage book.
> 
> @kelson42 I was thinking about this, and IMO we should show that this is a multiple-language book in tags instead of the book description. Since we are showing that this book has (picture, video, short text, etc) it shows the main information about the book, and if we show "Multiple languages" as a tag it will highlight to the user, and the user can easily know that this book is a multi-language book.
> 
> > There should not be a multilanguage category,
> 
> Also, we can do the same with the `mul` language code books as they are currently showing under the "Multiple languages" category as shown in the above video. We can do the same for those zim files so that no "Multiple languages" category will be displayed on the library screen. @kelson42 What do you think?

@MohitMaliDeveloper What you say makes sense and I agree with many parts of your proposal. But the solution of this problem will be in many places:
* For the moment, in this issue, just list the book in each of the languages listed. We will give up on the visual as this is a non trivial thing tomdo.
* Then we have actually an other problem which is that here the other languages are subtitles and there is no clear way to understand that (for the user). We will fix that we other metadata, see https://github.com/openzim/overview/issues/38
* Finally, in term of result displaying. In the future we will have to implement a way to provide many groups. for example first the full language match, the books which have only a few content in this language, then maybe book with subtitles in this language, etc... kind of extension of this feature for kiwix-serve https://github.com/kiwix/kiwix-tools/issues/562

So can you please just implement the first part so we can merge?

**Comment by MohitMaliFtechiz** [comment]
> For the moment, in this issue, just list the book in each of the languages listed. We will give up on the visual as this is a non trivial thing tomdo.

@kelson42 I have made the changes according to your request and updated the video on PR description for visual reference.

**Pull request merged**
