### PR TITLE
Updated widgets minimum resize width

### LINKED ISSUE #3166: Android widget resize
Widget cannot be resized (especially horizontally) on One UI 5.
So it cannot easily fit some home screens.

Allow user resizing home screen widget.

Android 13, oneui 5, note 20 ultra

### PR DESCRIPTION
**Pull request by gouri-panda**
Fixes #3166

### CODE REVIEW

**Comment by kelson42** [comment]
@gouri-panda WOW that was really super quick!!! :)

**Comment by kelson42** [comment]
@gouri-panda What is the problem with the CI?

**Comment by gouri-panda** [comment]
@kelson42 It looks like server issue from Fetch API. Some times it happens. I'll try after some time.

**Comment by gouri-panda** [comment]
@MohitMaliDeveloper It's ready now.

**Comment by kelson42** [comment]
Looks like Jitpack is back!

**Review by MohitMaliFtechiz — APPROVED** [review]
approved

**Pull request merged**
