### PR TITLE
Add tabs

### LINKED ISSUE #483: Add chrome like tabs
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
  
#### Feature Description

Currently the application has a side nav to navigate between the tabs.

screenshot_20180221-210520 1

### The idea is to change it to something similar to tabs creation and navigation which Chrome uses:

screenshot_20180221-210608 1

### PR DESCRIPTION
**Pull request by abdulwd**
Fixes #483 

Changes: I have made a separate activity in a new package called `main2`. I still have to integrate the WebView in the tabs. The tabs are presently blank. When everything is complete I will delete the `main` package and will rename `main2` to `main`.

file

### CODE REVIEW

**Comment by abdulwd** [comment]
@mhutti1 I have removed the original activity so tests are bound to fail.

**Comment by abdulwd** [comment]
@mhutti1 A single test is failing on all devices but it is empty. :/
If that is not a problem please merge this. I have just added an activity and moved some items from app bar to overflow menu to make room for the tab switcher icon.

**Comment by mhutti1** [comment]
@abdulwd Can you see which test is failing and give an explaination?

**Comment by abdulwd** [comment]
@mhutti1 The tests residing in `tests/activities` package were failing. They were only failing on running in the test suite but when they were run individually all these tests got passed.
So I added the [Android Test Orchestrator](https://developer.android.com/training/testing/junit-runner#using-android-test-orchestrator) which runs each test in its own instrumentation instance. The tests pass locally on adding it when run in the test suite but on Testdroid they fail.
A separate apk is installed for Android Test Orchestrator during instrumentation test so maybe that is not being installed on Testdroid. I'm not sure. :/

**Comment by abdulwd** [comment]
Moved to #832.

**Pull request closed without merging**
