### PR TITLE
Release/3.4.3

### PR DESCRIPTION
**Pull request by macgills**
Todo:
- update changelog
- merge on green build
- tag master with 3.4.3
- wait for release build to publish archives
- on google play alpha draft remove the universal archive that targets 4 architectures and then release to alpha
- update changelog on github releases draft

### CODE REVIEW

**Comment by kelson42** [comment]
@abdulwd Would you feel confortable to finish this PR? Seems straight forward, even if I don't really understand what is meant with "merge on green build".

**Comment by kelson42** [comment]
I guess "merge on green build", just mean "merge on master"

**Comment by abdulwd** [comment]
@s-ayush2903 Is updating the changelog as he's more up to date on the latest PRs merges.

**Comment by s-ayush2903** [comment]
> "merge on green build"

Build is said to be _green_ when, in our CI checks:
* StaticAnalysis check is green
* CodeFactor is green
* Pull Request build is green
* Either of the two coverage reporting checks is green

**Review by abdulwd — APPROVED** [review]

**Pull request merged**
