### PR TITLE
fix: NullPointerException on Fresh Application launch

### LINKED ISSUE #1037: bug: NPE on first launch of application.
**Describe the bug**

Upon a fresh clone of the repository and build using the Android studio, I got a crash right at the right of the application.

**Expected behavior**

It shouldn't crash.

**Steps to reproduce the behavior:**
1. Delete the application if you already have it along with it's data.
2. Build and run it again. You should get a crash.

**Screenshots**

N/A

**Environment**
- Version of Kiwix Android : Latest Master Branch
- Device : Oppo f1
- OS version : Android 5.1.1

**Logs**

```
03-02 17:15:35.575 12863-12863/org.kiwix.kiwixmobile E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.kiwix.kiwixmobile, PID: 12863
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.kiwix.kiwixmobile/org.kiwix.kiwixmobile.splash.SplashActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.kiwix.kiwixmobile.utils.SharedPreferenceUtil.nightMode()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2505)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2577)
        at android.app.ActivityThread.access$1000(ActivityThread.java:164)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1462)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:159)
        at android.app.ActivityThread.main(ActivityThread.java:5541)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.kiwix.kiwixmobile.utils.SharedPreferenceUtil.nightMode()' on a null object reference
        at org.kiwix.kiwixmobile.base.BaseActivity.getTheme(BaseActivity.java:50)
        at android.content.Context.isOppoStyle(Context.java:3464)
        at com.android.internal.policy.impl.PhoneWindow.<init>(PhoneWindow.java:319)
        at com.android.internal.policy.impl.Policy.makeNewWindow(Policy.java:60)
        at com.android.internal.policy.PolicyManager.makeNewWindow(PolicyManager.java:57)
        at android.app.Activity.attach(Activity.java:6049)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2439)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2577) 
        at android.app.ActivityThread.access$1000(ActivityThread.java:164) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1462) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:159) 
        at android.app.ActivityThread.main(ActivityThread.java:5541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759) 

```

### PR DESCRIPTION
**Pull request by harshika-arya**
Fixes #1037 

Changes: Added a null check

Screenshots/GIF for the change: N/A

### CODE REVIEW

**Comment by harshika-arya** [comment]
@abdulwd @siddharth2010 Please review.

**Comment by soloturn** [comment]
@harshika-arya can you have a look at #1039 also if there is an overlap pls?

**Comment by harshika-arya** [comment]
@soloturn Yes, I have looked at it. Left a review. It's not related to it. It is in `BaseActivity`.

**Comment by soloturn** [comment]
ah, ok, so not related to any design prob. tx @harshika-arya !

**Comment by harshika-arya** [comment]
@soloturn @mhutti1 @abdulwd Can we merge this one now? It's a very small change.

**Pull request merged**
