### PR TITLE
Change CI OS to macos-12, running 30 and 21 on separate runner, remove code coverage

### LINKED ISSUE #2832: Unstable code coverage
**Describe the bug**
We are facing issue where code coverage on android 21 and android 30 sometimes fails . So we need to figure it out how we can stable the envrionment.

**Suggestion would be**
a) Change Os to Ubuntu latest
b) only allow one max-parallel.
c) increase core
d) increase ram.

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #2832

### CODE REVIEW

**Comment by kelson42** [comment]
@MohitMaliFtechiz Can you please secure we do code coverage only once (with most common API version). For the rest obly run the automated tests (but without code coverage). Rename workflows accordingly. This should speedup the CI.

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz Can you please secure we do code coverage only once (with most common API version). For the rest obly run the automated tests (but without code coverage). Rename workflows accordingly. This should speedup the CI.

ok @kelson42

**Comment by kelson42** [comment]
@MohitMaliDeveloper I have rebased and now codecoverage still fail :(

**Comment by MohitMaliFtechiz** [comment]
hi ,
https://github.com/ReactiveCircus/android-emulator-runner/issues/162 , i found this solutions for our problem is to create [waitForView](https://github.com/ashutoshgngwr/noice/blob/03c5ec85968dc768081bba32ae1028a3134f98ab/app/src/androidTest/java/com/github/ashutoshgngwr/noice/EspressoX.kt#L98-L146) and [RetryTestRule](https://github.com/ashutoshgngwr/noice/blob/master/app/src/androidTest/java/com/github/ashutoshgngwr/noice/RetryTestRule.kt) , I am making changes according to it.

**Comment by MohitMaliFtechiz** [comment]
hi @kelson42 ,

I believe test failure issue is now resolved but build only fails sometimes due to timeout issue from Maven Or Jcenter connection but no more with test failure , do you have any suggestion how we can fix this issue ?







[7:18](https://kiwixoffline.slack.com/archives/D0396KN90E9/p1652881716141479)
Maven/Jcenter time out is issue is facing by many customer which is based on network due you have suggestion how we can overcome this ?

**Comment by MohitMaliFtechiz** [comment]
Hi ,
Found same issue on https://github.com/actions/virtual-environments/issues/2715

**Review by kelson42 — DISMISSED** [review]

**Comment by kelson42** [comment]
@MohitMaliFtechiz Approved, can you please rebase (and fix the confict)?

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz Approved, can you please rebase (and fix the confict)?

Ok sure

**Comment by kelson42** [comment]
> I believe test failure issue is now resolved but build only fails sometimes due to timeout issue from Maven Or Jcenter connection but no more with test failure , do you have any suggestion how we can fix this issue ?
> 
> ```
>          > Could not GET 'https://repo.maven.apache.org/maven2/org/jacoco/org.jacoco.report/0.8.7/org.jacoco.report-0.8.7.jar'.
>             > Connection reset
>    > Could not download org.jacoco.core-0.8.7.jar (org.jacoco:org.jacoco.core:0.8.7)
>       > Could not get resource 'https://repo.maven.apache.org/maven2/org/jacoco/org.jacoco.core/0.8.7/org.jacoco.core-0.8.7.jar'.
>          > Could not GET 'https://repo.maven.apache.org/maven2/org/jacoco/org.jacoco.core/0.8.7/org.jacoco.core-0.8.7.jar'.
>             > Connection reset 
> ```
> 
> Maven/Jcenter time out is issue is facing by many customer which is based on network due you have suggestion how we can overcome this ?

No really, lets try to monitor this and if necessary thing about an alternative later if the problem is recurrent.

**Comment by MohitMaliFtechiz** [comment]
hi @kelson42 ,

rebase and changes to coverage done.

**Review by kelson42 — APPROVED** [review]

**Pull request merged**
