### PR TITLE
Bump-up NDK version to 22.0.7026061

### LINKED ISSUE #2578: [REGRESSION] Newly unable to build custom apps (based on master 3.4.3)
I tried today to release a new wikispecies custom app, but the CD failed, see:
https://github.com/kiwix/kiwix-android-custom/runs/1700722782?check_suite_focus=true

I believe what went wrong is:
```
* What went wrong:
60 actionable tasks: 60 executed
Execution failed for task ':custom:stripWikispeciesReleaseDebugSymbols'.
> No version of NDK matched the requested version 21.3.6528147. Versions available locally: 22.0.7026061
```

### PR DESCRIPTION
**Pull request by kelson42**
Might fix #2578

### CODE REVIEW

**Comment by kelson42** [comment]
@abdulwd Would you know what to do to get the "Coverage Reporting" stopping to fail?

**Comment by abdulwd** [comment]
It failed on:
```
Execution failed for task ':app:stripDebugDebugSymbols'.
> No version of NDK matched the requested version 22.0.7026061. Versions available locally: 18.1.5063045, 21.3.6528147, 21.3.6528147, 21.3.6528147
```
I think you have to update the NDK version in some YAMLs

**Comment by abdulwd** [comment]
Here https://github.com/kiwix/kiwix-android/search?q=ndk

**Comment by kelson42** [comment]
@abdulwd OK, it seems we have some kind of discrepency about how the kiwix-android and kiwix-android-custom handle their dependences.

**Comment by kelson42** [comment]
@abdulwd bunch of other errors now :(

**Comment by abdulwd** [comment]
Doesn't seem like there's an easy fix, I need to check. I can give it a try this weekend.

**Comment by s-ayush2903** [comment]
@kelson42 Do you like the green color now :)

**Comment by kelson42** [comment]
@s-ayush2903 what happened?

**Comment by kelson42** [comment]
@abdulwd Good for you now?

**Review by abdulwd — APPROVED** [review]

**Comment by abdulwd** [comment]
@s-ayush2903 great job! What was the issue?

**Comment by kelson42** [comment]
Lokks like it was onky a temporary problem, just restarting the CI has solved the problem.

**Comment by s-ayush2903** [comment]
Yeah, this is due to the flakiness of instrumentation tests on CIs, they run smooth locally but sometimes fail pointlessly in CIs, so retriggering 'em fixes(but not always)

**Pull request merged**
