### PR TITLE
Minor typo in CONTRIBUTIONS.md

### PR DESCRIPTION
**Pull request by MisterAwesome23**
Minor typo in CONTRIBUTIONS.md.
Testing if project forked and integrated with GitHub correctly.

P.s: I am new (very new) here. Want to start contributing. Can someone help?

### CODE REVIEW

**Comment by abdulwd** [comment]
@MisterAwesome23 Welcome to Kiwix! You can choose an issue from our issue tracker here https://github.com/kiwix/kiwix-android/issues and comment on it if anyone is not currently working on it. You should read the contribution guidelines and the coding style we follow and then open a PR which will be reviewed. Use the PR and issue templates while creating one.

**Comment by MisterAwesome23** [comment]
I am not able to start the project on Android Studio. I made a straight import from VCS with link as my forked repo.
It misses gradle. Can someone help me up with the inital setup?

**Comment by abdulwd** [comment]
Also if you want test something please use your own fork.

**Comment by abdulwd** [comment]
Can you share the error or any screenshot?

**Comment by MisterAwesome23** [comment]
> Also if you want test something please use your own fork.

Yes. Was this change not pushed from my fork?

**Comment by abdulwd** [comment]
This was from your fork but open a PR once your branch is ready to be merged not for testing.

**Comment by MisterAwesome23** [comment]
> This was from your fork but open a PR once your branch is ready to be merged not for testing.

Oh right. Got your point.

**Comment by iadeelzafar** [comment]
@MisterAwesome23 I was facing the same issue and @abdulwd helped me out with this solution. Give it a try.
* Create a `local.properties` file in the project directory and add the location of the SDK according to this [answer](https://stackoverflow.com/a/48155800/7792129).
* Delete the `.idea` folder in the project directory. It is a hidden folder so you may have to change the settings of your file explorer to view it.
* Import the project using **Open an existing Android Studio project** and a dialog will pop up select these
* settings:
  image

**Comment by MisterAwesome23** [comment]
screenshot from 2019-02-16 02-36-21
screenshot from 2019-02-16 02-38-11

Is this correct. It still shows an error to target SDK.
Moreover I am having some KVM issue.
screenshot from 2019-02-16 02-40-17

I tried qemu but it didn't help. I guess because of VirtualBox and Ubuntu 18.04, not sure though. Will you suggest migrating to default windows platform I mean what do you prefer?

**Comment by abdulwd** [comment]
@MisterAwesome23 You should follow @iadeelzafar 's suggestions it will resolve your issue. Using VirtualBox will degrade the performance of Android Studio. IMO you should dual boot your system if you prefer to work on Ubuntu.

**Comment by iadeelzafar** [comment]
@MisterAwesome23 Add this in the local.properties file you are creating and if there's already a local.properties file replace all its existing content with this.
```
sdk.dir = /home/USERNAME/Android/Sdk
```
After this follow the next steps given above.

**Comment by MisterAwesome23** [comment]
> 
> 
> @MisterAwesome23 Add this in the local.properties file you are creating and if there's already a local.properties file replace all its existing content with this.
> 
> ```
> sdk.dir = /home/USERNAME/Android/Sdk
> ```
> 
> After this follow the next steps given above.

Oops. I missed sdk.dir = 
My bad sorry. By the way due to AVD problems I've switched to my main OS windows. I have added the local.properties file and followed rest of the steps. I get this error:
gradlepluginerror

**Comment by iadeelzafar** [comment]
Check each step carefully again, you must've missed something. It will work as soon as you implement all the steps.

**Comment by MisterAwesome23** [comment]
> 
> 
> Check each step carefully again, you must've missed something. It will work as soon as you implement all the steps.

Double checked. Followed them. Gives the same build error :(

**Comment by iadeelzafar** [comment]
you've switched to Windows so have you entered the sdk path that is for Windows OS? It's not the same as Ubuntu's.

**Comment by MisterAwesome23** [comment]
> 
> 
> you've switched to Windows so have you entered the sdk path that is for Windows OS? It's not the same as Ubuntu's.

Yeah I took care of that.
I deleted that repo and re downloaded it starting from scratch.
And it worked. It still has some warnings but we're proceeding.
Thank you so much for your patience and quick responses. Looking forward to regular contributions. 
warnings

**Comment by soloturn** [comment]
@MisterAwesome23 what was your main operating system? /dev/kvm was rw-rw-rw ?

**Comment by MisterAwesome23** [comment]
@soloturn my main is OS is a Windows system. But for project purposes I preffered Ubuntu running which via a virtual box image. And I don't have a /dev/kvm directory :-/

**Comment by abdulwd** [comment]
What is your installation directory of the Android SDK?

**Comment by MisterAwesome23** [comment]
> 
> 
> What is your installation directory of the Android SDK?
It was home/osboxes/Android/Sdk

Anyways I have now setup on windows and seems to be correctly setup. 
Here is a screenshot:
apprunning

Is this alright?

**Comment by iadeelzafar** [comment]
@MisterAwesome23 Now go to Build Variants and select kiwixDebug.

**Comment by MisterAwesome23** [comment]
> 
> 
> @MisterAwesome23 Now go to Build Variants and select kiwixDebug.

Done.
kiwixdebug
Correct?

Is there anything else I have to setup? I did try to explore the app via apk and codebase but to be very honest I am pretty new to such a huge bases and open sourcing overall and it all seems over whelming at once. But I surely want to put in regular efforts and make the best possible contributions. Any voluntary help to kick start, resources or absolutely anything is most welcomed.

**Comment by abdulwd** [comment]
You have selected the correct build variant you can try installing the app on your device using Android Studio

**Pull request merged**
