### PR TITLE
Refactor: Extract dimensions of resources

### LINKED ISSUE #413: Hard-coded values in layouts
**Actual Behavior**

Layout files have hard-coded values which is not feasible.

**Expected Behavior**

All dimensions of resources must be extracted and referenced accordingly.

**Would you like to work on this?**
Yes.

@mhutti1 Please review.

### PR DESCRIPTION
**Pull request by brijeshshah13**
Fixes #413 

Changes: Performed changes as discussed [here](https://github.com/kiwix/kiwix-android/pull/415#discussion_r168930162).

Screenshots/GIF for the change: N/A

### CODE REVIEW

**Comment by mhutti1** [comment]
@brijeshshah13 Could you resolve the conflict?

**Comment by brijeshshah13** [comment]
@mhutti1 The conflicts have been dealt with. However, the travis build is failing again as per the discussion at #518. You can check the log to verify the same. However, the PR is good to be merged.

**Comment by mhutti1** [comment]
@brijeshshah13 sorry more conflicts :( And #518 has no bearing on test failing as I explained in another issue just now. Simply restart the travis build to fix in 95% of cases.

**Comment by brijeshshah13** [comment]
@mhutti1 Gotcha. And the conflicts have been resolved.

**Pull request merged**
