### PR TITLE
Fixed Sometimes CI failed due to Broken pipe (32) error in android 33 

### LINKED ISSUE #3202: Sometimes CI failed due to ```Broken pipe (32)``` error in android 33
**Describe the bug**
Sometimes CI failed due to failed to install APK in android 33. This error happens when emulator freezes.

**Logs**
```
Failed to install APK(s): /Users/runner/.gradle/caches/modules-2/files-2.1/androidx.test/orchestrator/1.4.1/2600207000b9c30b9812c6e7b20131443e03f72c/orchestrator-1.4.1.apk
Unknown failure: cmd: Failure calling service package: Broken pipe (32)
```

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #3202 

I have added retry count in bash script if emulator freeze then it will kill the adb and start again.

### CODE REVIEW

**Comment by kelson42** [comment]
@MohitMaliDeveloper good to review?

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliDeveloper good to review?

Not Yet

**Comment by kelson42** [comment]
@gouri-panda @MohitMaliDeveloper Lets finish this before reviewing #3201

**Comment by MohitMaliFtechiz** [comment]
hi @gouri-panda 
This PR is ready for review.

**Review by gouri-panda — APPROVED** [review]

**Pull request merged**
