### PR TITLE
Feat: Add Leakcanary to the project

### LINKED ISSUE #364: Use leak canary to control/avoid memory leaks
**Proposal**

Currently we aren't using any library to avoid memory leaks. [Leak canary](https://github.com/square/leakcanary) is a lightweight library by Square which can be used to control and avoid memory leaks in the application.
It is a very famous library and used in various open source projects. I think it should be used in this project also.

@mhutti1 @kelson42 Please review and suggest if i should add it or not ?

### PR DESCRIPTION
**Pull request by srv-twry**
Fixes #364 

Changes: Configure Leak-canary for the project.
One thing to note is that we need to add dependencies to the release and test builds also. 
[Here](https://github.com/square/leakcanary/issues/139) is a github issue for this discussion. It's not a problem though since the apk size won't get affected that much.

Screenshots/GIF for the change: NA

### CODE REVIEW

**Comment by aryanshar** [comment]
@srv-twry  @rashiq  The project is not building up after this commit. `error: package com.squareup.leakcanary does not exist`

**Comment by aryanshar** [comment]
@srv-twry @rashiq  The project is not building up after this commit. 'error: package com.squareup.leakcanary does not exist'

**Comment by brijeshshah13** [comment]
@aryanshar Please make sure that the build variant is `kiwixDebug`

**Comment by aryanshar** [comment]
@brijeshshah13 Issue resolved. Thanks !

**Pull request merged**
