### PR TITLE
Feature/gouri-panda/2363_fix_file_transfer

### LINKED ISSUE #2363: File transfer does not work
**Describe the bug**
When initiating transfer of files the transfer finishes abruptly from the sender device, subsequent attempts to transfer lead to a crash
```
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter clientAddress
        at org.kiwix.kiwixmobile.localFileTransfer.WifiDirectManager.setClientAddress(Unknown Source:6)
        at org.kiwix.kiwixmobile.localFileTransfer.PeerGroupHandshakeAsyncTask.onPostExecute(PeerGroupHandshakeAsyncTask.java:164)
        at org.kiwix.kiwixmobile.localFileTransfer.PeerGroupHandshakeAsyncTask.onPostExecute(PeerGroupHandshakeAsyncTask.java:48)
        at android.os.AsyncTask.finish(AsyncTask.java:695)
        at android.os.AsyncTask.-wrap1(Unknown Source:0)
```

**Expected behavior**
No crash and the ability to share files over wifi

**Steps to reproduce the behavior:**
1. launch receiver activity on receiver device
2. Long click on a book from the sender device
3. click the share icon 
4. click send to nearby device
5. on both devices click the search icon until both devices are visible to each other
6. Click on the name of the receiver device from the sender
7. observe failure to send device

**Screenshots**

**Environment**
- Version of Kiwix Android : develop
- Device : Nexus5x & Samsung Galaxy s7
- OS version : 8.1 & 7.0

### PR DESCRIPTION
**Pull request by gouri-panda**
Fixes #2363

### CODE REVIEW

**Comment by gouri-panda** [comment]
@macgills In the `PeerGroupHandshakeAsyncTask` the `InetAddress` should not null but it returns null if the socet refuses to connect. I thought if we check the null check then the we can prevent the crash and also we can inform users that they can try again. If there is another better way to fix this then feel free to suggests me.Thanks!

**Comment by macgills** [comment]
@gouri-panda 
image
Does this fix satisfy the expected behaviour? ie Have you been able to send files from 1 phone to another?

**Comment by gouri-panda** [comment]
@macgills It's still not the appropriate solution for this ticket. If you have any other ideas then please let me know.

**Comment by macgills** [comment]
Don't worry about reconnection right now, figure out why it is failing on the first transfer, use a debugger,
https://developer.android.com/training/connect-devices-wirelessly/wifi-direct read through these articles.

image

this file is 1 of the most recent changes I can think of to file transfer, try checking out the code before/after this and see if it is broken/fixed

**Comment by macgills** [comment]
When I tried to transfer I got a timeout, the sender exited and the receiver did nothing. Subsequent attempt did nothing

**Comment by macgills** [comment]
Checked out a much earlier version to compare against. On that version there was an indeterminate progress spinner for a file in transfer. I think if we fix that displaying we have achieved parity with the most this feature has ever functioned.

**Comment by gouri-panda** [comment]
> Checked out a much earlier version to compare against. On that version there was an indeterminate progress spinner for a file in transfer. I think if we fix that displaying we have achieved parity with the most this feature has ever functioned.

Ok, on it.What about crash on your side?

**Comment by macgills** [comment]
There are no crashes. It doesn't function great but it looks like it never did, that is what I am getting at with "achieved parity". Always possible this is the samsung devices I am using, Samsung are notorious for fucking up every API they can get their hands on

**Comment by gouri-panda** [comment]
@macgills ping for review.

**Review by macgills — APPROVED** [review]

**Pull request merged**
