### PR TITLE
Introducing deprecated code check in CI

### LINKED ISSUE #3409: Create CI check to identify usage of deprecated classes or methods
**Issue Description:**

**Background:**
As our codebase evolves, it is important to ensure that we maintain code quality and prevent the usage of deprecated classes or methods. Deprecated code can lead to compatibility issues, reduced performance, and potential bugs. To address this concern, we need to implement a Continuous Integration (CI) check that identifies any usage of deprecated classes or methods in our codebase.

**Expected Behavior:**
When changes are made to the codebase, the CI system should analyze the modified code and flag any usage of deprecated classes or methods. This will help developers identify and update deprecated code, ensuring that our codebase stays up-to-date and avoids potential issues.

**Steps to Reproduce:**

1. Implement a CI check script or plugin that analyzes the codebase for deprecated code usage.
2. Configure the CI system to execute the script or plugin whenever a code change is pushed to the repository.
3. Ensure that the script or plugin scans all relevant code files (e.g., Kotlin, java) for deprecated code patterns.
4. When deprecated code is detected, the CI system should generate a report or provide a clear indication of the affected files, classes, and methods.

**Acceptance Criteria:**

* The CI check script or plugin is implemented and integrated into the CI system.
* The CI system analyzes the codebase for deprecated code whenever changes are pushed.
* The script or plugin scans all relevant code files for deprecated code patterns.
* The CI system provides a clear report indicating the affected files, classes, and methods using deprecated code.
* Developers are able to quickly identify and address any usage of deprecated code based on the CI check results.

**Additional Considerations:**

* It may be helpful to provide guidelines or documentation on how to update deprecated code to non-deprecated alternatives.
* The CI check should be efficient and not significantly impact the build or test execution time.

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #3409 

Since our project is a multi-module and previously we are using the wrong command of detekt, now we are using the updated command of detekt `./gradlew detektDebug detektCustomExampleDebug` to check all issues in both modules.

* We have introduced that if any deprecated code is found in the project then `detekt` will fail.
* It also fails when we are committing in our local machine since we have updated the `pre-commit.sh` file.
* We already have a `Compat21` file to handle the deprecated code, which does not have any alternative. we will manage that code in this file.
* We have suppressed the `KiwixService` file as we are using `SimpleXmlConverterFactory` and we do not have any alternative for this.
* We have improved some deprecated rules of detekt.

### CODE REVIEW

**Comment by kelson42** [comment]
@MohitMaliFtechiz I really wonder why the CI is green considering this branch is based on a version of gitvmain witj deprexated code!?

**Comment by MohitMaliFtechiz** [comment]
@kelson42, We have configured the CI failure if deprecated code is found in the assemble CI and that is failing right now since we have some deprecated code in our project. https://github.com/kiwix/kiwix-android/actions/runs/5411219667/jobs/9833687025?pr=3440

**Comment by kelson42** [comment]
@MohitMaliFtechiz I want the code to fail for any deprecation scenario you have fixed in the last 3 weeks.

**Review by gouri-panda — CHANGES_REQUESTED** [review]
@MohitMaliFtechiz After the discussion. We should go with Detekt custom rules for detecting the deprecated code. The current approach isn't viable for this issue.

**Review by gouri-panda — APPROVED** [review]

**Comment by gouri-panda** [comment]
@MohitMaliFtechiz We should fix the detekt problem before we merge that. Otherwise, code looks good.

**Comment by kelson42** [comment]
I guess we need to merge #3447 first?!

**Comment by gouri-panda** [comment]
@kelson42 Yes, hopefully, #3447 will solve the problem.

**Pull request merged**
