### PR TITLE
Test failing on android 13

### LINKED ISSUE #3085: Some test failing on android 13
**Describe the bug**
We have found that right now only ```google_api``` are available for target 33 which is causing failure of test cases , if we select target as ```google_apis``` on even target 30 test are failing and works fine with default api this indicate that we have wait till default api is available are target 33. So i have by pass some test on https://github.com/kiwix/kiwix-android/pull/2944. 

we will keep this open when default api is available we can test and move forward.

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #3085

### CODE REVIEW

**Comment by kelson42** [comment]
@MohitMaliFtechiz Any reason why this PR is in draft since two weeks?

**Comment by MohitMaliFtechiz** [comment]
hi @kelson42 ,
I have tried all the thing for running test on android 13 [All information here](https://github.com/kiwix/kiwix-android/issues/3189) .
But nothing works with ```google_apis```. Yesterday we merge https://github.com/kiwix/kiwix-android/issues/3202 after that i have take a try with latest code but nothing works. that's why this PR is in draft.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Worth to keep PR open then?

**Comment by MohitMaliFtechiz** [comment]
hi @kelson42 ,
in this PR we have removed deprecated ```ActivityTestRule``` from all test cases and upgraded test dependencies to latest stable version. I think we should take changes (latest dependencies and remove deprecated ```ActivityTestRule```)  from this PR for better test performance. After that we can close this PR. @gouri-panda what do you think?

**Comment by kelson42** [comment]
@MohitMaliDeveloper Yet, please put that in a dedicated, well documented (there is a ticket for that? Because hard to link to the current ticket I guess).... and close this one.

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliDeveloper Yet, please put that in a dedicated, well documented (there is a ticket for that? Because hard to link to the current ticket I guess).... and close this one.

hi @kelson42 ,
I have created a separate ticket for this https://github.com/kiwix/kiwix-android/issues/3204. I'm closing this one.

**Comment by kelson42** [comment]
@MohitMaliDeveloper You have forgozten to update the PR as well

**Comment by MohitMaliFtechiz** [comment]
hi @kelson42 ,

The summary of the steps which is executed to solve this problem is already mentioned on ticket https://github.com/kiwix/kiwix-android/issues/3189 and related to ActivityTestRule already created another PR https://github.com/kiwix/kiwix-android/issues/3204.

**Pull request closed without merging**
