### PR TITLE
Remove (CI detected) memory leaks

### LINKED ISSUE #3156: Memory Leak on ```IntroFragment``` and ```Hotspot Service```
## Intro Fragment
**Describe the bug**
1. Install fresh app.
2. Let the application open.

**Environment**
* Version of Kiwix Android : 3.6.0
* Device : Redemi Note 9
* OS version : 11

<details><summary> Logs  </summary>

```
D/LeakCanary: ====================================
D/LeakCanary: HEAP ANALYSIS RESULT
D/LeakCanary: ====================================
D/LeakCanary: 2 APPLICATION LEAKS
D/LeakCanary: 
D/LeakCanary: References underlined with "~~~" are likely causes.
D/LeakCanary: Learn more at https://squ.re/leaks.
D/LeakCanary: 
D/LeakCanary: 29833 bytes retained by leaking objects
D/LeakCanary: Signature: 079c5863800715f6811245d7924de6c9261f2e0b
D/LeakCanary: ┬───
D/LeakCanary: │ GC Root: Input or output parameters in native code
D/LeakCanary: │
D/LeakCanary: ├─ dalvik.system.PathClassLoader instance
D/LeakCanary: │    Leaking: NO (InternalLeakCanary↓ is not leaking and A ClassLoader is never leaking)
D/LeakCanary: │    ↓ ClassLoader.runtimeInternalObjects
D/LeakCanary: ├─ java.lang.Object[] array
D/LeakCanary: │    Leaking: NO (InternalLeakCanary↓ is not leaking)
D/LeakCanary: │    ↓ Object[527]
D/LeakCanary: ├─ leakcanary.internal.InternalLeakCanary class
D/LeakCanary: │    Leaking: NO (KiwixMainActivity↓ is not leaking and a class is never leaking)
D/LeakCanary: │    ↓ static InternalLeakCanary.resumedActivity
D/LeakCanary: ├─ org.kiwix.kiwixmobile.main.KiwixMainActivity instance
D/LeakCanary: │    Leaking: NO (Activity#mDestroyed is false)
D/LeakCanary: │    mApplication instance of org.kiwix.kiwixmobile.KiwixApp
D/LeakCanary: │    mBase instance of androidx.appcompat.view.ContextThemeWrapper
D/LeakCanary: │    ↓ AppCompatActivity.mDelegate
D/LeakCanary: │                        ~~~~~~~~~
D/LeakCanary: ├─ androidx.appcompat.app.AppCompatDelegateImpl instance
D/LeakCanary: │    Leaking: UNKNOWN
D/LeakCanary: │    Retaining 757 B in 7 objects
D/LeakCanary: │    mAppCompatCallback instance of org.kiwix.kiwixmobile.main.KiwixMainActivity with mDestroyed = false
D/LeakCanary: │    mContext instance of org.kiwix.kiwixmobile.main.KiwixMainActivity with mDestroyed = false
D/LeakCanary: │    mHost instance of org.kiwix.kiwixmobile.main.KiwixMainActivity with mDestroyed = false
D/LeakCanary: │    ↓ AppCompatDelegateImpl.mActionBar
D/LeakCanary: │                            ~~~~~~~~~~
D/LeakCanary: ├─ androidx.appcompat.app.ToolbarActionBar instance
D/LeakCanary: │    Leaking: UNKNOWN
D/LeakCanary: │    Retaining 273.2 kB in 5397 objects
D/LeakCanary: │    ↓ ToolbarActionBar.mDecorToolbar
D/LeakCanary: │                       ~~~~~~~~~~~~~
D/LeakCanary: ├─ androidx.appcompat.widget.ToolbarWidgetWrapper instance
D/LeakCanary: │    Leaking: UNKNOWN
D/LeakCanary: │    Retaining 273.1 kB in 5393 objects
D/LeakCanary: │    ↓ ToolbarWidgetWrapper.mToolbar
D/LeakCanary: │                           ~~~~~~~~
D/LeakCanary: ├─ androidx.appcompat.widget.Toolbar instance
D/LeakCanary: │    Leaking: UNKNOWN
D/LeakCanary: │    Retaining 272.6 kB in 5380 objects
D/LeakCanary: │    View not part of a window view hierarchy
D/LeakCanary: │    View.mAttachInfo is null (view detached)
D/LeakCanary: │    View.mID = R.id.toolbar
D/LeakCanary: │    View.mWindowAttachCount = 0
D/LeakCanary: │    mPopupContext instance of android.view.ContextThemeWrapper, wrapping activity org.kiwix.kiwixmobile.main.
D/LeakCanary: │    KiwixMainActivity with mDestroyed = false
D/LeakCanary: │    mContext instance of androidx.appcompat.view.ContextThemeWrapper, wrapping activity org.kiwix.kiwixmobile.main.
D/LeakCanary: │    KiwixMainActivity with mDestroyed = false
D/LeakCanary: │    ↓ View.mListenerInfo
D/LeakCanary: │           ~~~~~~~~~~~~~
D/LeakCanary: ├─ android.view.View$ListenerInfo instance
D/LeakCanary: │    Leaking: UNKNOWN
D/LeakCanary: │    Retaining 258 B in 5 objects
D/LeakCanary: │    ↓ View$ListenerInfo.mOnTouchListener
D/LeakCanary: │                        ~~~~~~~~~~~~~~~~
D/LeakCanary: ├─ org.kiwix.kiwixmobile.core.main.CoreReaderFragment$onViewCreated$2 instance
D/LeakCanary: │    Leaking: UNKNOWN
D/LeakCanary: │    Retaining 166 B in 4 objects
D/LeakCanary: │    Anonymous subclass of org.kiwix.kiwixmobile.core.main.OnSwipeTouchListener
D/LeakCanary: │    ↓ CoreReaderFragment$onViewCreated$2.this$0
D/LeakCanary: │                                         ~~~~~~
D/LeakCanary: ╰→ org.kiwix.kiwixmobile.nav.destination.reader.KiwixReaderFragment instance
D/LeakCanary: ​     Leaking: YES (ObjectWatcher was watching this because org.kiwix.kiwixmobile.nav.destination.reader.
D/LeakCanary: ​     KiwixReaderFragment received Fragment#onDestroy() callback and Fragment#mFragmentManager is null)
D/LeakCanary: ​     Retaining 29.8 kB in 307 objects
D/LeakCanary: ​     key = bb99518e-a4a1-4547-b19e-ff290763c685
D/LeakCanary: ​     watchDurationMillis = 15032
D/LeakCanary: ​     retainedDurationMillis = 10029
D/LeakCanary: 
D/LeakCanary: 2158 bytes retained by leaking objects
D/LeakCanary: Signature: 82c8dabe1ed664a4ce1554d308f56536a632e708
D/LeakCanary: ┬───
D/LeakCanary: │ GC Root: Input or output parameters in native code
D/LeakCanary: │
D/LeakCanary: ├─ dalvik.system.PathClassLoader instance
D/LeakCanary: │    Leaking: NO (InternalLeakCanary↓ is not leaking and A ClassLoader is never leaking)
D/LeakCanary: │    ↓ ClassLoader.runtimeInternalObjects
D/LeakCanary: ├─ java.lang.Object[] array
D/LeakCanary: │    Leaking: NO (InternalLeakCanary↓ is not leaking)
D/LeakCanary: │    ↓ Object[527]
D/LeakCanary: ├─ leakcanary.internal.InternalLeakCanary class
D/LeakCanary: │    Leaking: NO (KiwixMainActivity↓ is not leaking and a class is never leaking)
D/LeakCanary: │    ↓ static InternalLeakCanary.resumedActivity
D/LeakCanary: ├─ org.kiwix.kiwixmobile.main.KiwixMainActivity instance
D/LeakCanary: │    Leaking: NO (Activity#mDestroyed is false)
D/LeakCanary: │    mApplication instance of org.kiwix.kiwixmobile.KiwixApp
D/LeakCanary: │    mBase instance of androidx.appcompat.view.ContextThemeWrapper
D/LeakCanary: │    ↓ AppCompatActivity.mDelegate
D/LeakCanary: │                        ~~~~~~~~~
D/LeakCanary: ├─ androidx.appcompat.app.AppCompatDelegateImpl instance
D/LeakCanary: │    Leaking: UNKNOWN
D/LeakCanary: │    Retaining 757 B in 7 objects
D/LeakCanary: │    mAppCompatCallback instance of org.kiwix.kiwixmobile.main.KiwixMainActivity with mDestroyed = false
D/LeakCanary: │    mContext instance of org.kiwix.kiwixmobile.main.KiwixMainActivity with mDestroyed = false
D/LeakCanary: │    mHost instance of org.kiwix.kiwixmobile.main.KiwixMainActivity with mDestroyed = false
D/LeakCanary: │    ↓ AppCompatDelegateImpl.mActionBar
D/LeakCanary: │                            ~~~~~~~~~~
D/LeakCanary: ├─ androidx.appcompat.app.ToolbarActionBar instance
D/LeakCanary: │    Leaking: UNKNOWN
D/LeakCanary: │    Retaining 273.2 kB in 5397 objects
D/LeakCanary: │    ↓ ToolbarActionBar.mDecorToolbar
D/LeakCanary: │                       ~~~~~~~~~~~~~
D/LeakCanary: ├─ androidx.appcompat.widget.ToolbarWidgetWrapper instance
D/LeakCanary: │    Leaking: UNKNOWN
D/LeakCanary: │    Retaining 273.1 kB in 5393 objects
D/LeakCanary: │    ↓ ToolbarWidgetWrapper.mToolbar
D/LeakCanary: │                           ~~~~~~~~
D/LeakCanary: ├─ androidx.appcompat.widget.Toolbar instance
D/LeakCanary: │    Leaking: UNKNOWN
D/LeakCanary: │    Retaining 272.6 kB in 5380 objects
D/LeakCanary: │    View not part of a window view hierarchy
D/LeakCanary: │    View.mAttachInfo is null (view detached)
D/LeakCanary: │    View.mID = R.id.toolbar
D/LeakCanary: │    View.mWindowAttachCount = 0
D/LeakCanary: │    mPopupContext instance of android.view.ContextThemeWrapper, wrapping activity org.kiwix.kiwixmobile.main.
D/LeakCanary: │    KiwixMainActivity with mDestroyed = false
D/LeakCanary: │    mContext instance of androidx.appcompat.view.ContextThemeWrapper, wrapping activity org.kiwix.kiwixmobile.main.
D/LeakCanary: │    KiwixMainActivity with mDestroyed = false
D/LeakCanary: │    ↓ View.mParent
D/LeakCanary: │           ~~~~~~~
D/LeakCanary: ├─ com.google.android.material.appbar.AppBarLayout instance
D/LeakCanary: │    Leaking: UNKNOWN
D/LeakCanary: │    Retaining 237.2 kB in 4961 objects
D/LeakCanary: │    View not part of a window view hierarchy
D/LeakCanary: │    View.mAttachInfo is null (view detached)
D/LeakCanary: │    View.mID = R.id.fragment_main_app_bar
D/LeakCanary: │    View.mWindowAttachCount = 0
D/LeakCanary: │    mContext instance of org.kiwix.kiwixmobile.main.KiwixMainActivity with mDestroyed = false
D/LeakCanary: │    ↓ View.mParent
D/LeakCanary: │           ~~~~~~~
D/LeakCanary: ├─ org.kiwix.kiwixmobile.core.utils.NestedCoordinatorLayout instance
D/LeakCanary: │    Leaking: UNKNOWN
D/LeakCanary: │    Retaining 217.5 kB in 4474 objects
D/LeakCanary: │    View not part of a window view hierarchy
D/LeakCanary: │    View.mAttachInfo is null (view detached)
D/LeakCanary: │    View.mWindowAttachCount = 0
D/LeakCanary: │    mContext instance of org.kiwix.kiwixmobile.main.KiwixMainActivity with mDestroyed = false
D/LeakCanary: │    ↓ View.mParent
D/LeakCanary: │           ~~~~~~~
D/LeakCanary: ├─ androidx.constraintlayout.widget.ConstraintLayout instance
D/LeakCanary: │    Leaking: UNKNOWN
D/LeakCanary: │    Retaining 52.5 kB in 817 objects
D/LeakCanary: │    View not part of a window view hierarchy
D/LeakCanary: │    View.mAttachInfo is null (view detached)
D/LeakCanary: │    View.mID = R.id.activity_main_root
D/LeakCanary: │    View.mWindowAttachCount = 0
D/LeakCanary: │    mContext instance of org.kiwix.kiwixmobile.main.KiwixMainActivity with mDestroyed = false
D/LeakCanary: │    ↓ View.mParent
D/LeakCanary: │           ~~~~~~~
D/LeakCanary: ├─ androidx.constraintlayout.widget.ConstraintLayout instance
D/LeakCanary: │    Leaking: UNKNOWN
D/LeakCanary: │    Retaining 34.7 kB in 623 objects
D/LeakCanary: │    View not part of a window view hierarchy
D/LeakCanary: │    View.mAttachInfo is null (view detached)
D/LeakCanary: │    View.mWindowAttachCount = 0
D/LeakCanary: │    mContext instance of org.kiwix.kiwixmobile.main.KiwixMainActivity with mDestroyed = false
D/LeakCanary: │    ↓ View.mParent
D/LeakCanary: │           ~~~~~~~
D/LeakCanary: ╰→ androidx.drawerlayout.widget.DrawerLayout instance
D/LeakCanary: ​     Leaking: YES (ObjectWatcher was watching this because org.kiwix.kiwixmobile.nav.destination.reader.
D/LeakCanary: ​     KiwixReaderFragment received Fragment#onDestroyView() callback (references to its views should be cleared to
D/LeakCanary: ​     prevent leaks))
D/LeakCanary: ​     Retaining 2.2 kB in 35 objects
D/LeakCanary: ​     key = 7984664c-c7ea-4344-aeda-5b444c0bf454
D/LeakCanary: ​     watchDurationMillis = 15033
D/LeakCanary: ​     retainedDurationMillis = 10032
D/LeakCanary: ​     View not part of a window view hierarchy
D/LeakCanary: ​     View.mAttachInfo is null (view detached)
D/LeakCanary: ​     View.mID = R.id.navigation_fragment_main_drawer_layout
D/LeakCanary: ​     View.mWindowAttachCount = 0
D/LeakCanary: ​     mContext instance of org.kiwix.kiwixmobile.main.KiwixMainActivity with mDestroyed = false
D/LeakCanary: ====================================
```
</details>

## Hotsport Service

**Describe the bug**
1. Open WIFI Hotspot
2. Let the app goes into background.

**Environment**
- Version of Kiwix Android : 3.6.0
- Device : Redmi Note 9
- OS version : 11

<details><summary> Logs  </summary>

```
┬───
    │ GC Root: Global variable in native code
    │
    ├─ org.kiwix.kiwixmobile.webserver.wifi_hotspot.HotspotService$HotspotBinder instance
    │    Leaking: UNKNOWN
    │    Retaining 2.0 kB in 13 objects
    │    this$0 instance of org.kiwix.kiwixmobile.webserver.wifi_hotspot.HotspotService
    │    ↓ HotspotService$HotspotBinder.this$0
    │                                   ~~~~~~
    ╰→ org.kiwix.kiwixmobile.webserver.wifi_hotspot.HotspotService instance
    ​     Leaking: YES (ObjectWatcher was watching this because org.kiwix.kiwixmobile.webserver.wifi_hotspot.HotspotService
    ​     received Service#onDestroy() callback and Service not held by ActivityThread)
    ​     Retaining 1.4 kB in 12 objects
    ​     key = d36f1e52-bf37-44d0-9a80-614d9cfdae1f
    ​     watchDurationMillis = 29165
    ​     retainedDurationMillis = 24156
    ​     mApplication instance of org.kiwix.kiwixmobile.KiwixApp
    ​     mBase instance of android.app.ContextImpl
    ====================================

```
</details>

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #3156 , #3148 , #3154, #2605

### CODE REVIEW

**Comment by kelson42** [comment]
Should be based on the branch detecting the memory leaks in the CI.

**Comment by gouri-panda** [comment]
@MohitMaliDeveloper I think we should review this after #3155.

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliDeveloper I think we should review this after #3155.

Hi @gouri-panda ,
yes first we should merged #3155. After that we should review and merged #3158, #3149.

**Comment by MohitMaliFtechiz** [comment]
> I have already written it: I wont merge any PR which has a red CI. That means as long as I don't have a branch with both proper detection of memory leaks and all the appropriate fixes. You can make multiple PRs if you want but usually you have difficulties with dealing with multiple interdependent feature branches... so wouldn't recommend it.

I have made all memory leak changes on this PR.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Still based on the wrong branch

**Comment by kelson42** [comment]
… and CI is red

**Comment by gouri-panda** [comment]
>I have made all memory leak changes on this PR.

That's great! But we have to create separate tickets for each memory leaks.

**Comment by kelson42** [comment]
@gouri-panda Not my requirement at least, if each commit is identified to fix a memory leak, this is good enough to me.

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz Still based on the wrong branch
I have rebase on develop

**Comment by gouri-panda** [comment]
@MohitMaliDeveloper Is this PR ready?

**Comment by kelson42** [comment]
@gouri-panda I guess this one is the next in the review pipe. On the principle and if CI is green, then LGTM

**Comment by kelson42** [comment]
> @MohitMaliDeveloper Is this PR ready?

I guess it is, because you are requested as reviewer.

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliDeveloper Is this PR ready?

hi @gouri-panda ,
yes this PR is ready for review.

**Review by gouri-panda — APPROVED** [review]

**Pull request merged**
