### PR TITLE
Improved loading speed

### PR DESCRIPTION
**Pull request by gptshubham595**
Improved Loding of URL much faster and smooth transition while opening url and addition of cache data 
Changes:Added this:
getSettings().setDomStorageEnabled(true); getSettings().setJavaScriptEnabled(true); getSettings().setRenderPriority(WebSettings.RenderPriority.HIGH); getSettings().setCacheMode(WebSettings.LOAD_CACHE_ELSE_NETWORK); getSettings().setAppCacheEnabled(true); getSettings().setLayoutAlgorithm(WebSettings.LayoutAlgorithm.NARROW_COLUMNS); getSettings().setUseWideViewPort(true); getSettings().setSaveFormData(true); getSettings().setSavePassword(true); getSettings().setEnableSmoothTransition(true); getSettings().setRenderPriority(WebSettings.RenderPriority.HIGH);

Earlier:
getSettings().setDomStorageEnabled(true);

### CODE REVIEW

**Comment by gptshubham595** [comment]
Can anyone help why is it saying travis build failed

**Comment by gptshubham595** [comment]
Sorry forgot to import websettings

**Comment by mhutti1** [comment]
Your manifest looks incorrect according to travis.

**Comment by kelson42** [comment]
@gptshubham595 Do you still plan to fix the manifest problem reported by @mhutti1

**Pull request closed without merging**
