### PR TITLE
Lintissue fix for translate wiki

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixing lint issue for translatewiki pull request

### CODE REVIEW

**Comment by MohitMaliFtechiz** [comment]
hi @kelson42 ,

I have fixed the lint issue for translate wiki , please review and merge

**Comment by kelson42** [comment]
@MohitMaliFtechiz You should not merge the develop branch in the feature branch. You should rebase on the develop branch.

**Review by kelson42 — CHANGES_REQUESTED** [review]
In your feature branch, you should have only one commit with your fixes, on the top of git `develop` branch `HEAD`

**Comment by MohitMaliFtechiz** [comment]
https://github.com/kiwix/kiwix-android/pull/2806  please refer from this pull request.

**Comment by kelson42** [comment]
@MohitMaliFtechiz New PR is OK, but you should not have had to create a new one, just doing:
```
git reset --hard origin/develop
git cherry-pick 3251fb2
git push -f
```
... should have done the job.

**Pull request closed without merging**
