### PR TITLE
#1253 read action mode for sharing and deleting zim files on disk

### LINKED ISSUE #1253: Recreate Action Mode Context menu for sharing/deleting
**Is your feature request related to a problem? Please describe.**
I deleted this while merging 2.5 to dev

**Describe the solution you'd like**
Port the functionality from java/listview to kotlin/recyclerview

### PR DESCRIPTION
**Pull request by macgills**
Fixes #1253 

Changes: Create Redux-y-ish architecture to enable clean enabling of action mode. 
There is still a lot to make better here
+ Side effects shouldn't return values
+ state rendering should be a side effect
+ this is only affecting ZimFileSelectFragment 
+ state object should be a sealed class with distinct states
+ no unit tests

But it is about as much as I can do in my time remaining this week to unblock @Aditya-Sood from working on LocalFileTransfer

### CODE REVIEW

**Comment by soloturn** [comment]
@macgills the commit comment does not help to understand the commit, violates the commit style guidelines here:
https://github.com/kiwix/kiwix-android/blob/develop/docs/commitstyle.md 

@kelson42, still in emergency mode?

**Comment by Aditya-Sood** [comment]
@soloturn hi, if you need the context: In the 'Get Content' activity, long-pressing a zim file item in the 'Library' doesn't show the contextual action bar in the kotlin port, but used to previously in the java code of master

That bar showed an option to share zims, crucial for the working of my deliverable (feature/LocalFileTransfer)[https://github.com/kiwix/kiwix-android/tree/feature/LocalFileTransfer]

**Comment by soloturn** [comment]
@macgills you mind ammending your commit comment with adityas message here, and squash your commits?

**Comment by Aditya-Sood** [comment]
@soloturn not sure if my comment sums up everything done in this PR, all I know is that it was one of the things to be addressed

**Comment by kelson42** [comment]
> @kelson42, still in emergency mode?

We are not in emergency mode anymore. But we have here different views about how to do things with git... and we have releases to achieve to do soon. My strategy for now is to stay with what we have (a few changes will be brought to commitstyle.md) and save our energy to a more in-depth discussion on all of this (see https://github.com/kiwix/overview/issues/18) in fall.

**Comment by macgills** [comment]
Given the need to unblock Aditya, the upcoming commitstyle change and Isaac's approval I have merged this ticket

**Comment by Aditya-Sood** [comment]
Thanks! I have created the PR: #1276

**Pull request merged**
