### PR TITLE
Refactored test cases, added system test watcher to prevent ANR

### LINKED ISSUE #2928: Rewrite the test cases that are failing sometimes in our CI
**Context**
Sometimes our CI is failing due to faulty test cases, particularly instrument tests. We should rewrite/fix them. <del>For example, our [IntroRobot](https://github.com/kiwix/kiwix-android/blob/develop/app/src/androidTest/java/org/kiwix/kiwixmobile/intro/IntroRobot.kt) is hugely unreliable to our CI</del>.
**Expected Behaviour**
A green CI :)

### LINKED ISSUE #2956: Android 12 UITests are failing due to lack permission
>android:exported needs to be explicitly specified for element <activity#androidx.test.core.app.InstrumentationActivityInvoker$BootstrapActivity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined.

### PR DESCRIPTION
**Pull request by gouri-panda**
Fixes #2928 
Fixes #2956

### CODE REVIEW

**Comment by MohitMaliFtechiz** [comment]
hi @gouri-panda , is this PR is ready for review ?

**Comment by gouri-panda** [comment]
@MohitMaliFtechiz Yes :)

**Comment by MohitMaliFtechiz** [comment]
hi @gouri-panda , coverage reporting is failing on both can you please take a look at it.

**Comment by gouri-panda** [comment]
@MohitMaliFtechiz After #2933 i hope it will stable.

**Comment by MohitMaliFtechiz** [comment]
Hi @gouri-panda , Test failing reason is you forgot to paas ```drawer id``` and ```gravity``` to ```openDrawer()``` Method. https://github.com/kiwix/kiwix-android/blob/bb661551134b38de3a6ce712a2c6dfe22c42f168/app/src/androidTest/java/org/kiwix/kiwixmobile/main/TopLevelDestinationRobot.kt#L74

As you change parameters here. 
https://github.com/kiwix/kiwix-android/blob/bb661551134b38de3a6ce712a2c6dfe22c42f168/app/src/androidTest/java/org/kiwix/kiwixmobile/utils/StandardActions.java#L46

**Comment by MohitMaliFtechiz** [comment]
hi @gouri-panda ,

There were 19 test which were executed before this implementation now only 14 test are running , some of test like TopLevelDestination and other are not executing can you look at it.

**Comment by gouri-panda** [comment]
@MohitMaliFtechiz  Some network tests are skipping because in our CI no cellular provider there.

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz Some network tests are skipping because in our CI no cellular provider there.

hi @gouri-panda , All test which are extended by ```BaseActivityTest``` is not running so this might not due to network issue. Please check and if you uncomment 

```  
fun setUpBeforeClass() {
    uiDevice = UiDevice.getInstance(getInstrumentation())
    registerANRWatcher()
  } 

```
this function's all test were running , please take a look at it.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Can you please review again this PR?

**Comment by MohitMaliFtechiz** [comment]
hi @gouri-panda please fix the coverage reporting , i think you are still working on this please mark it as draft.

**Comment by gouri-panda** [comment]
I'm closing this issue. It's better to have two PRs.

**Pull request closed without merging**
