### PR TITLE
Few readme things

### PR DESCRIPTION
**Pull request by kelson42**

### CODE REVIEW

**Comment by abdulwd** [comment]
@kelson42 You have some changes from another branch in this PR and can you add a badge for slack in README? It will be welcoming for our new contributors to chat on slack instead of IRC. The badge should redirect to the slack invite page and not to our slack workspace.

**Comment by kelson42** [comment]
@abdulwd I have rebased. OK for Slack but I'm not sure about how the code should looks like as I guess you need to be invited to join our Channel?!

**Comment by macgills** [comment]
@kelson42 you can create a public slack channel

**Comment by kelson42** [comment]
@macgills Slacks proposed me in the options to make the #android channel private... so I guess this is public.
@abdulwd Do you know fomr where should I get the badge? Not clear to me.

**Comment by macgills** [comment]
`[](https://oresoftware.slack.com/messages/CCAD1H94G)`
something like that should do

**Comment by kelson42** [comment]
@macgills People will need to register with your proposal

**Comment by macgills** [comment]
still nice to have the badge there I think

**Pull request merged**
