### PR TITLE
Updated to Android 14 

### LINKED ISSUE #3478: Add support of Android 14
With proper test in CI

### PR DESCRIPTION
**Pull request by gouri-panda**
Fixes #3478 

* `BuildConfig` file is by default off in the latest gradle version, so we have enabled this in our `AllProjectConfigure` class to enable this class for both modules.
```
A problem occurred configuring project ':app'.
> com.android.builder.errors.EvalIssueException: Build Type 'debug' contains custom BuildConfig fields, but the feature is disabled.
  To enable the feature, add the following to your module-level build.gradle:
  `android.buildFeatures.buildConfig true`
```

### CODE REVIEW

**Comment by MohitMaliFtechiz** [comment]
@gouri-panda Now the test cases start running on API level 34, you can now start working on fixing the code error and we should upgrade our gradle as well to support Android 14.


```kotlin
We recommend using a newer Android Gradle plugin to use compileSdk = 34

This Android Gradle plugin (7.4.2) was tested up to compileSdk = 33

This warning can be suppressed by adding
    android.suppressUnsupportedCompileSdk=34
to this project's gradle.properties

The build will continue, but you are strongly encouraged to update your project to
use a newer Android Gradle Plugin that has been tested with compileSdk = 34

```

**Comment by gouri-panda** [comment]
@MohitMaliDeveloper Thanks! Will do that :)

**Comment by MohitMaliFtechiz** [comment]
@kelson42, @gouri-panda I came to an end on this due to the fetch library. 

In Android 14 we have to set the `RECEIVER_EXPORTED` or `RECEIVER_NOT_EXPORTED`  as mentioned in [Offical docs](https://developer.android.com/about/versions/14/behavior-changes-14#runtime-receivers-exported) and in the fetch library we are registering the runtime broadcast receiver. The Fetch library has not been maintained since 2020 so it is not compatible with Android 14. It has 2 classes that use the runtime broadcast receiver one is `DefaultFetchNotificationManager` for this I have made the changes in our code to make it compatible with Android 14 https://github.com/kiwix/kiwix-android/pull/3481/commits/75a2dcdc90eb48ef0c8a93e1d36c39b43fcfdbf7, and the second class is `PriorityListProcessorImpl` due to this class I came to an end because this class registering the broadcast in `init` method(primary constructor) so overriding does not work here as we have did for the first class. https://github.com/tonyofrancis/Fetch/blob/a703d145d779340345d04d6c6de15bff7598ab9e/fetch2/src/main/java/com/tonyodev/fetch2/helper/PriorityListProcessorImpl.kt#L71


Currently fetch library is on the jitpack.

@kelson42, @gouri-panda  For a current solution We can fork the Fetch repo and make the changes in code to make it compatible with Android 14, and publish it on jitpack and use it from there.

Let me know what you think on this?

**Comment by kelson42** [comment]
Sounds it's time to implement #3141

**Pull request closed without merging**
