### PR TITLE
Update Spanish strings.xml

### PR DESCRIPTION
**Pull request by Pablohn26**
Dear @kiwix/lieutenants
I provide updated Spanish translation strings.

### CODE REVIEW

**Comment by kelson42** [comment]
@Pablohn26 Thank you for your pull request, but the translations are handled on this online web service. https://translatewiki.net/wiki/Translating:Kiwix If we integrate them like this, they will be soon overwritten. May you please put your improvments to translatewiki.net?

**Comment by Pablohn26** [comment]
Ok, I have registered on that webpage and seems there is [no need of Spanish translations](https://translatewiki.net/w/i.php?title=Special:Translate&group=kiwix&language=es&filter=%21translated&action=translate). Strings were already translated. 

Could you update [Contributing Guidelines](https://github.com/kiwix/kiwix-android/blob/master/CONTRIBUTING.md) or create a TRANSLATING.md with that information? It would help to future contributors.

**Comment by kelson42** [comment]
@Pablohn26 done.

**Comment by Pablohn26** [comment]
> Could you update [Contributing Guidelines](https://github.com/kiwix/kiwix-android/blob/master/CONTRIBUTING.md) or create a TRANSLATING.md with that information? It would help to future contributors.

Where is it done? I do not see it (at least on master branch)

If you meant with done that **this issue** is done, I am ok with that. But please update the documentation or allow me to do that (I have not done it because [Contributing Guidelines](https://github.com/kiwix/kiwix-android/blob/master/CONTRIBUTING.md) is based on another document.

**Comment by kelson42** [comment]
https://github.com/kiwix/kiwix-android/blob/master/TRANSLATING.md

**Comment by Pablohn26** [comment]
Ok, thanks.

**Pull request closed without merging**
