### PR TITLE
Feature/rajputt2122/#1355 #1150 banner scroll vector images

### LINKED ISSUE #1150: Feature Ehancement: Convert Material Design png icons into vector assets
Should i Work on this
Most image formats (png, jpeg, bmp, gif, webp etc) are raster which means they describe the image as a fixed grid of pixels.
Using Vector assets will have benefits like
Sharp/Vector images Resize gracefully
Small
Dynamic

### LINKED ISSUE #1355: Add main Kiwix banner inside the scrollable region
**Is your feature request related to a problem? Please describe.**
Making the banner scrollable would add extra space for displaying the zim files.

**Describe the solution you'd like**

Just add the main banner inside the scroll view (along with the recycler view).

### PR DESCRIPTION
**Pull request by macgills**
Fixes #1355
Fixes #1150

Changes: https://github.com/kiwix/kiwix-android/pull/1421

### CODE REVIEW

**Comment by macgills** [comment]
Merged as I cannot approve a PR I have opened but I approved the original source pr

**Comment by abdulwd** [comment]
Did you test this on API 15? As far as I can remember converting some start/stop icons to svgs was causing a crash when download notification is shown.

**Comment by macgills** [comment]
I'll give it a spin

**Comment by macgills** [comment]
@abdulwd I can't even launch a 15 emulator, can you test it out?

**Comment by abdulwd** [comment]
Sure. I will test that tomorrow

**Pull request merged**
