### PR TITLE
Update KiwixLib to 10.1.1

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes: #3073 
Parent Issue: #2816

### CODE REVIEW

**Comment by kelson42** [comment]
I'm surprised this does not need additional changes considering that the libkiwix has brought many API changes!!! https://github.com/kiwix/libkiwix/blob/master/ChangeLog

**Comment by gouri-panda** [comment]
>I'm surprised this does not need additional changes considering that the libkiwix has brought many API changes!!! https://github.com/kiwix/libkiwix/blob/master/ChangeLog

Yes, we have to manually check it.

**Comment by kelson42** [comment]
@gouri-panda @MohitMaliFtechiz Would that be a good idea to:
* Activate it per default for non-releases? if "no" why?
* Activaye it and check it in the CI?

**Comment by kelson42** [comment]
> >I'm surprised this does not need additional changes considering that the libkiwix has brought many API changes!!! https://github.com/kiwix/libkiwix/blob/master/ChangeLog
> 
> Yes, we have to manually check it.

But CI is already green!

**Comment by gouri-panda** [comment]
>But CI is already green!

@kelson42 We don't cover all the ground in tests.

**Comment by MohitMaliFtechiz** [comment]
hi @kelson42  and @gouri-panda ,

I have performed manually testing against 10.1.1 , all looks good to me , @gouri-panda  can you also test it so that we can merge it.

**Comment by kelson42** [comment]
It would be interesting as well to check if this automaticaly fix (it shoukd IMO) the following tickets: #2768 #2811 #2772

**Comment by gouri-panda** [comment]
@kelson42 @MohitMaliDeveloper Looks good to me. But I don't know recent changes that affect `kiwix-android`. It would be better if we test those areas.

**Review by gouri-panda — APPROVED** [review]

**Pull request merged**
