### PR TITLE
Refactored CI

### LINKED ISSUE #2929: Improvement CI/CD
**Is your feature request related to a problem? Please describe.**
We are using very outdated code for our CI. Update with the new features and refactor the old code.

**Result**
A better and faster CI/CD is very important for the development project. This enables us faster and easy development process.

### PR DESCRIPTION
**Pull request by gouri-panda**
Fixes #2929

### CODE REVIEW

**Comment by gouri-panda** [comment]
It should merge after #2928

**Comment by gouri-panda** [comment]
@MohitMaliFtechiz It's ready now :)

**Comment by MohitMaliFtechiz** [comment]
hi @gouri-panda ,

I think your branch is not up to date with develop , I can't see changes for ```disable-animaiton``` and sdcard.

**Review by MohitMaliFtechiz — APPROVED** [review]
Approved

**Pull request merged**
