### PR TITLE
On clicking menu item icon new tab is open. #995

### PR DESCRIPTION
**Pull request by prajurock**
On clicking menu item icon new tab is open. #995

Changes: Open default new tab after closing all tab

Screenshot

### CODE REVIEW

**Comment by prajurock** [comment]
@soloturn @mhutti1 @abdulwd Closing all tab form App leads to open new home page after 1500ms.

**Comment by soloturn** [comment]
i just noticed there is #1021 (for #1011), this one, and #1009. @iadeelzafar what you think about this one?

**Comment by iadeelzafar** [comment]
In the current state of the app, when all tabs are closed, and user tries to go back to the Tab Layout a new tab opens automatically. 
That NewTab is either the Home Page of a book user was reading earlier. Or If there are no books downloaded, it will be the Home Page of the app.
Hence, I think the current state of the app is also doing the same work but with a different and better approach. The differences are that you open a NewTab after 1500ms while in the current state of the app, a newTab is opened when user tries to go back to the webview layout or clicks menu which is a good solution too and also it opens the newTab depending on either zim files are downloaded or not.
@prajurock I appreciate your work but IMO, the current state of the app has a better approach. Rest, I leave it to @soloturn @mhutti1.

**Comment by iadeelzafar** [comment]
In the current state of the app, when all tabs are closed, and user tries to go back to the Tab Layout a new tab opens automatically. 
That NewTab is either the Home Page of a book user was reading earlier. Or If there are no books downloaded, it will be the Home Page of the app.

Hence, I think the current state of the app is also doing the same work but there's a bug in it.
When there are ZIM files available, it will open that ZIM File as a newTab automatically when all tabs are closed but the bug here is that even after Zim File is deleted, it will still open that File as a newTab and user can read that book.

**The BUG:**





Hence, I think it is better to open the Kiwix Home Page in all cases which this PR is doing. As currently there are two cases according to which the newTab is opened which introduces a bug.

But there's one suggestion from my side that would be to open the default tab after user clicks the Menu or tries to go back to the webViews and not after 1500ms.

Rest, I leave it to @soloturn

**Comment by iadeelzafar** [comment]
@soloturn #1021 is valid for the time being there are zero tabs and user hasn't clicked on the menu yet or if this PR is approved with 1500 ms then I'll change the approach of hiding the FAB until 1500 ms reaches.

**Comment by prajurock** [comment]
Hey, @iadeelzafar Thanks for writing. In this PR if you deleted all the tab then new tab automatically open after 1500ms there is no need of clicking menu icon. And 1500ms is very small time so it's not the issue as I think.

**Comment by soloturn** [comment]
to make it easy for @mhutti1 a short statement: "merge both" or "xx needs a change, then merge only one" e.g. would be appreciated. ideally @iadeelzafar could comment on @prajurock pull request, and the other way round, what you think?

**Comment by prajurock** [comment]
@soloturn @mhutti1 why Travis showing error?

**Comment by mhutti1** [comment]
One of our test devices is playing up and isn't available. All the other devices are passing. I am going to merge as it passes on all the other devices.

**Comment by iadeelzafar** [comment]
@prajurock The bug that I talked about above is still present. It doesn't got solved by the 1500 ms time. I suggested you to either open the default tab after  button is clicked or open the default tab right after use closes the last opened tab.

**Pull request merged**
