### PR TITLE
Fixed nightly worflow should only compile and upload APK

### LINKED ISSUE #3142: Nightly worflow should only compile and upload APK
Following https://farm.openzim.org/pipeline/00574c2051b106670951b836 discussion

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #3142

### CODE REVIEW

**Comment by kelson42** [comment]
@MohitMaliFtechiz Obviously this workflow should only run on one API, wee need to build and upload only once!

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz Obviously this workflow should only run on one API, wee need to build and upload only once!



> @MohitMaliFtechiz Obviously this workflow should only run on one API, wee need to build and upload only once!

@kelson42 currently we are only upload once only but running test cases on different API level so should i remove other and target only one?

**Comment by kelson42** [comment]
There is no test to run... so what would be the added value to build on many platforms?

**Comment by MohitMaliFtechiz** [comment]
> There is no test to run... so what would be the added value to build on many platforms?

We are only testing on API level like [22, 23, 24, 25, 27, 28] on nightly other then that there is no use of that .

**Comment by kelson42** [comment]
@MohitMaliFtechiz please remove unit tests

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz please remove unit tests

hi @kelson42 ,
I have removed unit test from nightly.

**Review by kelson42 — APPROVED** [review]

**Pull request merged**
