### PR TITLE
Clear history

### PR DESCRIPTION
**Pull request by ritik2017**
Fixes  Issue #1058. 

Changes: Added Toast "Nothing to clear when history is empty" .

Screenshots/GIF for the change: 
ezgif com-video-to-gif

### CODE REVIEW

**Comment by ritik2017** [comment]
@abdulwd can you please review the changes and merge request?

**Comment by prajurock** [comment]
screenshot_20190305-171647
Do for this clear history also

**Comment by ritik2017** [comment]
Hope this resolves the issue

**Comment by ritik2017** [comment]
@prajurock Is there anything else I am missing?

**Comment by prajurock** [comment]
> @prajurock Is there anything else I am missing?

I think NO

**Comment by iadeelzafar** [comment]
@ritik2017 I'm already working on this issue to add EmptyViews in History and Bookmarks Activity. So, there's no need for the Toast message. 
#1010

**Comment by prajurock** [comment]
> @ritik2017 I'm already working on this issue to add EmptyViews in History and Bookmarks Activity. So, there's no need for the Toast message.
> #1010

yeah, I agree too.

**Pull request closed without merging**
