### PR TITLE
changed rate-us dialog launch to 10 from original 5 per issue #1235

### LINKED ISSUE #1235: Delay request to rate app
There is some understandable level of complaint that the app would ask users to rate it even before they've had the chance to actually use it: 
https://play.google.com/apps/publish?account=9116215767541857492#ReviewDetailsPlace:p=org.kiwix.kiwixmobile&reviewid=gp:AOqpTOFynxa5ioZX8ieSt_oFHfIIOOwJ22EdjjM_1uKv88iRuUcA3EVM2BFGzN_2PwoGeQ7DQtyr1oFst5y6_Xg
Can we delay the prompt after the nth time the app is opened (with n=10 at least)?

### PR DESCRIPTION
**Pull request by jhbiggs**
Fixes #1235 

Changes: made the number of app-launches 10 from 5 before the 'rate us' dialogue launched.

### CODE REVIEW

**Comment by kelson42** [comment]
@jhbiggs @Popolechien I let you judge if this would be a "good enough" approach. I have no opinion on this.

**Comment by macgills** [comment]
@jhbiggs going forward please adhere to the branching strategy outlined [here](https://github.com/kiwix/kiwix-android/blob/develop/CONTRIBUTING.md#branching), also the [commitstyle](https://github.com/kiwix/kiwix-android/blob/develop/docs/commitstyle.md). They may have changed a bunch since you last saw them so it is not a concern for this PR, we are stabilising these rules a lot and I will slowly get stricter the more confidence I have in them.

I think this solution is fine, I would have loved to see a rewrite of RateAppCounter in Kotlin + unit tests + DI, the removal of `tempVisitCount` in MainActivity, extracting a constant so 5/10 here is not just a magic number, the dialog being shown by KiwixDialogShower, basically just a nice little cleanup of this feature but this works and is quick.

**Comment by macgills** [comment]
@rashiq @Popolechien I would like your input also before we merge this

**Comment by Popolechien** [comment]
Sounds good to me.

**Comment by rashiq** [comment]
shit it! 👍

**Comment by rashiq** [comment]
ship it! 👍

**Comment by kelson42** [comment]
@macgills I think we can go on with the merging. I agree with all the points in your comment, they are valid. But this is maybe a bit much asking to @jhbiggs that time. He has fixed the problem in an acceptable manner and this is the most important for now.

**Comment by macgills** [comment]
Thank you all for the input, merging

**Pull request merged**
