### PR TITLE
Improved Dialog box

### LINKED ISSUE #430: Inappropriate dialog box in downloading fragment
**Is it a ?**
 Bug report
## Bug Report
When a user want to cancel the downloading wiki article,a dialog box is popping up with white shaded in background.I attached a screenshot below.

### Step 2 : What is your environment ?
  * browser / app : ___app__
  * version of the software you use : _2.2 Build:53__
  * device / operating system : ___Android Version 4.4.2 ( ASUS_T00J)__
  
### Step 3: Describe the problem:

  * What do you obtain? A copy of the error message or a screenshot is always useful
screenshot_2018-02-16-16-35-54

  * When does this occur? 
When user cancel the ongoing download in downloading fragment.

  * What should be the behaviour from your point of view? How do you expect the service to work?
    The behaviour of dialog box should be simple one clearing the white background as seen in the screen shot.

**Do you want to work on this?**
Yes

@mhutti1 @kelson42   Your reviews please?

### PR DESCRIPTION
**Pull request by RajaVamsi11**
Fixes #430 

Changed the alert dialog box in downloading fragment for removal of white shadowed part.

### CODE REVIEW

**Comment by RajaVamsi11** [comment]
Ok ..i did not noticed the changes.My bad.I will change it as you requested @mhutti1 .

**Comment by RajaVamsi11** [comment]
I accidantally deleted my dialog_box in local.So i am going to close this PR and open a new one.

**Comment by RajaVamsi11** [comment]
I know that closing and opening a PR's is not a good thing.It just happened.I will be careful in future.

**Comment by mhutti1** [comment]
@RajaVamsi11 Ok you could just have pulled your remote copy though.

**Pull request closed without merging**
