### PR TITLE
If no illustration available, display default logo for zim file

### LINKED ISSUE #2772: WikiHow zim files are definitely not using the correct logos / icons
From wikihow created by [Popolechien](https://github.com/Popolechien): openzim/wikihow#104  

Screenshot wikiHow

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #2772

### CODE REVIEW

**Comment by kelson42** [comment]
@gouri-panda Hi, would be great if you could review this ticket in priority

**Comment by gouri-panda** [comment]
@kelson42 Ok

**Comment by gouri-panda** [comment]
@MohitMaliDeveloper Our Assemble job is failing because some jitpack artifacts can't download.

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliDeveloper Our Assemble job is failing because some jitpack artifacts can't download.

Hi @gouri-panda ,

Currently jitpack is down it's returning ```521 error code```  that's why jitpack artifacts can't download.

**Review by gouri-panda — APPROVED** [review]

**Pull request merged**
