### PR TITLE
Refactor bottom toolbar

### LINKED ISSUE #745: Refactor bottom toolbar
The bottom toolbar has to be refactored to make it more user-friendly.

image

This is just a mock-up final design has to be discussed with @mhutti1 and @rashiq.
Should we include a button for the table of contents like the Wikipedia app does?

### PR DESCRIPTION
**Pull request by abdulwd**
Fixes #745 
The bottom toolbar is black in day mode as well as night mode.
@mhutti1 Do any reordering or change of color of the toolbar in day mode or night mode has to be done?
image

### CODE REVIEW

**Comment by abdulwd** [comment]
@mhutti1 Do you think that we should add Instagram like heart animation when adding bookmarks. But that will require us to remove the Snackbar which is shown on adding items to bookmark, then we will have to use a Toast instead.

**Comment by mhutti1** [comment]
I think that can be added. Later.

**Comment by abdulwd** [comment]
@mhutti1 It is ready to be merged.
image

**Comment by abdulwd** [comment]
@mhutti1 I have changed the alpha of the arrows to identify if the forward/ back actions are possible.
I will fix the white status bar issue in some other PR.

**Pull request merged**
