### PR TITLE
Make Alert Dialog boxes Uniform #960

### PR DESCRIPTION
**Pull request by prajurock**
Make Alert Dialog boxes Uniform #960

Changes: Changes in Style

Screenshots/GIF for the change: [If possible, please add relevant screenshots/GIF]
whatsapp image 2019-02-10 at 4 36 48 am 1  whatsapp image 2019-02-10 at 4 36 48 am

### CODE REVIEW

**Comment by prajurock** [comment]
@siddharth2010 Please Review.

**Comment by abdulwd** [comment]
@prajurock Can you add screenshots of the other screen as in the issue?

**Comment by prajurock** [comment]
whatsapp image 2019-02-10 at 5 29 17 pm 1
whatsapp image 2019-02-10 at 5 29 17 pm

**Comment by siddharth2010** [comment]
@prajurock , The 'alert icons' in the history and the external link dialog boxes should also be uniform. I think you should add the one in the delete history dialog to the external link one as well.

image

**Comment by siddharth2010** [comment]
Also, I just noticed that the Language Selection dialog box, has different dimensions depending upon whether the mode is light or dark.

| Light Mode | Dark Mode   
| -------------        |:-------------:| 
|screenshot_20190210-194001|screenshot_20190210-194010

I think we should probably fix all such issues in this PR

**Comment by prajurock** [comment]
Let me check.

**Pull request closed without merging**
