### PR TITLE
refactor: Implement SearchActivity using MVP pattern

### LINKED ISSUE #372: Refactor SearchActivity according to MVP pattern.
**Description**

Since the architecture used in the project is MVP, SearchActivity should also be refactored to use MVP pattern.

**Would you like to work on this?**

Yes

**Parent issue**

#29

### PR DESCRIPTION
**Pull request by srv-twry**
closes #372 

Gif: 
videotogif_2018 02 14_07 50 24

@mhutti1 Please review.

### CODE REVIEW

**Comment by mhutti1** [comment]
Side note are you able to request a review using the sidebar feature instead of asking or do you need more permissions?

**Comment by srv-twry** [comment]
No, i can't ask for reviews from the side bar.

**Comment by srv-twry** [comment]
No, i can't ask for reviews from the side bar.

**Comment by mhutti1** [comment]
Once you accept the email request sent to you  it should be possible from now onwards (hopefully).

**Comment by srv-twry** [comment]
@mhutti1 I have accepted it but still can't.

**Comment by mhutti1** [comment]
Ok, will look into this further then. Thanks for the info.

**Pull request merged**
