### PR TITLE
Help

### LINKED ISSUE #610: [Bug] Bottom toolbar is allowing "Help" to be bookmarked
### Are you ready to report?
   - Yes

### Environment
  * version of the software you use : Latest master
  * device / operating system : Android 7.1
  
### The Bug:

  Action bar doesn't allow Help to be bookmarked but when you enable bottom toolbar, it allows you to bookmark help.

**What should be the behaviour from your point of view? How do you expect the service to work?**

Help should not be allowed to be bookmarked as it is already there in menu.

### PR DESCRIPTION
**Pull request by hjoshi123**
Fixes #610 

Changes: Added comparison with help file i.e if
```
getCurrentWebView().getUrl().equals("file:///android_asset/help.html")

```

### CODE REVIEW

**Comment by hjoshi123** [comment]
@mhutti1 @srv-twry Only look at KiwikMobileActivity i.e this commit https://github.com/kiwix/kiwix-android/pull/656/commits/401d389c9734a30074795be81d6b31ae09c838aa. The rest are commits from another PR.

**Comment by srv-twry** [comment]
> The rest are commits from another PR.
Yes,so please don't add them in this PR. Why are they even included in this branch ?

**Comment by hjoshi123** [comment]
Ok. lemme delete them for you

**Comment by hjoshi123** [comment]
@srv-twry Check it out now.

**Comment by srv-twry** [comment]
Github still shows 3 commits for me although the files changed is correct now. Did you checkout master before creating the new branch help ?

**Comment by hjoshi123** [comment]
@srv-twry Forgot that. Would that create a problem if this code is accepted? Because the files are changed right?

**Comment by srv-twry** [comment]
Yes, unfortunately it will. The aim is to solve one issue per PR so that in case something goes wrong we can find the root cause of the issue. 
This is a very small change so you can close this PR and easily do it again the right way.

**Comment by hjoshi123** [comment]
Ok. Cool I reset it now.. Just give me 5-10 min I will do a PR again. Sorry for the trouble

**Pull request closed without merging**
