### PR TITLE
 io.objectbox:objectbox: updating to maven repo with version 2.9.1 

### LINKED ISSUE #2828: Jcenter dependency: io.objectbox:objectbox
### Describe the bug
We are using ```io.objectbox:objectbox```  for database operations. Version we are using 2.8.1 is available on jcenter while higher version are available on maven central. 

Maven Central have 3.1.3 as latest version. I am updating to this version.
https://mvnrepository.com/artifact/io.objectbox/objectbox-android

Part of #2816

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #2828 

 updating to maven repo with version 2.9.1

### CODE REVIEW

**Comment by gouri-panda** [comment]
@MohitMaliFtechiz Is this PR ready to review? or Are you planning to refactor the code as you suggested in the issue section?

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz Is this PR ready to review? or Are you planning to refactor the code as you suggested in the issue section?
For Now i have update to 2.9.1 which is on maven repo , latest version require refactoring of code which is basically for every library which we are using , we should handle the library update or replace ticket independently.

**Comment by gouri-panda** [comment]
Then we should pause here, it'll download this version from Jcenter too.

**Comment by MohitMaliFtechiz** [comment]
> Then we should pause here, it'll download this version from Jcenter too. What do you think @MohitMaliFtechiz @kelson42 ?

hi @gouri-panda version 2.9.1 is only available on maven central its not available on Jcenter.
https://mvnrepository.com/artifact/io.objectbox/objectbox-android

**Comment by gouri-panda** [comment]
@MohitMaliFtechiz My bad! Sorry!

**Review by gouri-panda — APPROVED** [review]

**Pull request merged**
