### PR TITLE
Fix memory leaks

### LINKED ISSUE #615: Fix memory leaks
## Bug Report
We must fix all the memory leaks present in the app as it leads to **ANR** and crashes especially on older devices.

### Environment
* version of the software you use: 2.3
* device / operating system: Redmi Note 3 / Android 6.0.1
  
### The Bug:
Memory leaks are present in the following classes:
* KiwixWebView - The **Handler** class must **be** static.
* DownloadService - **DownloadFragment** field must **not** be static.
* KiwixDatabase - **KiwixDatabase** field must **not** be static.
* ZimContentProvider - **Context** field must **not** be static.
* ZimFileSelectFragment - **ZimManageActivity** must **not** be static.

@kelson42 @mhutti1 Please review this issue.

### PR DESCRIPTION
**Pull request by abdulwd**
Partially fixes #615
Fix memory leaks.

All tests pass locally.

### CODE REVIEW

**Comment by abdulwd** [comment]
@mhutti1 @kelson42 Please review and merge this so that I can move onto #98 in which I will try to improve the performance.

**Comment by kelson42** [comment]
@abdulwd I hope you have the same problem as @mhutti1. Please try to test your code intensively before making a PR. Like you see, the maintainers, are really running short on time and it's important you provide the best of the quality as possible, so the maintainer work is reduced to the really necessary.

**Comment by abdulwd** [comment]
@mhutti1 I have rebased the branch and all the tests are passing.

**Comment by mhutti1** [comment]
Moved to #721

**Pull request closed without merging**
