### PR TITLE
prepare switch to build.gradle.kts

### PR DESCRIPTION
**Pull request by soloturn**
following the migration guide here:
https://guides.gradle.org/migrating-build-logic-from-groovy-to-kotlin/

this is based on PR #1177 - therefor it looks like more commits are in here ...

### CODE REVIEW

**Comment by soloturn** [comment]
@mhutti1 who merges pull requests nowadays if not you? @kelson42 ?

**Comment by kelson42** [comment]
@mhutti1 Yes, really easier if the one approving the PR - if the only one - do also the merge.

**Comment by mhutti1** [comment]
I think this needs the wrapper updating in kiwix build too.

**Comment by mhutti1** [comment]
On the other hand it seems to be working fine with a different version so Ill merge and change if needed.

**Comment by soloturn** [comment]
> I think this needs the wrapper updating in kiwix build too.

you mean here: https://github.com/kiwix/kiwix-build/commit/260ba5fce03c1eae37212ad54f4015793a8314f0 ? how is this used, resp tested?

**Pull request merged**
