### PR TITLE
Removed Debouncing mechanism

### LINKED ISSUE #3608: Display search results as you type delay
**Describe the bug**
Search results aren't instantly displayed while typing in search bar after selecting a zim library

**Expected behavior**
Display search results as you type

**Steps to reproduce the behavior:**
1. Select a zim library
2. Click on search button
3. Input text

**Environment**
- Version of Kiwix Android : 3.9.0
- OS version : Android 10

### PR DESCRIPTION
**Pull request by gouri-panda**
Fixes #3608

It removes debounce mechanics in order to have a better user experince.

### CODE REVIEW

**Comment by kelson42** [comment]
@gouri-panda We are sure this does not reintroduce new crash scenario? As well, I see you have removed the whole test, does that mean we have no test anymore for the suggestions?

**Comment by gouri-panda** [comment]
@kelson42 The test was specifically for the testing of debounce test to make sure we're not searching after a certain period of time.

**Comment by MohitMaliFtechiz** [comment]
@gouri-panda I have tested it and it searches results a little faster, I have tried with both codes with slow/fast typing, and without debouncing it is 500ms faster to fetch the results.

> @gouri-panda We are sure this does not reintroduce a new crash scenario. 

We should make sure about this, However, on my device, there is no crash with this new code. @gouri-panda had faced a crashing issue on his device. @gouri-panda have you faced the crashing issue on your devices after this fix?

Apart from this, @gouri-panda if we are going to remove the debouncing from our search functionality, we should remove all the code related to it.

**Comment by kelson42** [comment]
@MohitMaliFtechiz please remove addional code if needed

**Comment by kelson42** [comment]
@MohitMaliFtechiz what’s up here? This is prio PR to handle.

**Comment by MohitMaliFtechiz** [comment]
@kelson42 We have removed unnecessary debouncing code from the search functionality, and modified the test cases accordingly.

**Comment by gouri-panda** [comment]
@MohitMaliFtechiz @kelson42 Sorry for late reply! Yes, the changed code looks good to me! @MohitMaliFtechiz I can't see the new crash scenario. But if we have a chance to test this on the low-end devices. then that would be perfect. Also, we should write various test case scenarios to ensure they pass what we intended.

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz @kelson42 Sorry for late reply! Yes, the changed code looks good to me! @MohitMaliFtechiz I can't see the new crash scenario. But if we have a chance to test this on the low-end devices. then that would be perfect. Also, we should write various test case scenarios to ensure they pass what we intended.

@gouri-panda Thanks for confirming that you have not been able to reproduce the crash scenario, i have tested it on the lower API level emulators and it did not crash. Writing the test cases is a good idea, we have a ticket for this https://github.com/kiwix/kiwix-android/issues/3596.

**Pull request merged**
