### PR TITLE
[WIP] Create new Layout for Main Kiwix Banner

### LINKED ISSUE #911: Fix aspect ratio of main banner in home screen
**Is your feature request related to a problem? Please describe.**

when the device is rotated, the main Kiwix banner looks distorted.

Here's the screen:
screenshot_20190109-023355

And heres how it looks when the device is rotated:
screenshot_20190109-024049

**Describe the solution you'd like**

we could create the banner using three layers, (one for the main rectangle base, one for the kiwix logo, and one for the side pattern), instead of one. Then, in rotated mode, we can just change the size of the base layer, and change the relative positions of the side pattern, and the kiwix logo).

### PR DESCRIPTION
**Pull request by siddharth2010**
Fixes #911 
I am using basically the exact same strategy as done in #1027 

The main banner has now been broken down to three parts instead of one:

| . | . | . | . |
|:-:|:-:|:-:|:-:|
|Orientation|Left|Base Image|Right Pattern|
| Vertical | ic_kiwix_widget | back_cover | home_side_cover |
| Horizontal | kiwix_logo | back_cover | home_side_cover |

#### Screenshots
Vertical Layout

| . | . |
|:-:|:-:|
|Screenshot_1567289339|Screenshot_1567289379|

Horizontal Layout

|. | . |
|:-:|:-:|
|Screenshot_1567289355|Screenshot_1567289374|

### CODE REVIEW

**Comment by siddharth2010** [comment]
This is currently a work in progress. I need to fix a few bugs in the layout, and remove the extra image assets.

**Comment by siddharth2010** [comment]
@abdulwd , I have fixed the border and also made the eye transparent.
However, I am not sure if I should be adding the **kiwix_logo_night.png** and the **kiwix_logo.png** to all `mdpi`, `hdpi`, `xhdpi`, `xxhdpi`, `xxxhdpi`, etc since as mentioned by rashiq in his comment to #911, android is capable of downsizing images.

**Comment by macgills** [comment]
@siddharth2010 there should be icons of appropriate size in every density folder we have

**Comment by siddharth2010** [comment]
Got it! Will fix that..

**Comment by macgills** [comment]
It is a bit plate to be mentioning it but this could have theoretically been done using a 9-patch and would have probably made it a lot easier

**Comment by siddharth2010** [comment]
Got it @macgills ! sorry for the late reply, but I was in the middle with my univ lab exams. I will be getting over with them on 10th. will fix it then.

**Comment by macgills** [comment]
@siddharth2010 will you be able to finish this shortly? The milestone is now a day over and I expect to begin the full rollout in the coming days and it would be great to have this change in it

**Comment by siddharth2010** [comment]
@abdulwd @macgills , Can you Test the UI.. I think its glitching a bit sometimes on my end. Not sure why thats happening.

**Comment by macgills** [comment]
@siddharth2010 those are not 9 patch files, 9 patch extension is `.9.png`, more info [here](https://developer.android.com/studio/write/draw9patch).
That said we don't necessarily need the 9 patch but it would have allowed us to use only 2 images here by defining a "stretchy" portion of the image and then having a day/night resource

**Comment by siddharth2010** [comment]
oh, got it! @macgills ! Actually I initially generated the 9 Patch files having the .9.png extension, but They were showing a 1 px black border at the top edge centre and the right edge centre.
I tried to fix it through code, but wasnt. So I imported them to Photoshop and manually cropped 1 px from the height and 1 px from the width of all the images..

**Comment by siddharth2010** [comment]
But I think your idea is actually a lot better.. we should probably go with that approach instead.

**Comment by macgills** [comment]
hahaha, that is how a 9patch works! The 1px border is how you define where and what stretches.

You may have to create some negative space in the middle of the image to allow the stretch but the draw9patch tool should give you an accurate preview of what the image will look like

**Comment by siddharth2010** [comment]
woah, I thought maybe my emulator was glitching, and I ended up creating like two more AVDs just to see what that 1 px border was... Thanks! That clears a lot of stuff!

**Comment by macgills** [comment]
working off the base image I can make it do this:
image
Or this:
image

but to take this any further I will need help in manipulating the image so that there is at least 1px of horizontal blank space inbetween the kiwix icon and the connected web of dots. @kelson42

**Comment by kelson42** [comment]
@macgills Second one

**Comment by macgills** [comment]
fixed by #1503

**Pull request closed without merging**
