### PR TITLE
Removed Squidb code

### LINKED ISSUE #3168: Remove Squidb code
My understanding is that this code, introduced almost 4 years ago, has been responsible to handle everything which is currently handled with ObjectBox. There is also the migration code from SquidB to ObjectBox. All of this would make sense today only for a use which has a version of Kiwix for Android >4years... This is almost nobody.

Assuming there is no concrete impact on users having a recent version of Kiwix, please remove all the SquidB related code.

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #3168

### CODE REVIEW

**Review by kelson42 — CHANGES_REQUESTED** [review]
`credits.html` have not been upldated. In such a case, please at least run a `grep` on the whole source code.

**Comment by gouri-panda** [comment]
@kelson42 @MohitMaliFtechiz We should review/merge after the complete of migration of Room.

**Comment by kelson42** [comment]
@gouri-panda @MohitMaliFtechiz I don't really understand why we should wait actually? This shoukd not have so much code in common with Room! What is exactluy the problem which stops us to merge?

**Comment by kelson42** [comment]
@MohitMaliFtechiz @gouri-panda Please rebase and review, we should not wait additonal weeks for merging.

**Comment by gouri-panda** [comment]
@kelson42 I think after Room migration there may be a lot of conflicts. I'll try to finish room migration this WE. So we can move forward with this PR after this WE.

**Comment by kelson42** [comment]
@gouri-panda where exactly?

**Comment by gouri-panda** [comment]
@kelson42 I think particularly in the migration of ObjectBox and tests.

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz @gouri-panda Please rebase and review, we should not wait additonal weeks for merging.

ok @kelson42 I am rebasing it.

**Pull request merged**
