### PR TITLE
Removed the dialog box to select the storage in settings.

### LINKED ISSUE #3970: Revamp Settings > Storage
Here are the requested changes:
* Stop using an overlay/dialog box, the radio button to choose between the multiple storages should be directly in the settings
* It should be clearer (written?) what is total and empty space
* The exact path used should be written. In can this is the storage chosen, then we know what it is as this is a settings stored in the configuration. But in case of a non-used storage, this is hypothetical as there is no settings, the value should come from the code. This last bullet point is important as we will move from the private to the public app directory... people with everything in the private app directory should keep their private app directory but new user should better use public app directory.

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #3970 

* Now, the storage selection (internal/external) is directly visible in the settings with new visual, allowing users to select storage without using a dialog box.
* The total, used, and available space for each storage option is displayed.
* Additionally, the selected storage path is shown in the settings, so users know where the downloaded files will be saved.

https://github.com/user-attachments/assets/e259886e-0037-4d53-9972-38ca82792f45

### CODE REVIEW

**Comment by kelson42** [comment]
@MohitMaliDeveloper This is pretty much what I had in mind, two things:
* Please always display the location, even if not selected.
* Use this visual representation 
image

**Comment by MohitMaliFtechiz** [comment]
@kelson42 I have made the changes as you requested and updated the PR description with the video.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Thisnlooks perfect. Have you checked this displaynproperly in RTL laanguages like arabic?

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz Thisnlooks perfect. Have you checked this displaynproperly in RTL laanguages like Arabic?

@kelson42 Now it's displaying properly in RTL.

Screenshot from 2024-08-08 11-03-50

**Pull request merged**
