### PR TITLE
feat: Converted SharedPrefUtil to Kotlin and Set the OnlineLib Working

### LINKED ISSUE #2200: chore: Convert SharedPreferenceUtil.java to Kotlin Class
Currently, SharedPreferenceUtil.java is written in java, it should be instead in Kotlin.
For more info.:
Refer #1826

### PR DESCRIPTION
**Pull request by s-ayush2903**
* Close #2200 
* Mentions #2201 
* Mentions #2325 

**Screenshots** 
NA

### CODE REVIEW

**Comment by s-ayush2903** [comment]
* It was a quite subtle error and exactly what i was doubting to be, why does this happen.
* While working with robot i encountered the same problem. The function ran well and fine when passed arguments in `()` but always failed in `{}`. e.g. look at the second last commit, this exactly how i fixed the onlineLib, why does `{}` not work and what it is meant for? 
* I noticed, it runs as expected when called multiple functions/args in it, but fails when provided with one, why? Do we have some official doc considering this or you may throw some light on it

**Comment by s-ayush2903** [comment]
Flaky IntroTest is Creating Issues

**Comment by s-ayush2903** [comment]
How should i reword the commit which fails the staticAnalysis? I'm unable to do so as when i rebase commits, the hook is triggered which seems impossible to by-pass and ends up in failing the analysis and in turn rewording. Ideas

**Comment by macgills** [comment]
@s-ayush2903 because they are different methods. `{}` is kotlin syntax for a function, when the last parameter of a method is a function then you don't need to put it inside the `()`
image

image

**Comment by macgills** [comment]
> How should i reword the commit which fails the staticAnalysis? I'm unable to do so as when i rebase commits, the hook is triggered which seems impossible to by-pass and ends up in failing the analysis and in turn rewording. Ideas

During rebase you can combine commits together so they don't fail static analysis? I am not sure I understand the scenario

**Comment by s-ayush2903** [comment]
I'm actually rewording the first commit and then picking the rest ones. I'm refraining from squashing them

**Comment by s-ayush2903** [comment]
The scenario is like this:
I had five commits in a row, in which first three out of those five fail the staticAnalysis, so when i'm in a rebase session, and reword the first commit and mark remaining as pick, (even with _--no-verify_)the lint is triggered in fails in a few secs.

**Comment by macgills** [comment]
Every commit should pass SA, this is by design. The conversion of 1 file I wouldn't split into multiple commits.

**Comment by s-ayush2903** [comment]
So should i squash 'em all?

**Comment by macgills** [comment]
I'm fine with that

**Comment by s-ayush2903** [comment]
> I'm fine with that

Multiple commits or  a single one?

**Comment by macgills** [comment]
squashing them all

**Comment by s-ayush2903** [comment]
@macgills Can you please give it a review.

**Review by macgills — APPROVED** [review]

**Pull request merged**
