### PR TITLE
Fixes custom app wikimed bundle build problem 

### LINKED ISSUE #3634: Execution failed for task ':custom:shrinkBundleWikimedReleaseResources' - Java heap space error
Description:
While attempting to build a bundle for publishing, I encountered the following error:

```
Execution failed for task ':custom:shrinkBundleWikimedReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.transforms.ShrinkAppBundleResourcesAction
   > Java heap space

```

I believe this is happening due to the large amount of the bundle size. We should add a reasonable amount of the heap size for the compiler in the build time NOT runtime as long as that satisfies for all our large custom apps.

Additional context:
https://github.com/kiwix/kiwix-android-custom/actions/runs/7337740623/job/19979122016#step:7:259

### PR DESCRIPTION
**Pull request by kelson42**
Fixes #3634

### CODE REVIEW

**Comment by kelson42** [comment]
@gouri-panda Why do we need this? Does that apply at build time or at run time?

**Comment by gouri-panda** [comment]
@kelson42 Both in runtime and build time. I think the number is too high for a local computer. So i think it would be best if we only change in our virtual environment. 8GB would be fine. @MohitMaliDeveloper what do you think?

**Comment by kelson42** [comment]
@gouri-panda Why we need to do that? Why suddently we need to have more memory allocated on the heap?

**Comment by kelson42** [comment]
@MohitMaliDeveloper @gouri-panda Please fixes in PRIO, but just upgrade slightly, 16GB is far too much!

**Comment by MohitMaliFtechiz** [comment]
@gouri-panda Before, it was 4GB. We should increase it to 6GB or 8GB according to the need, i agree with @kelson42 that 16GB is too much.

**Comment by MohitMaliFtechiz** [comment]
@gouri-panda Thanks for the quick changes, can you try with this PR code to publish the custom app, so that we can ensure that 5GB is enough?

**Comment by gouri-panda** [comment]
@kelson42 @MohitMaliFtechiz 5GB works fine with the Wikimed https://github.com/kiwix/kiwix-android-custom/actions/runs/7337591202/job/19981573502. It'll also allow to speed up other tasks.

**Comment by MohitMaliFtechiz** [comment]
@gouri-panda Thanks for testing, now resolved the one problem. We have one more size problem. Does that link work that @kelson42 provided you?

**Comment by gouri-panda** [comment]
@MohitMaliFtechiz which link? Github action link?  That was created by me.

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz which link? Github action link? That was created by me.

Not GitHub link, i am talking about ZIM file link https://mirror.download.kiwix.org/zim/.hidden/custom_apps/mdwiki_en_all-app_maxi_2023-10.zim

**Comment by gouri-panda** [comment]
No. We did tried with another zim. That didn't work either.

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz which link? Github action link? That was created by me.

Hmm, i checked both ZIM files has the same size.

**Pull request merged**
