### PR TITLE
Feature/gouri-panda/Fix_exteranal_search

### LINKED ISSUE #2577: Application crashes while searching in inside the app
**Expected behavior**
No crash

**Steps to reproduce the behavior:**
1. Open the Kiwix app
2. Open a zim file
3. Select a text and click search Kiwix
4. Open a zim file

**Environment**
- Version of Kiwix Android: 10
- Device: Realme
- OS version: 10

https://user-images.githubusercontent.com/43576162/104331058-a7ed8480-5514-11eb-9472-96f86ef59c5b.mp4

### LINKED ISSUE #2601: Back Press doesn't work in SearchFragement
**Describe the bug**
The back button doesn't work(stuck) while Searching

**Expected behavior**
It should go where it comes from.

**Steps to reproduce the behavior:**
1. Open the Kiwix app
2. Select a word
3. Press Search Kiwix
4. Press Back Button

**Environment**
- Version of Kiwix Android: 3.4.3
- Device: Realme
- OS version: 10

### LINKED ISSUE #2602: Search text don't appear in the search field
**Describe the bug**
If we select a text and click Search Kiwix then the selected text doesn't appear in the search field

**Expected behavior**
 Search Text should appear in the SearchEditText
**Steps to reproduce the behavior:**
1. Open the Kiwix app
2. Select a word
3. Press Search Kiwix
4. See the search field

**Environment**
- Version of Kiwix Android: 3.4.3
- Device: Realme
- OS version: 10

### LINKED ISSUE #2603: Clicking the search result doesn't go anywhere
**Describe the bug**
If we search through the search field and click the search result then the search result doesn't open the link

**Expected behavior**
 Search Text should appear in the SearchEditText
**Steps to reproduce the behavior:**
1. Open the Kiwix app
2. Select a word
3. Press Search Kiwix
4. Type a text to search
5. Click the link

**Environment**
- Version of Kiwix Android: 3.4.3
- Device: Realme
- OS version: 10

### PR DESCRIPTION
**Pull request by gouri-panda**
Fixes #2577 
Fixes #2601 
Fixes #2602 
Fixes #2603

### CODE REVIEW

**Comment by gouri-panda** [comment]
The reason the above issues are partially solved because the `SearchFragment` created multiple times(2,3). So if we press the back button or click the search item multiple times(2,3), then it works fine.

**Comment by gouri-panda** [comment]
@abdulwd If we click twice the back button then it closes the `SearchFragment`. I invested a little bit found that the `CoreReaderFragment`  creates twice. Should we fix that here or create a separate ticket for it? Thanks!

**Comment by gouri-panda** [comment]
Ahh! got it for some reason `onCreateOptionsMenu()` Called multiple times that's why it creates multiple instances.

**Comment by kelson42** [comment]
@abdulwd Any feedback?

**Comment by abdulwd** [comment]
I'll check it tomorrow

**Review by abdulwd — APPROVED** [review]
Apologies. Got stuck with something else.

**Comment by gouri-panda** [comment]
No worries! Thanks for the review👍

**Pull request merged**
