### PR TITLE
initial fastlane structure

### PR DESCRIPTION
**Pull request by IzzySoft**
You've asked for it [via Mastodon](https://mastodon.social/@kiwix/108459083538537615) :wink: his relates to #2569 and provides an initial starter package – actually an "enhanced version", including…

* all the summaries already be made available by the translators at F-Droid
* the full description as currently present at F-Droid for `en-US`, plus a translation by me for `de`
* icon and screenshots as seen with your listing at Google Play

As mentioned by the author of the linked issue, you're welcome to use my [Fastlane Cheat Sheet](https://gitlab.com/snippets/1895688) to build on this. It would e.g. be great if you'd provide per-release changelogs (starting with the latest one is totally fine). A featureGraphic would be a cosmetic polish not strictly required but certainly welcome.

Should any questions be left, I gladly try to help further if I can.

### CODE REVIEW

**Comment by IzzySoft** [comment]
PS: Please squash when merging :rofl: Just had to apply some fix-up (images where in the wrong locale).

**Comment by gouri-panda** [comment]
@IzzySoft Did you give us access to modify the PR? Thanks!

**Comment by kelson42** [comment]
@gouri-panda He can not, this is his own fork. Do you want to change things?

**Comment by gouri-panda** [comment]
Hmm. I can't push the squashed commit.

**Comment by kelson42** [comment]
@gouri-panda Does it looks good to you? Beside this squashing?

@IzzySoft Can you please squash yourself your two commits?

**Comment by gouri-panda** [comment]
Yup! But the images are outdated.

**Comment by gouri-panda** [comment]
@kelson42 We can replace with new ones. The screenshot's were very old.

**Comment by gouri-panda** [comment]
@IzzySoft Thanks! We can take this from here. You just have to give us permission to edit the PR(for maintainers) or I can send a edit PR to your repo if you have time to merge :)

**Comment by kelson42** [comment]
@IzzySoft you should squash wit "git rebase".

**Review by gouri-panda — APPROVED** [review]
🎉

**Comment by IzzySoft** [comment]
Sorry. But though I managed to squash locally, git refuses to push (even with `git push --force`) stating that "everything is up-to-date". So I have no idea how I can help with that. But what I've found is the checkbox to allow edits by maintainers (which I checked now). so do as you please :wink:

**Comment by kelson42** [comment]
@IzzySoft I jave merged like it is... it is important we move forward

**Comment by IzzySoft** [comment]
Thanks a lot – and "good move" then!

**Pull request merged**
