### PR TITLE
Fixed sometimes CI fails in LanguageFragmentTest

### LINKED ISSUE #3161: Sometimes CI fails in ```LanguageFragmentTest```
**Describe the bug**
Sometimes CI fails with error ```select_language``` not found in ```LanguageFragmentTest```.

**Expected behaviour**
CI should be passed.

**Logs**
`org.kiwix.kiwixmobile.language.LanguageFragmentTest > testLanguageFragment[test(AVD) - 11] FAILED 
	java.lang.RuntimeException: No view found with Id org.kiwix.kiwixmobile:id/select_language
	-[DecorView] visibility:visible`

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #3161

### CODE REVIEW

**Comment by MohitMaliFtechiz** [comment]
we should merge this only after https://github.com/kiwix/kiwix-android/pull/3160

**Comment by kelson42** [comment]
@gouri-panda Are you OK to merge this?

**Comment by gouri-panda** [comment]
@kelson42 I'll review this soon.

**Comment by kelson42** [comment]
@gouri-panda At least CI is green ;)

**Review by gouri-panda — APPROVED** [review]

**Comment by gouri-panda** [comment]
@kelson42 LGTM!

**Pull request merged**
