### PR TITLE
#1766 Fix Tag Display Behaviour - correct inversion and add rule

### LINKED ISSUE #1766: Fix Tag Display Behaviour
**Describe the bug**
The tags curently do not operate to spec

**Expected behavior**
Short text/Text Only should display appropriately

### PR DESCRIPTION
**Pull request by macgills**
Fixes #1766

### CODE REVIEW

**Comment by rgaudin** [comment]
As I was to report the issue, I found #1766 and gave that PR a try. The **text-only** and **text** are gone which is good but could you explain why there are **Pic** and **Vid** badges on this ZIM files which has the following `Tags: _ftindex:yes;_ftindex` ?

Using this PR branch:


With master, it was:
master

**Comment by macgills** [comment]
@rgaudin 
```
tag_picture.selectBy(tags.isYesOrNotDefined<PicturesTag>())
tag_video.selectBy(tags.isYesOrNotDefined<VideoTag>())
```

this is the behaviour @kelson42 wanted

**Comment by rgaudin** [comment]
OK thanks. I guess we should update [the spec](https://wiki.openzim.org/wiki/Tags) so that all readers have a ref to implement the same default behavior. ie. if not set, consider videos and pictures to be present.

Brings another concern: considering video and pictures to be present is different than _advertising the presence of those_ ;)

**Comment by macgills** [comment]
@rgaudin if you need reference this behaviour was decided in #1650

**Pull request merged**
