### PR TITLE
Fix #1943 Update app icon

### LINKED ISSUE #1943: Update Kiwix logo
There is a new, slightly remodeled logo for Kiwix 
https://commons.wikimedia.org/wiki/File:Kiwix_logo_v3.png
The app's icon needs to be updated accordingly

### PR DESCRIPTION
**Pull request by yashk2000**
Fixes #1943

Updated app icon with the new Kiwix logo

### CODE REVIEW

**Comment by macgills** [comment]
@popolechien are you happy with this

image

**Comment by Popolechien** [comment]
Maybe a tad smaller like the old one - I wouldn't want it to fill the whole icon space.

**Comment by yashk2000** [comment]
@Popolechien this is the image that I directly download from the link you provided. 
https://commons.wikimedia.org/wiki/File:Kiwix_logo_v3.png
I haven't modified it in any way. 
The image in that link also fills the entire space.

**Comment by Popolechien** [comment]
@yashk can you try with this one then? I slightly reduced it with regard to the borders. Let me know if that works. Worst case we'll pick the best of those two choices.
smaller Kiwix

**Comment by yashk2000** [comment]
@Popolechien sure.
On it.

**Comment by yashk2000** [comment]
Screenshot from 2020-03-23 23-35-46

@Popolechien there's not much difference in both the icons.

**Comment by Popolechien** [comment]
@yashk2000 Yeah I'm kind of surprised by that, but so be it.
@macgills Let's roll.

**Comment by rashiq** [comment]
We don't need to add one for all these resolutions.

**Comment by yashk2000** [comment]
@rashiq I didn't get what you meant?
I've not added different icons for different resolutions. Android studio automatically scales the provided icon to support devices with different screen sizes. 
If they are not updated, on devices such as tablets, the old icon will be displayed instead of the new one.

**Comment by macgills** [comment]
@yashk2000 you can adjust the scale of the image
image

@Popolechien  are you still happy with the addition of this information? The Kiwi's nose looks awfully close to the edge of the circle in the currently proposed icons

**Comment by yashk2000** [comment]
@macgills @Popolechien should I update the icon with a new scale?

**Comment by Popolechien** [comment]
@yashk2000 Yes please. Ideally the scaling should be similar to that of the old logo.

**Comment by yashk2000** [comment]
@macgills @Popolechien does this work fine?

Screenshot from 2020-03-24 21-51-02

**Comment by Popolechien** [comment]
Awesome.

**Pull request merged**
