### PR TITLE
Fixed App crash issue [ #990 when we click pause or stop button for download in Landscape mode ] & [ #975 while tapping download notification and changing or stopping the download]

### PR DESCRIPTION
**Pull request by CodetoInvent**
Fixes #1162
Fixed App crash issued by @rohap97 [ #990 ] and @siddharth2010  [ #975 ]
This is the case 1 [ while tapping download notification and changing or stopping the download ]
which was issued by @siddharth2010 at #975

Notification Tap crash FIXED Link :
https://drive.google.com/file/d/1na4DFsWZuGRnI1acxJYZ8D20hJROYQSR/view?usp=sharing

This is the case 2 where App crashes when we click pause  or stop button for download in Landscape mode. 
Rotation Tap Crash Fixed Link
https://drive.google.com/file/d/1M4dMi2_TjgiuJTd5t5mZM1fryjDVi1D6/view?usp=sharing

@mhutti1 @abdulwd @kelson42 @siddharth2010 @soloturn please review this

### CODE REVIEW

**Comment by prajurock** [comment]
Squash your commits.And write the changes you done .

**Comment by CodetoInvent** [comment]
sure ill do that

**Comment by soloturn** [comment]
here some help on how to squash commits: https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git 

or is the difficulty to update the pull request then?

**Comment by CodetoInvent** [comment]
Thanks for the help sir.  I will squash all the commits as soon as possible. :)

**Comment by mhutti1** [comment]
Should be fixed by 2.5, closing

**Pull request closed without merging**
