### PR TITLE
Localisation updates from https://translatewiki.net.

### PR DESCRIPTION
**Pull request by translatewiki**
Translation updates

### CODE REVIEW

**Review by gouri-panda — APPROVED** [review]
Looks good to me! although we should fix the lint issues first.

**Comment by kelson42** [comment]
@gouri-panda Why we have so many red things in the CI?

**Comment by gouri-panda** [comment]
@kelson42 The static analysis is failing because of some backward slash issue and "...", otherwise I ran again CI Jobs. It's ok now.

**Comment by gouri-panda** [comment]
@kelson42 should we fix the static analysis in another PR?

**Comment by kelson42** [comment]
Yes please, my bad I should not have merged it. Sorry.

**Pull request merged**
