### PR TITLE
[WIP] UI Test Bottom Bar

### LINKED ISSUE #771: Add UI tests for the Bottom bar
Add UI tests for the Bottom toolbar created under #763

### PR DESCRIPTION
**Pull request by siddharth2010**
Fixes #771

### CODE REVIEW

**Comment by kelson42** [comment]
@siddharth2010 What should we do with that PR? Any plan to merge/finish it?

**Comment by siddharth2010** [comment]
@kelson42 , earlier I was unable to fix a persistent error while accessing the webview elements, and so I left it till I could figure out a solution. I forgot all about it. I will get right on it.

**Comment by siddharth2010** [comment]
@kelson42 , yes, I have this bad habit of always merging master. I will make it sure to use a rebase from now.

**Comment by kelson42** [comment]
@siddharth2010 I have deleted the branch as nobody seems to happen anymore here and there is no plan to merge the code.

**Pull request closed without merging**
