### PR TITLE
Stop using backticks in Shell script

### PR DESCRIPTION
**Pull request by kelson42**
@macgills Resolves 5 problems reported by Codefactor

### CODE REVIEW

**Comment by macgills** [comment]
I'd prefer to delete these scripts and probably some other scripts that are hanging around

**Comment by kelson42** [comment]
@macgills OK, can we document otherwise to do the same thing?

**Comment by macgills** [comment]
`create-signed-android-release.sh` this should just plain not be done anymore
`install-kiwix-on-device.sh` is easily done by `gradlew install<BuildVariant>` or `adb install <path to apk>` or you can just click the run button in AS.
`take-screenshot` AS has a button for this and if we need to do it in an instrumentation test then they have methods for this or if you are using an emulator then it is pretty easy to take a screengrab.

I don't see a purpose for any of these scripts and explaining more than we already have in contributing seems like overkill when they are one google away

**Comment by kelson42** [comment]
@macgills I don't really want to rely on GoogleStudio for the important operations. This is the purpose of these scripts:
* `make-screenshot.sh` will be kept for obvious reasons
* `create-signed-android-release.sh`, I guess we have an alternative as TravisCI does it?
* `install-kiwix-on-device.sh` not so sure we should keep it, but I don't really think why such a script should not work anymore 

But maybe we should make something like a `contrib` directory to avoid to pollute the root directory with them?

**Comment by macgills** [comment]
@kelson42 if you want to create a `scripts`/`contrib` folder go ahead but I think `create-signed-android-release.sh` should be deleted. 
`install-kiwix` can also go, `gradlew installKiwixDebug` is already there and will build the app if it is not there, `install-kiwix` seems to just install whatever is in the build outputs?

**Comment by macgills** [comment]
@kelson42 what is the status of this?

**Comment by macgills** [comment]
@kelson42 am I taking this over or will you be making the changes?

**Pull request merged**
