### PR TITLE
#2723 updated logo banner on hamburger menu

### LINKED ISSUE #2723: Update logo banner on hamburger menu
The current hamburger menu displays the old logo when opened
screenshot2

Here is the updated version (a bit of cropping will probably be needed):
.png: https://drive.google.com/file/d/1ZFYbQT-G8NbKMfyRSCat8wtOz_ujZtpW/view?usp=sharing
.svg: https://drive.google.com/file/d/1t6sU65SQZ8W1FgJp-2nCAiVkG3LVgz0I/view?usp=sharing

### PR DESCRIPTION
**Pull request by Rigzbot**
Fixes #2723

Updated logo banner on hamburger menu to use the updated image. 
Replaced the image with:
image

**Screenshots** 
image

### CODE REVIEW

**Review by gouri-panda — CHANGES_REQUESTED** [review]
@Rigzbot We should support all those pixel quality as well i.e hdpi, mdpi, xhdpi etc.

**Comment by gouri-panda** [comment]
@Rigzbot I only see xxhdpi. Did you commit?

**Comment by gouri-panda** [comment]
@Rigzbot In GitHub, I only see one file added but let me check on Android Studio.

**Review by cdhiraj40 — COMMENTED** [review]
here 
image

**Review by cdhiraj40 — COMMENTED** [review]
@Rigzbot here
image

**Comment by gouri-panda** [comment]
Yes! It is visible in Android Studio.

**Review by gouri-panda — COMMENTED** [review]
@Rigzbot Test cases are failing. You should update the test case as well.
```
org.kiwix.kiwixmobile.main.TopLevelDestinationTest > testTopLevelDestination[test(AVD) - 5.0.2] FAILED 
	java.lang.RuntimeException: java.lang.RuntimeException: No views in hierarchy found matching: with content description from resource id: <2131820869>[open_drawer] value: Open Drawer
```

**Comment by gouri-panda** [comment]
Run the test cases locally. Find the test cases which are failing. And find why it's failing. You can start by [here](https://developer.android.com/training/testing/fundamentals).

**Comment by gouri-panda** [comment]
@Rigzbot According to error no views found with content description my guess would be you need to update content description as well in your PR.

**Comment by gouri-panda** [comment]
@Rigzbot I think the test cases are failing On our side sorry for the inconvenience. We'll fix it as soon as possible.

**Comment by gouri-panda** [comment]
Yes! As far I know you don’t have any problem :)

**Review by gouri-panda — APPROVED** [review]
@Rigzbot Thank you for the contribution 🎉 ! and extremely sorry for the delayed review!

**Pull request merged**
