### PR TITLE
Added New book dao tests

### LINKED ISSUE #1864: Add unit tests for NewBookDao
### Problem
Unit tests are missing for `NewBookDao`

### Solution
Add unit tests for `NewBookDao`

### Additional Context
Parent issue: #1827 

### Working on it?
Yes

### PR DESCRIPTION
**Pull request by ashutosh1919**
Fixes #1864 .
@macgills , please review.

### CODE REVIEW

**Comment by macgills** [comment]
See my comments on https://github.com/kiwix/kiwix-android/pull/1862

**Comment by macgills** [comment]
@ashutosh1919 will you be able to finish off this PR? I generally close PRs after 2 stale labellings

**Comment by ashutosh1919** [comment]
Closing this and unassigning from issue. Because of COVID-19 pandemic in my area, will not be able to complete this on time.

**Comment by macgills** [comment]
@ashutosh1919 stay safe, it is a pretty scary time globally

**Comment by ashutosh1919** [comment]
@macgills, you too.

**Pull request closed without merging**
