### PR TITLE
fixes#2756 close keyboard when clicked on menu buttons of download screen and choose language

### LINKED ISSUE #2756: Keyboard doesnt hide when clicked on menu buttons of download screen and choose language
**Describe the bug**

The keyboard doesn't hide even when the editText is not focused
1) when clicked on ``choose a language `` from the download screen keyboard doesn't close and stays open in the select language screen
vice versa 
from the select languages screen when clicked on the ``tick``  icon keyboard doesn't close

**Expected behavior**
the keyboard should hide once editText has no focus
**Steps to reproduce the behavior:**
1. go to the download screen, click on search, see the keyboard open
2. now click on 
image
and see the keyboard still open on a different screen
1. go to select languages screen and click on search see the keyboard open
4. now click on tick and see the keyboard open on the download screen
-->

sorry if I couldn't explain properly
see this screen recording this might help in understanding

**Screenshots**

https://user-images.githubusercontent.com/75211982/144816520-36d0d53b-6c51-4dc1-bad8-dfc25f6ea329.mp4

**Environment**
- Version of Kiwix Android: 3.4.5
- Device: realme 6/ emulator
- OS version: android10/11

I would like to work on this issue :)

### PR DESCRIPTION
**Pull request by cdhiraj40**
fixes #2756 

**Screenshots**

### CODE REVIEW

**Comment by cdhiraj40** [comment]
I did follow  https://medium.com/@topspinj/how-to-git-rebase-into-a-forked-repo-c9f05e821c8a this time but I think I still made some mistakes

**Comment by gouri-panda** [comment]
@cdhiraj40 Still I think you miss something. If you have problems with commits in the branch. Start with a fresh brach.

**Comment by cdhiraj40** [comment]
> @cdhiraj40 Still I think you miss something. If you have problems with commits in the branch. Start with a fresh brach.

I have tried every PR with a new branch and have committed many times but it just never seems to work.
now I think the only thing I can think of is to fork it again and make new PRs if you all approve the old PRs

**Comment by gouri-panda** [comment]
There is a heck if you start a fresh branch from the remote dev branch. You can resume your work.

**Comment by cdhiraj40** [comment]
> There is a heck if you start a fresh branch from the remote dev branch. You can resume your work.

Oh I would love to know, as forking and doing the work again will be definitely unproductive

**Comment by cdhiraj40** [comment]
Closing this PR and opening a new one as there were problems with this branch, Sorry for the inconvenience.

**Pull request closed without merging**
