### PR TITLE
F-DROID AUTOMATICALLY BUILD INFO

### LINKED ISSUE #1682: Automatize publication on F-Droid
Doing this manually is too complicated.

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #1682

### CODE REVIEW

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliDeveloper How to you compute the second number? In a real release it should be computer _before_ releasing (usually the build number is computed by Gradle).



> @MohitMaliDeveloper How to you compute the second number? In a real release it should be computer _before_ releasing (usually the build number is computed by Gradle).

hi @kelson42 , that number needs to update manually once we publish the build , right now on PR the versioncode is of 3.5.0 , which is already published.

**Comment by kelson42** [comment]
@MohitMaliFtechiz How do you do that considering that you should ideally tag and publish after having updating that file. Looks like that havibg this int git might not be the best idea. Maybe the release process cozkd update a wiki page?

**Comment by MohitMaliFtechiz** [comment]
> like that havibg this int git might no
We can get this number any time during development build and we can update it just before release and tag of 3.6.0

**Comment by kelson42** [comment]
@MohitMaliDeveloper This was my question 5 days ago: How to you compute the second number concretly?

**Comment by MohitMaliFtechiz** [comment]
> 

hi @kelson42 , Its being generate by using this function


```

ext {
  set("versionMajor", 3)
  set("versionMinor", 5)
  set("versionPatch", 0)
}

fun generateVersionCode() =
  20 * 10000 +
    ext["versionMajor"] as Int * 10000 +
    ext["versionMinor"] as Int * 100 +
    ext["versionPatch"] as Int
```

Yes we can include this by calculating it on CONTRIBUTING.md

**Comment by kelson42** [comment]
@MohitMaliDeveloper I don't have a gradle parser in my mind. If we let devs doing that manually, they will do errors. This is why I propose to let `gradle` do that and generate the file itself in the wiki at release time. Wouldn't that be better? If this is too complicated (which I doubt), then we should probably create a small program on the command line making this computation, so a developer could launch it and avoid an error.

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliDeveloper I don't have a gradle parser in my mind. If we let devs doing that manually, they will do errors. This is why I propose to let `gradle` do that and generate the file itself in the wiki at release time. Wouldn't that be better? If this is too complicated (which I doubt), then we should probably create a small program on the command line making this computation, so a developer could launch it and avoid an error.

ok @kelson42 , let me check how we can do this.

**Review by kelson42 — APPROVED** [review]

**Review by gouri-panda — APPROVED** [review]

**Pull request merged**
