### PR TITLE
Localisation updates from https://translatewiki.net.

### PR DESCRIPTION
**Pull request by translatewiki**
Translation updates

### CODE REVIEW

**Review by MohitMaliFtechiz — APPROVED** [review]
approved

**Comment by kelson42** [comment]
@MohitMaliFtechiz I don't understant what is going on here. You fix something but you don't approve the PR... so I don't merge it and then your fix is erase three days after!

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz I don't understant what is going on here. You fix something but you don't approve the PR... so I don't merge it and then your fix is erase three days after!

Hi @kelson42 , I did approved the next days seems like @translatewiki force pushed over the changes .

**Comment by kelson42** [comment]
@MohitMaliFtechiz Next time, please just merge this PR. I have no problem if you merge the PR of translatewiki, once they are OK. You can come back to your last version (working), force push and merge.

**Review by MohitMaliFtechiz — APPROVED** [review]

**Pull request merged**
