### PR TITLE
RecentSearchDao.java converted to kotlin

### PR DESCRIPTION
**Pull request by Rishavgupta12345**
Fixes #

**Screenshots** 

the java file is completely deleted and converted into KOTLIN file under issue #1826

### CODE REVIEW

**Comment by kelson42** [comment]
@Rishavgupta12345 Any feedback?

**Comment by kelson42** [comment]
@Rishavgupta12345 Any feedback, without conpleting this PR we will have to close it.

**Comment by cdhiraj40** [comment]
> @Rishavgupta12345 Any feedback, without conpleting this PR we will have to close it.

if no response comes can I make a PR and complete the work?

**Comment by kelson42** [comment]
@cdhiraj40 yes, please.

**Comment by cdhiraj40** [comment]
> @cdhiraj40 yes, please.

sure will make a new PR soon :)

**Pull request closed without merging**
