### PR TITLE
Hide Keyboard when Scrolling in OnlineLibraryFragment/PagerFragment

### LINKED ISSUE #2717: Hide Keyboard when Scrolling in OnlineLibraryFragment/PagerFragment
**Is your feature request related to a problem? Please describe.**
In  OnlineLibraryFragment  & PagerFragment  while scrolling the keyboard just stays there and takes so much space of the page
which in my opinion isn't a great experience, its better if we scroll and the keyboard goes away :)

**Describe the solution you'd like**
I will addOnScrollListener to the recycler view so everytime we scroll the keyboard gets hidden

**Describe alternatives you've considered**
if we use a touch listener, then the keyboard hiding code is called multiple times each second while scrolling, which is not efficient.

**Additional context**
Before my approach 

https://user-images.githubusercontent.com/75211982/137470164-0d79d9d4-6856-4956-88b2-d8fcdc72a653.mp4

After my approach 

https://user-images.githubusercontent.com/75211982/137470182-efae0cbd-4e29-42df-bff1-d60632b8363f.mp4

### PR DESCRIPTION
**Pull request by cdhiraj40**
Fixes #2717

**Screenshots** 

https://user-images.githubusercontent.com/75211982/137470182-efae0cbd-4e29-42df-bff1-d60632b8363f.mp4

### CODE REVIEW

**Comment by cdhiraj40** [comment]
@gouri-panda I have done the requested changes
as I talked earlier about editText(searchView) having focus, even if we closeKeyboardonScroll but when the phone/the screen closed and opened  as it (editText) still has a focus
 the keyboard opens/closes on its own and sometimes just stay open
 
 possible solution: clear focus from search view or give focus to the recycler view.

**Comment by gouri-panda** [comment]
@cdhiraj40 Sorry for the late reply.
> give focus to the recycler view.

I'm not sure what are you talking about. can you elaborate a little more?

**Comment by cdhiraj40** [comment]
> @cdhiraj40 Sorry for the late reply.
> 
> > give focus to the recycler view.
> 
> I'm not sure what are you talking about. can you elaborate a little more?

when we are scrolling then focus is not totally going to recycler view, edit view(search) still has the focus
so if you turn off screen and open again you will see keyboard opening(for search as it has focus) and close again or sometimes just stays open

**Comment by gouri-panda** [comment]
Remove the focus completely.

**Comment by cdhiraj40** [comment]
> Remove the focus completely.



> > @cdhiraj40 Sorry for the late reply.
> > > give focus to the recycler view.
> > 
> > 
> > I'm not sure what are you talking about. can you elaborate a little more?
> 
> when we are scrolling then focus is not totally going to recycler view, edit view(search) still has the focus so if you turn off screen and open again you will see keyboard opening(for search as it has focus) and close again or sometimes just stays open

@gouri-panda seems like this is normal behavior as it was earlier too without close keyboard(I checked) but if you would still like me to remove focus from search
I can do `` libraryList.requestFocus() `` so on touch recyclerview will get the focus :)

**Comment by kelson42** [comment]
@gouri-panda @cdhiraj40 Any chance we can merge this before I release 3.4.6?

**Comment by cdhiraj40** [comment]
> @gouri-panda @cdhiraj40 Any chance we can merge this before I release 3.4.6? 
we can sure as the work is done and seems like the behavior which I talked about is pretty normal 
>@cdhiraj40 Please rebase on origin: develop.
sure

**Comment by cdhiraj40** [comment]
> @gouri-panda @cdhiraj40 Any chance we can merge this before I release 3.4.6? @cdhiraj40 Please rebase on origin:develop.

we can sure as the work is done and seems like the behavior which I talked about is pretty normal
sure I will rebase

**Comment by cdhiraj40** [comment]
> @cdhiraj40 You made a merge, not a rebase... which created a really dirty git log history.

oh sorry my bad, can you tell me how to resolve this or should I make a new PR?

**Comment by kelson42** [comment]
@cdhiraj40 You can make a new PR, but you should be able to do it on this PR. See https://medium.com/@topspinj/how-to-git-rebase-into-a-forked-repo-c9f05e821c8a. In worse case, if your PR revision log is a mess, keep track of your commit ids, make a git reset and cherry-pick again your few commits one by one.

**Comment by cdhiraj40** [comment]
> PR revision log

Sorry but I am still having some problems, I did understand how to do ``git rebase``, thanks for it I will sure use it properly next time but for now I will make a new PR and get this done quick, thanks :)

**Pull request closed without merging**
