### PR TITLE
Remove the need for storage permissions

### LINKED ISSUE #3265: Storage permissions are unnecessarily required
**Describe the bug**

Whenever an app refuses to work unless I give it storage permissions, I always give it a 1-star review on Google Play. Open source apps I compile from source are an exception, but I still don't like that. This is a privacy concern after one of my apps scanned my entire storage and tried to upload everything. Storage permissions are unnecessary for reading user-selected files on modern Android.

**Expected behavior**

Kiwix-android should not:
- ask for
- declare in AndroidManifest.xml
- mention in any documentation
- require
- use

any storage permissions.

When I'm using the app, it shouldn't even make me think of storage permissions. Please use modern Android APIs like SAF and `Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION`. I know this is possible because my own apps never ask for storage permissions. An example of an app I ported to SAF is https://github.com/danielzgtg/DeepSpeech-examples/blob/33f58a39a5f1005ac1e7e1a6efb685c0dce12d2d/android_mic_streaming/app/src/main/java/org/deepspeechdemo/LoadFilesActivity.kt .

**Steps to reproduce the behavior:**
1. Install Kiwix
2. Open Android Settings
3. Open "Privacy"
4. Open "Permissions manager"
5. Open "Files"
6. Open "See more apps that can access all files"
7. Tap "Kiwix"
8. Notice that this page exists

**Screenshots**

This screen shouldn't exist:

Screenshot_20230313-202753_Settings

**Environment**
- Version of Kiwix Android : 3.6.0
- Device : OnePlus 7 Pro
- OS version : Android 13 crDroid 9.2

### PR DESCRIPTION
**Pull request by danielzgtg**
Fixes #3265 

# What works

- Opening ZIMs
- Searching articles
- Reading articles
- All without any storage {permissions in settings, popups, toasts, privacy concerns, and annoyances}

# What doesn't work and needs to be readded

- Deleting files
- Is-zim-file detection
- Scanning for ZIMs. I will readd this by allowing the user to select and restrict the folder that they want Kiwix to scan
- Error handling
- Investigate whether file descriptor is already closed or whether I need to close it?
- Downloading
- Adding notes
- Clearing notes
- Selecting notes folder
- Undo close tab
- Database migration
- Multipart zims

# Removed as obsolete

- File transfer. (Android has this built-in)
- Storage available space checking. I might preallocate the ZIM instead, as that might help with fragmentation as well. With SAF, you can't and shouldn't be sure which drive the file is stored on, or even if it's a real filesystem compared to a cloud folder
- That infamous 4GB file thing
- Selecting storage devices. I might prompt the user using SAF before downloading each file

# Before

Users had to give kiwix-android the storage permission or else ZIMs could not be opened. I don't like doing so for privacy. Users also experienced bugs with granting that permission, like endless loops.

# After

Kiwix-android looks the same. You just don't need to take the time to grant the storage permission anymore.

**Screenshots** 

https://user-images.githubusercontent.com/25646384/224858456-ee784863-281b-46bc-80c2-7adca57121cf.mp4

This PR is nowhere near done. It might take 2 months to finish.

### CODE REVIEW

**Comment by kelson42** [comment]
@danielzgtg Considering the amount of regressions (so far) in this PR, I hardly see how we shozl/could consider it. If you plan to remove features, then first is to annouce which ones so a discussion can take place before any implementation. Otherwise glad to consider your proposal, but it should be without regression.

If you can make your case with smaller PR, I recommend it. Better smaller incremental PR than a big one.

**Comment by danielzgtg** [comment]
April was exam month. At least for the start of May I have a lot of paperwork to fill out for work. I hope to finish this PR by the end of June if I work on weekends

**Comment by kelson42** [comment]
@danielzgtg Hi, I hope you have been able to move forward with your other tasks? We have started to work on `3.8.0` and it would be now a good time to move forward on this PR. Do you still plan to continue it or should I close it?

**Comment by Jaifroid** [comment]
When I run this PR in Android Studio, it builds fine, the app opens fine, I can attempt to pick a pre-downloaded file from the Downloads directory, but then the app reports that the archive is not a valid ZIM file. I tried three different archives.

**Comment by Jaifroid** [comment]
I also tried putting my files in a `MyZims` directory, with the same outcome, they are not recognized as valid ZIM files. I checked the files by opening them successfully in the PWA app on the same virtual Android device, and the files open fine in the PWA. Strange.

**Pull request closed without merging**
