### PR TITLE
#2721 launch screen icon updated

### LINKED ISSUE #2721: Update logo on app launch screen
For some reason the old logo is still showing when opening the app:
Screenshot_20211020-142826

The current version of our logo can be found here: https://commons.wikimedia.org/wiki/File:Logo-kiwix-vertical.svg (or [here](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Logo-kiwix-vertical.svg/512px-Logo-kiwix-vertical.svg.png) for the png)

### PR DESCRIPTION
**Pull request by AdiAr11**
Fixes #2721 
Updated the launch screen logo for both light and dark mode

### CODE REVIEW

**Comment by gouri-panda** [comment]
@AdiAr11 Just a small change, rebase the commits then we are good to go!

**Comment by AdiAr11** [comment]
> @AdiAr11 Just a small change, rebase the commits then we are good to go!

sure, I'll do that

**Comment by gouri-panda** [comment]
@AdiAr11 Do you need any help here? Please feel free to ask :)

**Comment by AdiAr11** [comment]
@gouri-panda I'm really sorry i got busy with college work I totally forgot.

**Comment by kelson42** [comment]
@AdiAr11 You did a merge of master in your branch. This is not a rebase.

**Pull request merged**
