### PR TITLE
Fixed: Unable to render homepage of "Klimawandel".

### LINKED ISSUE #3966: [REGRESSION] Unable to render homepage of "Klimawandel"
... and this freezes the app!

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #3966 

* The issue was that we were writing the content on the IO thread using a coroutine, which was called from a `suspend` function. The function was suspended while loading the content, causing the `PipedOutputStream` to be flushed prematurely and resulting in the failure to render the remaining data.
* To fix this, we removed the content rendering from the coroutine and are now using `Completable` to render the content on the IO thread.
* Added instrumentation test case for testing whether the full page content is properly loaded or not, and if not loaded it will fail the test case, and we will avoid this type of rendering issue in the future. For this test case we are using [wikipedia_fr_climate_change_mini](https://download.kiwix.org/zim/wikipedia_fr_climate_change_mini.zim) zim file.

https://github.com/user-attachments/assets/a74d96a9-98ba-4df4-86b5-d56e37a265c2

### CODE REVIEW

**Comment by kelson42** [comment]
@MohitMaliFtechiz We need an airomated est to identify such a massive loading problem.

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz We need an airomated est to identify such a massive loading problem.

@kelson42 Yes, I am writing the automated test for this type of problem. Our current testing zim files are rendering correctly in the application. There is a small zim file of "Klimawandel" https://download.kiwix.org/zim/wikipedia/wikipedia_de_climate_change_nopic_2024-06.zim in which I am able to reproduce this issue so I am using this zim file for testing (if there is any other small zim file available then please let me know).

**Comment by kelson42** [comment]
@MohitMaliFtechiz CI does not pass

**Comment by MohitMaliFtechiz** [comment]
@kelson42 Now CI is green.

**Pull request merged**
