### PR TITLE
Convert KiwixDatabaseTest.java into kotlin

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes: #3044 
Parent Issue: #1826 

Converted KiwixDatabaseTest.java into kotlin

### CODE REVIEW

**Comment by gouri-panda** [comment]
@MohitMaliDeveloper I think this class will refactor fully in the upcoming migration to Room. So I think  we shouldn't focus on this any more. I will right a new class or fully refactored code. What do you think?

**Comment by MohitMaliFtechiz** [comment]
> 

hi @gouri-panda ,

yes this class will refactor in migration to Room. so for now we can ignore this and focus on other PR.

**Comment by gouri-panda** [comment]
@MohitMaliDeveloper @kelson42 Should we close the ticket?

**Comment by kelson42** [comment]
What is the purpose of this class? Keep in mind that we will still have to keep most of that code to allow data migration during a few releases.

**Comment by kelson42** [comment]
@gouri-panda Thinking twice about it, lets review and merge this. We will have to deal with KiwixDatabase code for the next few releases, so better have it tested properly in Kotlin.

**Review by gouri-panda — DISMISSED** [review]

**Comment by kelson42** [comment]
@MohitMaliFtechiz @gouri-panda The CI does not pass, please don’t request review and don’t approve as long as the automated tests are all OK.

**Comment by kelson42** [comment]
@MohitMaliDeveloper Can you please secure the test are OK and the CI passes?

**Comment by gouri-panda** [comment]
@MohitMaliFtechiz It keeps failing on API 30.

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz It keeps failing on API 30.

hi @gouri-panda ,

i have check the reason for test failure on android 30 and i found i have already fixed this test failure in  #2944  but that PR is not merged yet. this is also reason for Nightly failure on different api level. i have placed a fix for this issue, first we should merged this PR so we can check Nightly and other PR's as well.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Please fix it here, this fix has nothing to do with Android 13 anyway

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz Please fix it here, this fix has nothing to do with Android 13 anyway

Already placed the fix. CI is green now.

**Pull request merged**
