### PR TITLE
Add unit tests for HistoryDao.kt

### LINKED ISSUE #1827: Add more Unit Tests
**Is your feature request related to a problem? Please describe.**
Kiwix's coverage is at 33%~ right now and we want that to be a lot higher. If you want to contribute to the project but are finding it diffcult to find a suitable ticket of a manageable size then this is for you!

**Describe the solution you'd like**
Comment here that you want to test a class (I recommend starting with small ones) with the class name to claim it. Then make a ticket and start working on it. Use `ctrl+shift+t` to automatically create the test class. You can check our [codecov report](https://codecov.io/gh/kiwix/kiwix-android) to find classes without tests, `ctrl+shift+t` also navigates to a test class if it already exists.

**Additional context**
Our unit testing strategy is based on [this article](https://phauer.com/2018/best-practices-unit-testing-kotlin/) which is a recap of KotlinConf talk on the topic, linked in the article. [Mockk](https://mockk.io/) is the one of the more important libraries to know about and that link has several articles on the topic. As always kiwix team members can help if you open a PR in Draft.

### PR DESCRIPTION
**Pull request by bhaktideshmukh**
Fixes #1827 

**Screenshots**

### CODE REVIEW

**Comment by abdulwd** [comment]
@bhaktideshmukh can you check why the coverage reporting failed?

**Comment by bhaktideshmukh** [comment]
> @bhaktideshmukh can you check why the coverage reporting failed?

I was not able to find the error from the logs. Can you share the command to test it locally?

**Comment by abdulwd** [comment]
@gouri-panda @s-ayush2903 can you help here?

**Review by s-ayush2903 — COMMENTED** [review]
I would say the testing logic is incorrect. 
See: [info from ci run](https://github.com/kiwix/kiwix-android/pull/2643/checks?check_run_id=2418391694#step:5:6352)
image

To reproduce the failure locally, simply run this specific test in android studio.

**Comment by bhaktideshmukh** [comment]
> I would say the testing logic is incorrect.
> See: [info from ci run](https://github.com/kiwix/kiwix-android/pull/2643/checks?check_run_id=2418391694#step:5:6352)
> image
> 
> To reproduce the failure locally, simply run this specific test in android studio.

kiwix
sir its working properly in my android studio

**Comment by kelson42** [comment]
Without fix, I will unfortunatly have to fix this PR

**Comment by abdulwd** [comment]
@bhaktideshmukh can you try running all the unit tests together locally and see if you're able to reproduce?

**Comment by bhaktideshmukh** [comment]
@kelson42 @abdulwd Can you please look to my patch once again

**Review by abdulwd — APPROVED** [review]

**Comment by abdulwd** [comment]
@bhaktideshmukh Thanks for the contribution! 💪

**Pull request merged**
