### PR TITLE
#2215 updated to correct links in contributing.md

### LINKED ISSUE #2215: DESIGN and STRING_RESOURCES both link to the edit instead of the blob page.
**Describe the bug**

Links to DESIGN.md and STRING_RESOURCES.md both link to the edit page for the respective pages. 

**Expected behavior**

They should link to the readable pages. 
* STRING_RESOURCES.md → https://github.com/kiwix/kiwix-android/blob/develop/STRING_RESOURCES.md
* DESIGN.md → https://github.com/kiwix/kiwix-android/blob/develop/DESIGN.md

### PR DESCRIPTION
**Pull request by Frans-Lukas**
Fixes #2215 

Updated links.

### CODE REVIEW

**Comment by s-ayush2903** [comment]
Hey, @Frans-Lukas no offence but there is similar problem in the https://github.com/kiwix/kiwix-android/blob/develop/CONTRIBUTING.md#continous-integration section of contribution.md where the url of `.travis.yml` doesn't work, can you please check that out or should i fix that in a new ticket?

**Comment by Frans-Lukas** [comment]
Nice catch. I can add it to this active pr. Do you know where it's supposed to link to?

**Comment by s-ayush2903** [comment]
I'm not pretty sure as we don't have an explicitly defined `travis.yml` but following the context of that particular section of _[CI](https://github.com/kiwix/kiwix-android/blob/develop/CONTRIBUTING.md#continous-integration)_ in _Contributing.md_ it should either be [PullRequest Jobs](https://github.com/kiwix/kiwix-android/blob/develop/.github/workflows/pull_request.yml) or the complete [workflow](https://github.com/kiwix/kiwix-android/tree/develop/.github/workflows).

**Comment by Frans-Lukas** [comment]
Ok, thanks! @macgills @kelson42

**Comment by macgills** [comment]
Link to the workflows directory, that has all our job configs

**Pull request merged**
