### PR TITLE
Localisation updates from https://translatewiki.net.

### PR DESCRIPTION
**Pull request by translatewiki**
Translation updates

### CODE REVIEW

**Comment by kelson42** [comment]
@gouri-panda Shoukd we merge this?

**Comment by gouri-panda** [comment]
@kelson42 Same static analysis error.

**Comment by kelson42** [comment]
@gouri-panda OK, but this is a problem with the CI right? Does the rest looks good?

**Review by gouri-panda — DISMISSED** [review]

**Comment by kelson42** [comment]
@gouri-panda Coukd we finally merge this PR?

**Review by gouri-panda — APPROVED** [review]

**Pull request merged**
