### PR TITLE
changed web server java class to web server Kotlin file

### PR DESCRIPTION
**Pull request by markZuckerberg2**
Changed web server java class into Kotlin

### CODE REVIEW

**Review by gouri-panda — CHANGES_REQUESTED** [review]
@markZuckerberg2 Some #2624 commits are here. Can you remove them, please?

**Comment by markZuckerberg2** [comment]
> @markZuckerberg2 Some #2624 commits are here. Can you remove them, please?

😢so sorry @gouri-panda. I will fix this.

**Comment by gouri-panda** [comment]
@markZuckerberg2 Go to the Android studio then follow these steps
1. Open git windows
2. Select your branch
3. Right-click those commits that you don't want
4. Click revert commit
5. Add commit to the branch
6. Push that commit to the appropriate branch

**Comment by markZuckerberg2** [comment]
@gouri-panda I am closing this issue. It would be much easy if I will create a new brand PR.

**Pull request closed without merging**
