### PR TITLE
Convert NetworkLanguageDao.java into kotlin

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes: #3029 
Parent Issue: #1826 

Converted NetworkLanguageDao.java into kotlin

### CODE REVIEW

**Comment by kelson42** [comment]
@gouri-panda Can you please review?

**Comment by gouri-panda** [comment]
After `Room` implementation we don't need this anymore.

**Comment by kelson42** [comment]
@gouri-panda This is use to store what kind of data exactly?

**Comment by gouri-panda** [comment]
This class is responsible for accessing(filtering) Languages from the database to download selected languages for downloading zim files. 
 This is the table [entity](https://github.com/kiwix/kiwix-android/blob/develop/core/src/main/java/org/kiwix/kiwixmobile/core/data/local/entity/NetworkLanguageSpec.kt).

**Comment by kelson42** [comment]
@gouri-panda You are sure you won’t need this to secure data migration from objectbox to room?

**Comment by kelson42** [comment]
Why you woukd recreate a class to access object in objectbox database?

**Comment by gouri-panda** [comment]
Room will require separate implementation.

**Comment by kelson42** [comment]
@gouri-panda This is clear, but how do you want to handle the migration from ObjectBox to Room, without having the implementation twice in kiwix-Android (one for ObjectBox and one for Room)?

**Comment by kelson42** [comment]
@gouri-panda so this class allow to write/read the list of languages the user wants to get ZIM files (in these languages)? So it is just something like a small list of language codes?

**Comment by gouri-panda** [comment]
>
@gouri-panda so this class allow to write/read the list of languages the user wants to get ZIM files (in these languages)? So it is just something like a small list of language codes?

Yes @kelson42

**Comment by kelson42** [comment]
So, it it basically a list like "eng,fra,deu"? Why this is not store in the android app preferences?

**Comment by gouri-panda** [comment]
@kelson42 Android preference only allow us to store small number of sets. More complex data forms should store in the sqldatabase.

**Comment by kelson42** [comment]
@gouri-panda a list of language codes is not a complex data.

**Comment by kelson42** [comment]
@gouri-panda OK, it would have been helpful to get this information earlier in the discussion. So, at least, we have absolutly to migrate from ObjectBox to Room is the list of `enabled` languages. The overall list of languages with their respective number of books might be better recalculate from the the online feed. Right? So we need to to keep that class, you understand. Ths is why we need to merge this PR.

**Comment by gouri-panda** [comment]
@kelson42 ok. I'll keep this in mind in future :) But we are changing the mechanism in Room on how to access these data.

**Comment by kelson42** [comment]
@gouri-panda OK, it does not have to be done the same way with Room indeed.

**Review by gouri-panda — APPROVED** [review]

**Pull request merged**
