### PR TITLE
Fixed Navigation Bar Issue

### LINKED ISSUE #442: text being cut on Help screen
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request

### Step 1: Are you ready to report ?
   - Your issue may already be reported! Please search on the [issue track](../) before creating one.
   - [x] I have test with the last (dev) version of the software?  ( If not, and if possible, run your test again with the most recent version available.)

### Step 2 : What is your environment ?
  * browser / app : App
  * version of the software you use :  2.3 Build 55
  * device / operating system : Android 7.0 (Samsung Galaxy S6)
  
### Step 3: Describe the problem:

  * What do you obtain? A copy of the error message or a screenshot is always useful
The text at the bottom of the help screen is being cut.
this is the screenshot of the bottom of the app:
image
while this is the one that should actually be displayed:
image

  * When does this occur? 

#### Steps to reproduce:

  1. navigate to the bottom of the help screen
  
  * What should be the behaviour from your point of view? How do you expect the service to work?

The text should not be cut and the card ending should be properly displayed

### Step 4 (optional) : Other Comments:
  * What is the context of this ticket? If not obvious, explain why you need to do this.
 
  * If you have an idea about the technical background of the ticket, please share it.
  
  
#### Feature Description

Please describe the feature you want to add to the project.

### PR DESCRIPTION
**Pull request by harsh-2711**
Fixes #442 

Changes: Navigation bar(available on 18:9 display phones) is made transparent and the layout is changed to full screen.

Screenshots/GIF for the change: 
screenshot_20180226-175436 1

### CODE REVIEW

**Comment by harsh-2711** [comment]
@brijeshshah13  @mhutti1  Please review this PR

**Comment by harsh-2711** [comment]
@brijeshshah13 Can you please review it now. Travis CI build passed successfully.

**Comment by brijeshshah13** [comment]
@harsh-2711 How does this solve the problem of text being cut off on Help screen?

**Comment by harsh-2711** [comment]
@brijeshshah13  Now as the navigation bar is transparent, the greetings text can be seen...

**Comment by brijeshshah13** [comment]
@mhutti1 @harsh-2711 I don't think that was the behavior to be implemented. The approach was to find and solve the hindrance which is causing the text being cut off on the Help screen. Wasn't it?

**Comment by harsh-2711** [comment]
The navigation bar was only the hindrance. So, I made it transparent. Other way possible is to add extra space after the last greeting message but that would result in excess space for users having no on-screen navigation bar

**Comment by rashiq** [comment]
Imo this is a hack. And we should rather change the help screen than do it like this. And since we all seem to agree on this I'd like to close this.

**Pull request closed without merging**
