### PR TITLE
Room migration of languages

### LINKED ISSUE #3112: Room migration of Languages
This is a subtask for #3102 . Write migration test and new database test for LanguageEntity.

Should be done:
* A kind of generic and abstract accessor to access Room data
* Secure the Room DB is created properly at start (if it is not easy to create on the fly) if necessary (first installation or migration context)
* The data structure and accessor to the languages (based on what exists in ObjectBox)
* Link with the existing code around the languages(disconnect this from ObjectBox)
* Write the automated tests (Unit tests and maybe one UI test) for that new Room code (adapt what exists for ObjectBox)
* Write the migration function (for the data) from the ObjectBox language DB to the Room DB
* Write automated tests for that migration function
* LanguageEntity (Responsible for storing all language lists that user can search) https://github.com/kiwix/kiwix-android/blob/e2c901bf22034ea891c29ce12bc5793df7eccf52/core/src/main/java/org/kiwix/kiwixmobile/core/dao/entities/LanguageEntity.kt

### PR DESCRIPTION
**Pull request by gouri-panda**
Fixes #3112 

- [x]  A kind of generic and abstract accessor to access Room data
- [x] Secure the Room DB is created properly at start (if it is not easy to create on the fly) if necessary (first installation or migration context)
- [x] The data structure and accessor to the languages (based on what exists in ObjectBox)
- [x] Link with the existing code around the languages (disconnect this from ObjectBox)
- [x] Write the automated tests (Unit tests and maybe one UI test) for that new Room code (adapt what exists for ObjectBox)

### CODE REVIEW

**Comment by MohitMaliFtechiz** [comment]
hi @gouri-panda , 
is this PR ready for review?

**Comment by gouri-panda** [comment]
@MohitMaliFtechiz Yes.

**Comment by MohitMaliFtechiz** [comment]
hi @gouri-panda , 
can you please rebase this PR on #3183. So we can get last review changes here as well.

**Comment by gouri-panda** [comment]
@MohitMaliFtechiz It would be easier to rebase if we merge #3111.

**Comment by MohitMaliFtechiz** [comment]
hi @gouri-panda ,

I have tested this PR , I have one minor issue , after migration its lost previous selected languages its only check English after migrations.

**Comment by gouri-panda** [comment]
@MohitMaliFtechiz previously We didn't save the languages while migrating squiddb to objectbox. But we should do it now. I have added both migrate functions and tests as well.

**Review by MohitMaliFtechiz — DISMISSED** [review]
Hi @gouri-panda ,
Thanks. We should merge this after https://github.com/kiwix/kiwix-android/pull/3183

**Comment by kelson42** [comment]
Probably better to implement #2689 in place

**Pull request closed without merging**
