### PR TITLE
Localisation updates from https://translatewiki.net.

### LINKED ISSUE #1605: Document translatable messages in translatewiki
**Describe the bug**

Kiwix is localized in translatewiki. About 250 translatable message are currently not documented, and this makes localization more difficult. Every message, short and long, must be documented.

**Expected behavior**

The list of "untranslated" message documentation items must be empty. The list is available here:
https://translatewiki.net/wiki/Special:Translate?filter=%21translated&action=translate&language=qqq&group=kiwix

**Steps to reproduce the behavior:**
Click https://translatewiki.net/wiki/Special:Translate?filter=%21translated&action=translate&language=qqq&group=kiwix . The list has about 250 items.

Somebody who is familiar with how the software works must have a translatewiki account, click each row in this list and add a short explanation in English about each message—where does it appear, and what is its function.

**Screenshots**

**Environment**
(Not relevant. It's a problem in the source code and in the localization workflow.)

**Logs**

### PR DESCRIPTION
**Pull request by translatewiki**
Translation updates

Fixes #1605

### CODE REVIEW

**Comment by kelson42** [comment]
@MohitMaliDeveloper Beside the `qqq` language we are still expecting, all looks good?

**Comment by MohitMaliFtechiz** [comment]
@kelson42 , we got an update from TW for `qqq` https://github.com/kiwix/kiwix-android/pull/3281/files#diff-c1d6a2c40103f6a634a01a49b2f1e66d2410aee714916a54c0928bb6d0ae2001 apart from that TW update looks good.

**Comment by kelson42** [comment]
@MohitMaliFtechiz so why not approving the PR?

**Review by MohitMaliFtechiz — APPROVED** [review]
@kelson42 , It's LGTM.

**Pull request merged**
