### PR TITLE
Fixed: The donation popup does not look well in tablet.

### LINKED ISSUE #3736: Add donation popup
[Signal](../../../../signalapp) has a donation prompt that appears every three months or so at the bottom of its android app. Nothing fancy (see text below - it's in French but the gist of it is `Donate today / Signal needs your help` with the choice button being _remind me later_ of _donate_)

There is already a static feature in the settings, so this is in addition to the latter.

Signal has a sophisticated donation funnel that allows in-app payments, but at this stage a link to support.kiwix.org would already be good

donation_prompt

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #3736

The donation popup was not looking good on tablets, so we have improved the design of the donation popup for tablets.

| Tablet landscape  | Tablet portrait |
| ------------- | ------------- |
| TabletDayModeLandscape | TabletDayModePotrait | 

| Tablet landscape in Dark mode | Tablet portrait in Dark mode |
| ------------- | ------------- |
| TabletDarkModeLandscape | TabletDarkMode |

In normal devices
Screenshot from 2024-10-07 14-25-36

### CODE REVIEW

**Comment by kelson42** [comment]
@Popolechien To me it still does not look good for tablets. I really wonder if it would not be better to make a standard Android notification in place?

**Comment by Popolechien** [comment]
@kelson42 Do you have a screenshot? Can we tell from the playstore the percentage of tablets onto which Kiwix is installed?

**Comment by kelson42** [comment]
@MohitMaliFtechiz Do you have stats about phone vs. tablet usage? This is actually an interesting question!

**Comment by MohitMaliFtechiz** [comment]
@kelson42 Our application is installed on the 4%(5,974 device) on tablets, and 96% on mobile phone.

Screenshot from 2024-10-02 11-57-29

**Comment by Popolechien** [comment]
Thanks @MohitMaliDeveloper. That would amount to anywhere between 3-60 donations, ie $100-$1,800 in total (and tbh I don't really believe in a 0.1% (upper range) donation rate). 

@kelson42 from the screenshot at the top of this PR I'd say the prompt works well enough and in any case I'd favour rolling it out to see what happens.

**Comment by kelson42** [comment]
@MohitMaliFtechiz All these boxes are too large. I suspect the best approach is to limit the max width to a kind of width like we have on a phone. Please also put screenshots in dark mode.

**Comment by MohitMaliFtechiz** [comment]
@kelson42 I have made the changes as you requested and updated the PR description with screenshots.

**Pull request merged**
