### PR TITLE
Refactor: Explicitly include codestyle for XML files

### LINKED ISSUE #519: Explicitly include codestyle for XML files
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request

#### Feature Description

Noticing that almost all the PR's are facing the Indentation issue for the XML files, I think it would be great if we could specify that `kiwix` follows `2dp` for the `Indent` and `Continuous Indent` values.

We can even provide the following screenshot in the `codestyle.md` file to indicate the same.

indent_final

After changing the values, we can simply `select the files we want to indent`, `right click` -> `Reformat Code` -> Check `Rearrange entries` -> `OK`. And just like that all the future indentation issues will be prevented saving a heck lot of time while reviewing.

@mhutti1 @kelson42 @srv-twry Please review.

### PR DESCRIPTION
**Pull request by brijeshshah13**
Fixes #519
 
Changes: Included codestyle guidelines to be followed for XML files.

Screenshots/GIF for the change: N/A

### CODE REVIEW

**Comment by brijeshshah13** [comment]
@mhutti1 Travis build is failing as per the discussion at #518. However, the PR is good to be merged.

**Comment by mhutti1** [comment]
Yeah one of the GSoC students might have a look at the randomly failing travis its about 1/10 but still really annoying.

**Comment by brijeshshah13** [comment]
@mhutti1 Sadly, I don't think there is any work around for this as this isn't an issue with our travis script or travis service itself. We will have to wait for the release of Android Plugin version 3.0.1.

**Comment by mhutti1** [comment]
@brijeshshah13 You are misunderstanding the issue as you don't yet have access to our remote build system where these tests are being run. 1/10 times one of the tests fails on our device this has nothing to do with the warning that you are referencing.

**Comment by brijeshshah13** [comment]
@mhutti1 Oh, alright. Got it 👍

**Pull request merged**
