### PR TITLE
Convert BookmarksDao.java to kotlin

### LINKED ISSUE #2997: Convert BookmarksDao.java to kotlin
Parent Issue: #1826

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #2997 
Parent Issue: #1826 

Converted BookmarksDao.java to kotlin

### CODE REVIEW

**Comment by gouri-panda** [comment]
This class too. We won't need anymore after the Room.

**Comment by kelson42** [comment]
We should create a "Room" project and move this ticket there. I woukd keep them open until a ticket/PR removes the code. Does that sounds good?

**Comment by gouri-panda** [comment]
Ok @kelson42. Sounds good to me!

**Comment by gouri-panda** [comment]
Ok @kelson42. Sounds good to me!

**Comment by gouri-panda** [comment]
Ok @kelson42. Sounds good to me!

**Comment by gouri-panda** [comment]
Ok @kelson42. Sounds good to me!

**Comment by gouri-panda** [comment]
Ok @kelson42. Sounds good to me!

**Comment by gouri-panda** [comment]
Ok @kelson42. Sounds good to me!

**Comment by kelson42** [comment]
See #3105 for the class BookmarksDao.java deletion request

**Review by gouri-panda — CHANGES_REQUESTED** [review]
@MohitMaliDeveloper At the beginning of the installation, it crashes on several occasions.

**Comment by MohitMaliFtechiz** [comment]
> 



> @MohitMaliDeveloper At the beginning of the installation, it crashes on several occasions.

hi @gouri-panda ,
I have try to install the APK, it successfully installed on my device also i have add some bookmarks that also successfully saved. so i'm unable to reproduce the crashes. can you please let me know where you are facing crashes in app and also please provide me the logs so i can debug it.

**Comment by gouri-panda** [comment]
@MohitMaliDeveloper If you freshly install the app, you can encounter the crash. Here are logs. Let me know if you need anything.
<details><summary> Logs </summary>

```
2022-11-17 15:11:53.108 23487-23818 AndroidRuntime          org.kiwix.kiwixmobile                E  FATAL EXCEPTION: RxCachedThreadScheduler-13
                                                                                                    Process: org.kiwix.kiwixmobile, PID: 23487
                                                                                                    io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.IllegalAccessError: Field 'org.kiwix.kiwixmobile.core.entity.LibraryNetworkEntity$Book.tags' is inaccessible to class 'org.kiwix.kiwixmobile.core.zim_manager.fileselect_view.adapter.BooksOnDiskListItem$BookOnDisk' (declaration of 'org.kiwix.kiwixmobile.core.zim_manager.fileselect_view.adapter.BooksOnDiskListItem$BookOnDisk' appears in /data/app/~~pcjRw-tcTUcWr2tQmLXd_A==/org.kiwix.kiwixmobile-4-VWlsCtUnWsEimCgGqmKg==/base.apk!classes11.dex)
                                                                                                    	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
                                                                                                    	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:69)
                                                                                                    	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                                                    	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)
                                                                                                    Caused by: java.lang.IllegalAccessError: Field 'org.kiwix.kiwixmobile.core.entity.LibraryNetworkEntity$Book.tags' is inaccessible to class 'org.kiwix.kiwixmobile.core.zim_manager.fileselect_view.adapter.BooksOnDiskListItem$BookOnDisk' (declaration of 'org.kiwix.kiwixmobile.core.zim_manager.fileselect_view.adapter.BooksOnDiskListItem$BookOnDisk' appears in /data/app/~~pcjRw-tcTUcWr2tQmLXd_A==/org.kiwix.kiwixmobile-4-VWlsCtUnWsEimCgGqmKg==/base.apk!classes11.dex)
                                                                                                    	at org.kiwix.kiwixmobile.core.zim_manager.fileselect_view.adapter.BooksOnDiskListItem$BookOnDisk.<init>(BooksOnDiskListItem.kt:47)
                                                                                                    	at org.kiwix.kiwixmobile.core.zim_manager.fileselect_view.adapter.BooksOnDiskListItem$BookOnDisk.<init>(BooksOnDiskListItem.kt:66)
                                                                                                    	at org.kiwix.kiwixmobile.core.StorageObserver.convertToBookOnDisk(StorageObserver.kt:53)
                                                                                                    	at org.kiwix.kiwixmobile.core.StorageObserver._get_booksOnFileSystem_$lambda-0(StorageObserver.kt:41)
                                                                                                    	at org.kiwix.kiwixmobile.core.StorageObserver.$r8$lambda$GdHqLldRNXLqIZ5ZbeFUQDsiNuo(Unknown Source:0)
                                                                                                    	at org.kiwix.kiwixmobile.core.StorageObserver$$ExternalSyntheticLambda1.apply(Unknown Source:4)
                                                                                                    	at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:106)
                                                                                                    	at io.reactivex.subscribers.SerializedSubscriber.onNext(SerializedSubscriber.java:100)
                                                                                                    	at io.reactivex.internal.operators.flowable.FlowableWithLatestFrom$WithLatestFromSubscriber.tryOnNext(FlowableWithLatestFrom.java:94)
                                                                                                    	at io.reactivex.internal.operators.flowable.FlowableWithLatestFrom$WithLatestFromSubscriber.onNext(FlowableWithLatestFrom.java:76)
                                                                                                    	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onNext(FlowableSubscribeOn.java:97)
                                                                                                    	at io.reactivex.internal.operators.flowable.FlowableCombineLatest$CombineLatestCoordinator.drainAsync(FlowableCombineLatest.java:374)
                                                                                                    	at io.reactivex.internal.operators.flowable.FlowableCombineLatest$CombineLatestCoordinator.drain(FlowableCombineLatest.java:406)
                                                                                                    	at io.reactivex.internal.operators.flowable.FlowableCombineLatest$CombineLatestCoordinator.innerValue(FlowableCombineLatest.java:250)
                                                                                                    	at io.reactivex.internal.operators.flowable.FlowableCombineLatest$CombineLatestInnerSubscriber.onNext(FlowableCombineLatest.java:521)
                                                                                                    	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onNext(FlowableSubscribeOn.java:97)
                                                                                                    	at io.reactivex.internal.subscriptions.DeferredScalarSubscription.complete(DeferredScalarSubscription.java:132)
2022-11-17 15:11:53.108 23487-23818 AndroidRuntime          org.kiwix.kiwixmobile                E  	at io.reactivex.internal.operators.flowable.FlowableFromCallable.subscribeActual(FlowableFromCallable.java:50)
                                                                                                    	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
                                                                                                    	at io.reactivex.Flowable.subscribe(Flowable.java:14882)
                                                                                                    	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
                                                                                                    	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
                                                                                                    	... 6 more
2022-11-17 15:11:53.139 23487-23818 Process                 org.kiwix.kiwixmobile                I  Sending signal. PID: 23487 SIG: 9
---------------------------- PROCESS ENDED (23487) for package org.kiwix.kiwixmobile ----------------------------
```
</details>

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliDeveloper If you freshly install the app, you can encounter the crash. Here are logs. Let me know if you need anything.
> 
> Logs
> ```
> 2022-11-17 15:11:53.108 23487-23818 AndroidRuntime          org.kiwix.kiwixmobile                E  FATAL EXCEPTION: RxCachedThreadScheduler-13
>                                                                                                     Process: org.kiwix.kiwixmobile, PID: 23487
>                                                                                                     io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.IllegalAccessError: Field 'org.kiwix.kiwixmobile.core.entity.LibraryNetworkEntity$Book.tags' is inaccessible to class 'org.kiwix.kiwixmobile.core.zim_manager.fileselect_view.adapter.BooksOnDiskListItem$BookOnDisk' (declaration of 'org.kiwix.kiwixmobile.core.zim_manager.fileselect_view.adapter.BooksOnDiskListItem$BookOnDisk' appears in /data/app/~~pcjRw-tcTUcWr2tQmLXd_A==/org.kiwix.kiwixmobile-4-VWlsCtUnWsEimCgGqmKg==/base.apk!classes11.dex)
>                                                                                                     	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
>                                                                                                     	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:69)
>                                                                                                     	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
>                                                                                                     	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>                                                                                                     	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
>                                                                                                     	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>                                                                                                     	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>                                                                                                     	at java.lang.Thread.run(Thread.java:923)
>                                                                                                     Caused by: java.lang.IllegalAccessError: Field 'org.kiwix.kiwixmobile.core.entity.LibraryNetworkEntity$Book.tags' is inaccessible to class 'org.kiwix.kiwixmobile.core.zim_manager.fileselect_view.adapter.BooksOnDiskListItem$BookOnDisk' (declaration of 'org.kiwix.kiwixmobile.core.zim_manager.fileselect_view.adapter.BooksOnDiskListItem$BookOnDisk' appears in /data/app/~~pcjRw-tcTUcWr2tQmLXd_A==/org.kiwix.kiwixmobile-4-VWlsCtUnWsEimCgGqmKg==/base.apk!classes11.dex)
>                                                                                                     	at org.kiwix.kiwixmobile.core.zim_manager.fileselect_view.adapter.BooksOnDiskListItem$BookOnDisk.<init>(BooksOnDiskListItem.kt:47)
>                                                                                                     	at org.kiwix.kiwixmobile.core.zim_manager.fileselect_view.adapter.BooksOnDiskListItem$BookOnDisk.<init>(BooksOnDiskListItem.kt:66)
>                                                                                                     	at org.kiwix.kiwixmobile.core.StorageObserver.convertToBookOnDisk(StorageObserver.kt:53)
>                                                                                                     	at org.kiwix.kiwixmobile.core.StorageObserver._get_booksOnFileSystem_$lambda-0(StorageObserver.kt:41)
>                                                                                                     	at org.kiwix.kiwixmobile.core.StorageObserver.$r8$lambda$GdHqLldRNXLqIZ5ZbeFUQDsiNuo(Unknown Source:0)
>                                                                                                     	at org.kiwix.kiwixmobile.core.StorageObserver$$ExternalSyntheticLambda1.apply(Unknown Source:4)
>                                                                                                     	at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:106)
>                                                                                                     	at io.reactivex.subscribers.SerializedSubscriber.onNext(SerializedSubscriber.java:100)
>                                                                                                     	at io.reactivex.internal.operators.flowable.FlowableWithLatestFrom$WithLatestFromSubscriber.tryOnNext(FlowableWithLatestFrom.java:94)
>                                                                                                     	at io.reactivex.internal.operators.flowable.FlowableWithLatestFrom$WithLatestFromSubscriber.onNext(FlowableWithLatestFrom.java:76)
>                                                                                                     	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onNext(FlowableSubscribeOn.java:97)
>                                                                                                     	at io.reactivex.internal.operators.flowable.FlowableCombineLatest$CombineLatestCoordinator.drainAsync(FlowableCombineLatest.java:374)
>                                                                                                     	at io.reactivex.internal.operators.flowable.FlowableCombineLatest$CombineLatestCoordinator.drain(FlowableCombineLatest.java:406)
>                                                                                                     	at io.reactivex.internal.operators.flowable.FlowableCombineLatest$CombineLatestCoordinator.innerValue(FlowableCombineLatest.java:250)
>                                                                                                     	at io.reactivex.internal.operators.flowable.FlowableCombineLatest$CombineLatestInnerSubscriber.onNext(FlowableCombineLatest.java:521)
>                                                                                                     	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onNext(FlowableSubscribeOn.java:97)
>                                                                                                     	at io.reactivex.internal.subscriptions.DeferredScalarSubscription.complete(DeferredScalarSubscription.java:132)
> 2022-11-17 15:11:53.108 23487-23818 AndroidRuntime          org.kiwix.kiwixmobile                E  	at io.reactivex.internal.operators.flowable.FlowableFromCallable.subscribeActual(FlowableFromCallable.java:50)
>                                                                                                     	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
>                                                                                                     	at io.reactivex.Flowable.subscribe(Flowable.java:14882)
>                                                                                                     	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
>                                                                                                     	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
>                                                                                                     	... 6 more
> 2022-11-17 15:11:53.139 23487-23818 Process                 org.kiwix.kiwixmobile                I  Sending signal. PID: 23487 SIG: 9
> ---------------------------- PROCESS ENDED (23487) for package org.kiwix.kiwixmobile ----------------------------
> ```

hi @gouri-panda  ,
i have tried with installing fresh app, but i'm still unable to reproduce the error. i'm using ```Redmi Note 9 (Android 11)```. According to these logs problem occurs in this line https://github.com/kiwix/kiwix-android/blob/ef545094a2c5ffa4c72358b42284b24042b15328/core/src/main/java/org/kiwix/kiwixmobile/core/zim_manager/fileselect_view/adapter/BooksOnDiskListItem.kt#L47

Can you please let me know which device you using.

**Comment by gouri-panda** [comment]
Yes sorry! It's Realme 7 ,api 30. I don't think it's related to device problem.

**Comment by MohitMaliFtechiz** [comment]
> Yes sorry! It's Realme 7 ,api 30. I don't think it's related to device problem.

hi @gouri-panda , Yes this is not device related problem. but i have tried with different zim files/devices and i'm not facing any crash issue or is there any spacial case or zim file that i'm missing here?. I'm using latest develop branch.

**Comment by gouri-panda** [comment]
@MohitMaliDeveloper I'm testing with this PR's beach. Here are the exact steps
1. Uninstall the app
2. Reinstall the app
3. Give all the necessary permissions
4. Wait for the search of the zim files in the device.

**Comment by MohitMaliFtechiz** [comment]
> 



> @MohitMaliDeveloper I'm testing with this PR's branch. Here are the exact steps
> 
> 1. Uninstall the app
> 2. Reinstall the app
> 3. Give all the necessary permissions
> 4. Wait for the search of the zim files in the device.

hi @gouri-panda ,
i have tried with the following steps but i'm unable to reproduce the crash. here you can see.

https://user-images.githubusercontent.com/34593983/202644752-399e8363-e762-4d39-b11c-7204bb71594d.mp4

**Comment by gouri-panda** [comment]
@MohitMaliDeveloper I don't know how to reproduce it on other devices but it seems to me that the crash is not small trivial. Please let me know how to help you to produce this on your device.

**Comment by kelson42** [comment]
@MohitMaliFtechiz @gouri-panda Last Kotlin PR. What is the way forward?

**Comment by gouri-panda** [comment]
@MohitMaliDeveloper Should I give a complete log in case you want it? I think the bug is in the code. I have tried in the multiple pixel emulators but the bug is not there. it's still crashing on my device. I think it's some edge cases that are causing this problem.

**Comment by MohitMaliFtechiz** [comment]
> pixel emulators but the bug is not there.

hi @gouri-panda can you further work on this PR since its only specific to your device.

**Comment by kelson42** [comment]
@MohitMaliFtechiz @gouri-panda I’m not sure what to do here. I think to some extend it would good if @gouri-panda could investigate to understand what goes wrong… but if things start to be really lon It woukd be good if @MohitMaliFtechiz you buy a second hand device of this very same model.

**Comment by gouri-panda** [comment]
@kelson42 Sounds good to me!

**Comment by MohitMaliFtechiz** [comment]
> ds good to me!

hi @gouri-panda so are you carry your investigation or I am going to ordered same device for testing ?

**Comment by gouri-panda** [comment]
@MohitMaliFtechiz @kelson42 Currently I'm busy with Room. The bug seems not trivial. It maybe happens under some conditions. Let me know what to do?

**Comment by kelson42** [comment]
I can say nothing, if the device crash shoukd be doablevto identify which line is a problem and why.

**Comment by gouri-panda** [comment]
@kelson42 We know which line is causing this problem. It happens because some objects are already consumed while it needs them.When we are accessing them it gives us the crash.

**Comment by kelson42** [comment]
So? none of you know how to fix this?

**Comment by gouri-panda** [comment]
@kelson42 I can fix this. It produces on my end. I'm busy now with the Room. If you want I can push the fix the commits here later.

**Comment by kelson42** [comment]
@gouri-panda This is the last PR for Kotlin, please deal with that in top priority, so we can finally close this chapter.

**Comment by kelson42** [comment]
@gouri-panda merci, crossing the fingers for you it won't take too long.

**Comment by gouri-panda** [comment]
@MohitMaliDeveloper I have placed the fix here. Please review it :)

**Comment by kelson42** [comment]
OK, but CI fails!

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliDeveloper I have placed the fix here. Please review it :)

hi @gouri-panda ,
Thanks for the fix. code looks good to me, now can you please re-review this PR.

**Comment by gouri-panda** [comment]
>OK, but CI fails!

@kelson42 Sometimes it fails due to the flakiness of the emulators.
>Thanks for the fix. code looks good to me, now can you please re-review this PR.

Thanks! @MohitMaliFtechiz

**Review by gouri-panda — APPROVED** [review]
@MohitMaliDeveloper Thanks!

**Comment by kelson42** [comment]
@gouri-panda What goes wring exactly with the CI, where are the tickets?

**Pull request merged**
