### PR TITLE
Fix #1966 Update home title when exiting a zim

### LINKED ISSUE #1966: Home title not changed when exiting zim
**Describe the bug**
When we exit a zim and return to the main screen of the app, the title of the screen stays the same as that of the zim just exited. 

**Expected behavior**

The title should be set back to "Kiwix"

**Steps to reproduce the behavior:**
1. Open any zim.
2 Press the phone back button to return to the main screen.
3. See the title. It should be "Kiwix", but it is that of the exited zim. 

**Screenshots**

The title on the top should have been kiwix. 
screencap

**Environment**
- Version of Kiwix Android : 3.2.1
- Device : Redmi K20
- OS version : Android 10

### PR DESCRIPTION
**Pull request by yashk2000**
Fixes #1966 

The home title gets updated when returning from a zim.

### CODE REVIEW

**Comment by 4shutosh** [comment]
Your solution is not perfect @yashk2000.
**On your solution**
Try opening a file again after closing it.
The title remains the same "Kiwix"
ezgif com-video-to-gif (2)

**Comment by yashk2000** [comment]
@4shutosh I am not able to replicate this bug with my device. 
But I reverted the change and noted a peculiarity. 
Even when my change is not there, on opening a zim for the first time on launching the app, the title of the zim is not displayed and Kiwix is displayed instead. Maybe both issues are related. I'll look into this.

**Comment by 4shutosh** [comment]
Would you please undo the change done in the current commit
And try adding `actionBar.setTitle(R.string.app_name);` in `CoreMainActivity.setHomePage` 
along with calling `updateTitle();` in `CoreMainActivity.openZimFile.1096`

I think then it should work perfectly fine.
ezgif com-video-to-gif (3)

**Comment by yashk2000** [comment]
@4shutosh for your information, that is exactly what I am doing. 
A polite reminder that I also know how to code and have been at it for a very long time :)

Not to be rude here, but I really don't appreciate you pasting a solution when I didn't ask for it. AFAIK this is the third time you've done this. I would like to remind you that everyone here comes to learn, and not get direct solutions. 

Not to sound rude again, but unless anyone directly asks for help please do not give direct solutions. Or at least please don't post direct solutions on the issues I create. 

@4shutosh I request you not to take this as rudeness or in the wrong way, but some polite advice from a fellow contributor. I appreciate constructive discussions, but not direct solutions. If I am stuck somewhere, I will ask for clarifications of my doubts then. You can check out my prs, if I get stuck, I do ask for help but not before.

**Comment by 4shutosh** [comment]
@yashk2000 Did not want to challenge or doubt your coding skills in any way.

I just tried to suggest a code that I think will work. There is no intention of giving a **direct solution** here. You are always required to work on your own and find the best possible solution which you always do and is appreciated.

Apologies if you find it rude.

**Comment by yashk2000** [comment]
@4shutosh I'm sure that you know that for such a basic issue, what you mentioned in the comment above is a direct solution. 

> I just tried to suggest a code that I think will work.

So instead of mentioning the code here maybe, you can give your idea. For example how you think I should have approached the issue. For instance, when you pointed out the flaw in my solution, my thought process was something like "Set the title to Kiwix when the home is reached. Set the title of a zim whenever a zim  is opened". You could comment something like that. This way, maybe even we could get a better and more efficient solution to more complex issues by discussing our ideas instead of directly telling which lines of code to change and what exactly to code. If you discuss this way, I would gladly take part and we could learn even more from other contributors and how they approach issues. 

> Apologies if you find it rude.

I didn't find it rude. I hope you understood what I meant to say :)

**Comment by 4shutosh** [comment]
Yes @yashk2000, I'll defintely implement what you explained.

**Comment by 4shutosh** [comment]
Yes @yashk2000, I will defintely implement what you suggested.

**Comment by yashk2000** [comment]
@4shutosh it works in the expected way now. 
Thanks for pointing out the error :)

**Comment by 4shutosh** [comment]
> @4shutosh it works in the expected way now.
> Thanks for pointing out the flaw :)

@yashk2000 Sorry to say, the current commit does not work 
Below is the exexcution of your latest commit
ezgif com-video-to-gif (4)

**Comment by yashk2000** [comment]
ezgif com-video-to-gif

**Comment by 4shutosh** [comment]
Try opening the same zimfile repeatedly, like I demonstrated above. It won't work.

**Comment by yashk2000** [comment]
Ok, saw that now. This is peculiar.

**Pull request merged**
