### PR TITLE
Fixes#943 Resolving Deprecated API Usage

### LINKED ISSUE #943: Deprecated API Usage
**Describe the bug**
Deprecated API Usage in 2 files.

**Expected behavior**
Import updated classes and use it's methods.

**Steps to reproduce the behavior:**
1. Deprecated API Usage in KiwixDatabaseTest.Java and TestUtils.java.
2. androidTestImplementation of junit can be updated in build.gradle.
3. import updated class of AndroidJUnit and InstrumentationRegistry in KiwixdatabaseTest.Java.
4. import updated class of InstrumentationRegistry in TestUtils.Java.

### PR DESCRIPTION
**Pull request by iadeelzafar**
### Changes:
* In build.gradle. I added.
When you're using Android X you need to make sure you have the following in your app's build.gradle file.
androidTestImplementation "androidx.test.ext:junit:1.1.0"
androidTestImplementation 'androidx.test:core:1.1.0'

* In KiwixDatabaseTest.java
I added import androidx.test.platform.app.InstrumentationRegistry because it is the latest class according to Android Developers documentation
Reference: https://developer.android.com/reference/androidx/test/platform/app/InstrumentationRegistry#getInstrumentation()

* Same was done in the TestUtils.java class and method calls are made accordingly.

### CODE REVIEW

**Comment by soloturn** [comment]
@iadeelzafar , the change @abdulwd did for androidx introduced a couple of more erros in the build:
https://travis-ci.org/kiwix/kiwix-android/builds/489166034?utm_source=github_status&utm_medium=notification

you have an idea where this is coming from as well, or should we create a ticket for it?

```
> Transform artifact converter-simplexml.jar (com.squareup.retrofit2:converter-simplexml:2.5.0) with JetifyTransform
ERROR: [TAG] Failed to resolve variable '${project.groupId}'
ERROR: [TAG] Failed to resolve variable '${project.version}'

> Transform artifact logging-interceptor.jar (com.squareup.okhttp3:logging-interceptor:3.12.1) with JetifyTransform
ERROR: [TAG] Failed to resolve variable '${project.groupId}'
ERROR: [TAG] Failed to resolve variable '${project.version}'

> Transform artifact error_prone_annotations.jar (com.google.errorprone:error_prone_annotations:2.1.3) with JetifyTransform
ERROR: [TAG] Failed to resolve variable '${junit.version}'
> Transform artifact guava.jar (com.google.guava:guava:24.0-jre) with JetifyTransform
ERROR: [TAG] Failed to resolve variable '${animal.sniffer.version}'

```

**Comment by iadeelzafar** [comment]
Hi @soloturn , I think it's better to create a separate ticket for it. So, everyone can give their suggestions on resolving this issue.

**Comment by iadeelzafar** [comment]
@siddharth2010 Thanks for the review brother.

**Comment by soloturn** [comment]
ok, created #950

**Comment by mhutti1** [comment]
It seems this breaks our device runner. I think it doesn't yet have the latest test runner. Am looking into it.

**Pull request merged**
