### PR TITLE
#2657 Input methods were broken

### LINKED ISSUE #2657: [Bug]Text input lag-Article search
**Describe the bug**
Text input is very laggy.

**Expected behavior**
Fluid text input
**Steps to reproduce the behavior:**
1.Open library
2. Input any text for search

**Environment**
- Version of Kiwix Android : 3.4.4
- Device : Huawei P30 ELE-L09
- OS version : EMUI 11-Android 10
- Keyboard : Gboard latest version

### PR DESCRIPTION
**Pull request by gouri-panda**
Fixes #2657

### CODE REVIEW

**Comment by kelson42** [comment]
@gouri-panda I was impacted and the fix seems to work. Unfortunately I don't really understand why we had this regression and can not judge if the fix is appropriate.

**Comment by mhutti1** [comment]
@gouri-panda can you explain what you did to fix it?

**Comment by gouri-panda** [comment]
@mhutti1 In `SearchFragment` we render the text as a SeachState, that's why it doesn't add some words.

**Comment by kelson42** [comment]
@gouri-panda What I don't understand, but this is probably because I'm not an Android dev, but the diff does not explains it:
* What exactly is not rendered each time anymore?
* Why a regression has been added in 2.4.5 (if someone has created the regression, there is a reason behind)?
* It does seem to me that the inputbox should be rendered eachtime someone type a letter?
* What triggers the rendering now, if this is not typing on the inputtext?
* Why rendering all the times leads to a situation where basically time to time a letter is not rendered?
* Who is impacted by this bug?

**Comment by gouri-panda** [comment]
>What exactly is not rendered each time anymore?
>It does seem to me that the inputbox should be rendered eachtime someone type a letter?

Well, it does it automatically each time. So, we don't have to do it manually anymore.  
Here is the code that does automatically 
https://github.com/kiwix/kiwix-android/blob/6873e9f3b957ad0a8abfd8c3d68d0a00ab0f3365/core/src/main/java/org/kiwix/kiwixmobile/core/search/SearchFragment.kt#L151-L156
>Why rendering all the times leads to a situation where basically time to time a letter is not rendered?
In my theory our `render()` function does a lot of things each time users inserted a character such as filtering from the database and looking through all the zim for a word and more, so this is an expensive task and it needs some time to calculate in the meanwhile users to start typing so fast, so android dropped some character in inputbox if a user typed so fast.

**Comment by kelson42** [comment]
@gouri-panda OK, but then if this rendering method is called automatically, why the code has been added here in a first place? This has been added recently as this was working earlier? From which PR comes this code?

**Comment by gouri-panda** [comment]
>@gouri-panda OK, but then if this rendering method is called automatically, why the code has been added here in a first place? This has been added recently as this was working earlier? From which PR comes this code?

@kelson42 This comes from #2607 .

**Comment by kelson42** [comment]
@mhutti1 what is the status of this PR? I beleive we shoukd merge.

**Comment by mhutti1** [comment]
@kelson42 Sure, feel free to if you are satisfied

**Comment by danielzgtg** [comment]
I will answer the questions in this thread, as this was a regression of #1818. Hopefully this will lead to some automated tests being added.

> so android dropped some character in inputbox if a user typed so fast.

No, Android will not drop characters if users type fast. It will just buffer those characters. When one of my apps lag, I can still see the suggestions in my keyboard updating, while the text field is stuck. Then once the app comes back to life, all those characters are inputted all at once.

> What exactly is not rendered each time anymore?

Nothing. Whatever "rendering" was completely unnecessary as it was setting a text field to its new value every time.

> Why a regression has been added in 2.4.5 (if someone has created the regression, there is a reason behind)?

Because there is no automated testing with input methods or something equivalent.

Even without CJK users, it was flickering on a normal keyboard, and hardwriting input would not work. Regressions like these are likely if the text input components that OSes provide are messed with. Input methods are a complex domain that has a major component dedicated to them in every OS/browser. I suppose a regression would occur eventually if there are no automated tests.

> It does seem to me that the inputbox should be rendered eachtime someone type a letter?

No, you do not want to render (two-way bind the text) the inputbox on Android. Perhaps on other platforms as well such as one app doing that with Qt and another breaking things by trying to reinvent a HTML textarea. It breaks all CJK input methods and handwriting input methods that ***rely on a selection***. A input method selection is an underlined and highlighted region that is being edited. The editing may be converting ASCII to Kanji, composing Hangul, or converting an English "l" into and "i" when you draw the dot. The problem with two-way binding is that the binding back sets the inputtext value on every action. ***That clears the input method selection***, which cancels those editing functions that an input method a.k.a. an Input Method Editor (IME) provides. Two-way text binding is especially bad as it interrupts you after the first step of everything you want to do, making it impossible to type CJK languages.

> What triggers the rendering now, if this is not typing on the inputtext?

It is indeed typing on the inputtext. There might have been an initial value feature, but I've never seen it working.

> Why rendering all the times leads to a situation where basically time to time a letter is not rendered?

1. User types a few letters into input queue
2. Kiwix-android event handler is called and starts executing
3. Users types a few more letters into input queue
4. Kiwix-android perhaps ignores those because the event handler is already running and there might be debouncing logic somewhere
5. Kiwix-android event handler finishes its heavy processing
6. It sets the inputtext's value to the outdated text in step 2, not the text in step 3. This throws away the new value, causing letters to be dropped
7. If the event handler is set to run again at this point, it will read the same value because the value has already been overwritten by step 6

This is a symptom separate from that of the CJK input methods, but it comes from the same disease of text two-way binding.

> Who is impacted by this bug?

The list of user demographics you mentioned in https://github.com/kiwix/kiwix-android/issues/1818#issuecomment-591378066

**Pull request merged**
