### PR TITLE
Fixed: Online library cannot be retrieved in the Play Store variant.

### LINKED ISSUE #3991: Online library can not be retrieved
On Samsung tablet with Android14, newly, the online library can not be retrieved. The spinner keeps running...

Screenshot_20240911_073854_Kiwix

It should work obviously as I have plenty of bandwidth

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #3991 

* The issue arose after upgrading the Gradle version of our project (which introduced Android 14). The new Gradle version includes an updated minify tool that excludes some `SimpleXML` attributes from the code. As a result, this error occurred. To resolve this, we added specific rules to the ProGuard file to ensure these attributes are retained in the release variant.
* Added test cases to the CI for testing the minified version of the application to prevent this type of error from happening in the future.
* Improved the DownloadTest to handle cases where pausing the download may show a complete pause message, such as 'Pause: Waiting for Retry,' which previously caused the test case to fail. The test case has been updated to accommodate this behavior.
* Fixed the NoSucMethodError in UI test cases [see](https://github.com/kiwix/kiwix-android/actions/runs/10848990036/job/30107246469?pr=3994#step:9:938). It was due to AGP silently downgrade to `tracing:1.0.0`. It is mentioned in the [official github repo](https://github.com/android/testing-samples/blob/a76330ba879cd671bf31012c79a9321e87097e64/ui/espresso/ScreenshotSample/app/build.gradle#L60)

```kotlin
09-13 12:28:47.887  4720  4768 E AndroidXTracer: java.lang.NoSuchMethodError: No static method forceEnableAppTracing()V in class Landroidx/tracing/Trace; or its super classes (declaration of 'androidx.tracing.Trace' appears in /data/app/org.kiwix.kiwixmobile-1/base.apk)
```
* Improved the fetching and downloading the online library on low bandwidth. Since the online library file is 19MB large and on slow bandwidth devices it takes more time to fetch that file. Our current read timeout is 60 seconds which is not enough for reading this file on slow-bandwidth devices(After reaching the timeout it cancels the ongoing request). So we have increased it to 180 seconds.

```kotlin
java.io.InterruptedIOException: timeout
Caused by: okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL
```
* Refactored our code to properly show the progress of downloading the online library.
* Improved the library loading process: previously, fetching the online library involved making two requests, which not only took more time to get a response from the server but also used twice the bandwidth. To address this, we have refactored our code to ensure that only one request is made at a time.
* Upgraded the retrofit, and interceptor dependencies to the latest version.

https://github.com/user-attachments/assets/91913432-2042-431f-9d40-eb9fc99dac31

Screenshot from 2024-09-18 22-03-27

Any suggestions/improvements are welcome for the UI to show the progress.

### CODE REVIEW

**Comment by kelson42** [comment]
@MohitMaliDeveloper From a user perspective this looks really good, here a few points:
* We should be sure that this sync does not happen in mobile data only without clearly accepted by the user (should already be the case)
* Please ensure that we can not start such a process twice at a time (should already be the case). Please confirm.
* Do we have scenario where this sync with the online scenario happen in the background (so not triggered by a user action)? If "yes" does it continues to work fine?
* Does this sync continues to work fine if we put the app in background or leave this view by switching back to the content for example?
* Can you put the pourcentage on the new line at the bottom please (so we don't have the comment message and the pourcentage on the same line)?

**Comment by MohitMaliFtechiz** [comment]
> We should be sure that this sync does not happen in mobile data only without clearly accepted by the user (should already be the case)

@kelson42 Yes, the sync does not happen on mobile data if the user does not accepted it.

> Please ensure that we can not start such a process twice at a time (should already be the case). Please confirm.

@kelson42 It was happening, but I have placed a fix for it in this PR.

> Do we have scenario where this sync with the online scenario happen in the background (so not triggered by a user action)? If "yes" does it continues to work fine?

Yes, we have this scenario and it is working fine. I have tested it.

> Does this sync continues to work fine if we put the app in background or leave this view by switching back to the content for example?

yes, the sync works in these scenarios.

> Can you put the pourcentage on the new line at the bottom please (so we don't have the comment message and the pourcentage on the same line)?

@kelson42 I have made the changes as per your request.

> CI is not passing!!!

Yes. the unit coverage was failing due to our changes. I have placed a fix for those test failures.

**Comment by kelson42** [comment]
@MohitMaliFtechiz wenn no wifi is available the download process should not start at all!

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz wenn no wifi is available the download process should not start at all!

@kelson42 The downloading/sync process only starts on the mobile network when the user confirms to sync/download via the mobile network. Downloading/Sync will not start when no wifi is available and the user does not agree to download/sync content via the mobile network.

**Comment by MohitMaliFtechiz** [comment]
@kelson42 The application has been released for internal testing: https://github.com/kiwix/kiwix-android/actions/runs/10938877209/job/30367933099.

**Pull request merged**
