### PR TITLE
Dialog Box style changes in settings itself

### LINKED ISSUE #426: Dialog Box style not changing until KiwixMobileActivity is refreshed.
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request

## Bug Report
When changing from one mode to another, the dialog box styles do not change unless we go back to kiwixMobileActivity.
### Step 1: Are you ready to report ?
   - Your issue may already be reported! Please search on the [issue track](../) before creating one.
   - [x] I have test with the last (dev) version of the software?  ( If not, and if possible, run your test again with the most recent version available.)

### Step 2 : What is your environment ?
  * browser / app : app
  * version of the software you use : 2.3 Build: 55 
  * device / operating system : Android 7.1.1 ( Lenovo K8 Plus)
  
### Step 3: Describe the problem:

  * What do you obtain? A copy of the error message or a screenshot is always useful
   
ezgif com-video-to-gif 2

  * When does this occur? 
   When the mode is changed and the dialog boxes are clicked without going back.
#### Steps to reproduce:

  1. Change mode from day to night
  2. Click on "Clear all history" without going back
  3. Click on "Credits"
  ...
  
  * What should be the behaviour from your point of view? How do you expect the service to work?
Dialog Box style should change as soon as the mode is changed.

### Step 4 (optional) : Other Comments:
  * What is the context of this ticket? If not obvious, explain why you need to do this.
 
  * If you have an idea about the technical background of the ticket, please share it.

### PR DESCRIPTION
**Pull request by arpank10**
Fixes #426

Changes: Dialog Box style changes as soon as mode is changed.

### CODE REVIEW

**Comment by srv-twry** [comment]
@arpank10 Can you please attach a GIF ?

**Comment by arpank10** [comment]
ezgif com-video-to-gif 5

**Comment by arpank10** [comment]
That wouldn't work IMO. That would mean that the style would change when we go back to kiwixmobileactivity and would remain unchanged till then. Tried it, not working.

**Comment by srv-twry** [comment]
Interesting. I thought we are actually calling finish() which would make us go back to the KiwixMobileActivity but yeah it won't. :+1:

**Pull request merged**
