### PR TITLE
Added Share Menu in Menu Option

### PR DESCRIPTION
**Pull request by pprathameshmore**
This is my first implitimation in app. Is this correct!

### CODE REVIEW

**Comment by pprathameshmore** [comment]
@mhutti1 Please help I can not understand these conflicts.

**Comment by srv-twry** [comment]
@pprathameshmore 
> This is my first implitimation in app. Is this correct!

Please link this PR with the issue that you're trying to solve. You can check how to do that [here](https://github.com/blog/1506-closing-issues-via-pull-requests)

> Please help I can not understand these conflicts.

After you have opened a PR, someone else made a change to one of the files that you've edited in your PR also. So there is a conflict. You can easily resolve this conflict following the steps from [here](https://help.github.com/articles/resolving-a-merge-conflict-on-github/)

**Comment by srv-twry** [comment]
@pprathameshmore 
> This is my first implitimation in app. Is this correct!

Please link this PR with the issue that you're trying to solve. You can check how to do that [here](https://github.com/blog/1506-closing-issues-via-pull-requests)

> Please help I can not understand these conflicts.

After you have opened a PR, someone else made changes to one of the files that you've edited in your PR also. So there is a conflict. You can easily resolve this conflict following the steps from [here](https://help.github.com/articles/resolving-a-merge-conflict-on-github/)

**Comment by cmeher196** [comment]
can i get the link of this issue as i m interested to work on it

**Comment by srv-twry** [comment]
Closing due to inactivity. Please feel free to reopen when required.

**Pull request closed without merging**
