### PR TITLE
Ripple effect

### PR DESCRIPTION
**Pull request by MayankChuriwal**
Ripple effect #477

The ripple effect is more visible now and the button also now looks better with gradient styling and the ripple effect is more visible. 

Please review @mhutti1

### CODE REVIEW

**Comment by kelson42** [comment]
@MayankChuriwal Why do you close this PR?

**Comment by MayankChuriwal** [comment]
@kelson42 I have opened a new PR because there there some unwanted code changes and it had 3 commits. Now the PR which I have opened is accurate and precise. Sorry for that. Actually new to open source relatively.

**Comment by kelson42** [comment]
@MayankChuriwal no problem.

Opening PR or manipulating them generates notifications to the mentors. We get a lot of them currently and appreciate if PR are not considered as a "playground".

A few recommendations:
* Open PR what time you have properly tested your code
* If you remark you have still done something wrong, do not close the PR to reopen one, you `git rebase` (have a look to the `-i` option) and `git push -f` instead.

**Comment by MayankChuriwal** [comment]
I will keep that in mind and will follow the guild lines strictly. I am extremely sorry and thanks for your help. @kelson42 Can you review my PR and let me know if I have to make any changes.

**Comment by kelson42** [comment]
@MayankChuriwal Thank you. @mhutti1 will, he is the dev lead.

**Pull request closed without merging**
