### PR TITLE
Feature/jhbiggs/#973 bottom toolbar

### LINKED ISSUE #973: Enable bottom toolbar by default
**Is your feature request related to a problem? Please describe.**

As of now, there is no way to add a bookmark without enabling the bottom toolbar.

**Describe the solution you'd like**

 Enable the bottom toolbar by default.

### PR DESCRIPTION
**Pull request by macgills**
Fixes #973 

Changes: see #1197

### CODE REVIEW

**Comment by macgills** [comment]
@jhbiggs there are 2 minor issues
```

  /home/travis/build/[secure]/[secure]-android/app/src/main/res/values/strings.xml:163: Error: The resource R.string.pref_bottomtoolbar appears to be unused [UnusedResources]

    <string name="pref_bottomtoolbar">Enable bottom toolbar</string>

            ~~~~~~~~~~~~~~~~~~~~~~~~~

  /home/travis/build/[secure]/[secure]-android/app/src/main/res/values/strings.xml:164: Error: The resource R.string.pref_bottomtoolbar_summary appears to be unused [UnusedResources]

    <string name="pref_bottomtoolbar_summary">Display a toolbar with quick actions at the bottom of the screen</string>

            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Can you open a PR targeting this branch that removes these 2 unused strings please?

**Comment by jhbiggs** [comment]
Thanks, @macgills.  I created a new pull request with the changes.  Hope that was right.

**Comment by kelson42** [comment]
@jhbiggs Thank you for the new PR, but you can perfectly also updated this PR. You can change the branch it applies on by clickint on the "Edit" button beside the PR's title. You can also just fix the problem by making a new commit to your branch, the PR will be then automatically updated.

**Comment by macgills** [comment]
@jhbiggs the strings were still present in 25 other languages causing 50 lint errors, I have fixed it now

**Pull request merged**
