### PR TITLE
fix: Enable Proguard to reduce apk size

### LINKED ISSUE #101: Set up proguard
Set up Proguard to reduce apk size for #86.

### PR DESCRIPTION
**Pull request by brijeshshah13**
Fixes #101.
@mhutti1 Please review.

### CODE REVIEW

**Comment by mhutti1** [comment]
My bad for this not failing the auto test though I'm going to fix that now.

**Comment by brijeshshah13** [comment]
So shall I change the build variant or keep as it is?

**Comment by mhutti1** [comment]
@brijeshshah13 Code must compile for all build Variants and this doesn't for release because proguard has been configured incorrectly.

**Comment by brijeshshah13** [comment]
Shall I write another build type `debug` and include proguard in that as well?

**Comment by mhutti1** [comment]
@brijeshshah13 No the point of proguard is to reduce app size but it takes time so it is only supposed to be run on relase builds. But it must be configured to work with libraries. This task is actually fairly complex so you can try something else if you are struggling.

**Comment by brijeshshah13** [comment]
Okay. No problem.

**Comment by srv-twry** [comment]
@brijeshshah13 How about closing this PR for now and opening it when we have feasible solution for it ?
The number of opened PRs is increasing everyday so let's close the inactive ones.

**Pull request closed without merging**
