### PR TITLE
Refactor manageExternalLaunchAndRestoringViewState

### PR DESCRIPTION
**Pull request by rashiq**
- rename method to loadZimFile because manageExternalLaunchAndRestoringViewState
is a very confusing name
- remove unnecessary logs and added comments instead
- reduced nesting

This does not add any new functionality. It's just reducing complexity.

### CODE REVIEW

**Comment by rashiq** [comment]
@mhutti1 can you make sense of why exactly the build is failing?

**Comment by RohanBh** [comment]
The random failing of travis build was discussed in #518.

**Comment by rashiq** [comment]
Gotcha @RohanBh. Though I restarted yesterday as well and got the same error; oh well let's see if it builds now!

**Comment by rashiq** [comment]
It's still failing

**Comment by brijeshshah13** [comment]
@rashiq Do not worry about the build. It will get resolved in the upcoming Android Plugin version.

**Comment by RohanBh** [comment]
It has passed now!

**Comment by RohanBh** [comment]
@rashiq this PR fixes #174.

**Comment by kelson42** [comment]
@rashiq @macgills I guess we should close this PR because of inactivity? What about the underlying ticket #174?

**Comment by macgills** [comment]
This method still exists in the now renamed MainActivity, I would say it would be for the best to just redo the work as opposed to try and update this PR

**Pull request closed without merging**
