### PR TITLE
Fix Storage permission on Android 13

### LINKED ISSUE #3081: Can't grant storage permission on Android 13

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #3081

### CODE REVIEW

**Comment by kelson42** [comment]
@MohitMaliDeveloper CI seems to fail :(

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliDeveloper CI seems to fail :(

hi @kelson42 , I just rerun it and its green now.

**Review by gouri-panda — COMMENTED** [review]
We should test this as well in Android 13 in CI after #2944

**Comment by kelson42** [comment]
Hi @gouri-panda I think this PR desserves a new review.

**Comment by gouri-panda** [comment]
@kelson42 It would be best if we do this after #2944 and also it would be best if we add tests for this in the PR as well.

**Comment by MohitMaliFtechiz** [comment]
> @kelson42 It would be best if we do this after #2944 and also it would be best if we add tests for this in the PR as well.

hi @gouri-panda ,

Actually we are not taking ```storage permission``` on android 13 because we are saving ```zim files``` inside 
```app specific directory``` and for test case i think #3084 in this PR we added ```InitialDownloadTest``` will works for this issue.

According to https://github.com/kiwix/kiwix-android/issues/3081#issue-1377421856 after clicking on download button it's showing a dialog, so for this issue our ```InitialDownloadTest``` will works.

**Comment by kelson42** [comment]
@gouri-panda not sure abput the status here hobestly!

**Comment by kelson42** [comment]
@gouri-panda ???

**Comment by gouri-panda** [comment]
@MohitMaliDeveloper There are some conflict files here :)

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliDeveloper There are some conflict files here :)

hi @gouri-panda ,
i have resolved the conflicts.

**Comment by gouri-panda** [comment]
@MohitMaliDeveloper Thanks!

**Review by gouri-panda — APPROVED** [review]

**Comment by kelson42** [comment]
@gouri-panda Still good for you to merge?

**Comment by gouri-panda** [comment]
Ok @kelson42

**Review by gouri-panda — APPROVED** [review]

**Pull request merged**
