### PR TITLE
Pass Test for Android 30

### LINKED ISSUE #2729: Pass Test for Android 30
Error:
 >qemu_pipe_open_ns:62: Could not connect to the 'pipe:qemud:network' service: Invalid argument

Since we weren't checking the device after 6.0(marshmallow) we are seeing now in android API 30(android 10)  emulator devices. This error could be seen on Android Emulator/Device Version >= 6.0. It occurs probably when our app tries to send/receive requests/responses to a remote API that is not secure (HTTP).

### PR DESCRIPTION
**Pull request by gouri-panda**
Fixes #2729 

**Reason:**
When an app communicates with servers using a cleartext network traffic, such as HTTP, it could raise the risk of tampering with the content. Third parties can inject unauthorized data or leak information about the users. That is why developers are encouraged to secure traffic only, such as HTTPS.

But this can fix by `android:usesCleartextTraffic="true"`. This allows override this error.

### CODE REVIEW

**Comment by kelson42** [comment]
@gouri-panda What is the status here? You have asked review, but the PR is in draft! I have requested @MohitMaliFtechiz To have a look to these recurrent CI problems. You should talk together soon IMO to better collaborate.

**Review by MohitMaliFtechiz — DISMISSED** [review]
this changes will allow http request.

**Comment by gouri-panda** [comment]
@MohitMaliFtechiz It's not done yet. Some of the tests are still failing. I'll look into it.

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz It's not done yet. Some of the tests are still failing. I'll look into it.

yes

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz It's not done yet. Some of the tests are still failing. I'll look into it.

yes

**Comment by kelson42** [comment]
@gouri-panda @MohitMaliFtechiz How does this PR collaborate with #2802?

**Comment by gouri-panda** [comment]
@kelson42 I guess it's the same.

**Comment by kelson42** [comment]
@gouri-panda What i coukd propose is to close this PR and let @MohitMaliFtechiz continue your work on fixing the CI. I don't think it is wfficient if both of you work on the same topic.

**Comment by kelson42** [comment]
Superseeded by #2810

**Pull request closed without merging**
