### PR TITLE
Disable density splits

### PR DESCRIPTION
**Pull request by macgills**
Attempt to fix quickly #1410. App was failing to install on hdpi emulators. We will need to supply the missing resources for the respective densities, will be solved by #1274

### CODE REVIEW

**Comment by kelson42** [comment]
@macgills Why not just providing the missing resources?

**Comment by macgills** [comment]
@kelson42 because that is more work and there is a ticket for it, albeit not a very in depth ticket.

**Comment by kelson42** [comment]
@macgills  #1274 Seems to belong the category of ticket difficult to fix because it handles a bunch of different things. How much time do you expect would be needed to fix this very specific problem with the missing resources related to multiple densities?

**Comment by macgills** [comment]
I believe @Aditya expressed an interest in going through that ticket and making a dent in the baseline.

I have no idea where these images came from, I can scale down the images in paint and put them in the correct folders? I usually just get provided assets, what is asset generation like on the project?

**Comment by Aditya-Sood** [comment]
Yes, I'd like to help out with #1274 once I'm through with the stuff I'm working on right now

**Comment by kelson42** [comment]
@macgills Could you please open a dedicated ticket for this problem and attach your PR? We should then see what is the smarter approach to deal with it.

**Comment by macgills** [comment]
@kelson42 this is temporary fix so devs can continue to install the app on lower density devices. I will create a ticket to fix the icon issues and re-enable the splits but I think we should go ahead with this PR

**Comment by kelson42** [comment]
@macgills Could we keep it open a bit and give a chance to @Aditya-Sood to fix the problem properly? I really don't like to see us going in that direction in July and then in August somehow rollbacking.

**Comment by macgills** [comment]
The density split feature is not actually crucial, it just saves us a couple KB(maybe 1MB) per apk.
I thought there was an issue when I first pursued this but Gradle Play Publisher(how we release to the play store) released an update that satisfies our pre-existing scenario of only splitting per abi (armeabi, x86 etc).
We can hold off on it if @Aditya-Sood will gets time to work on this soon, otherwise I would like to remove friction for our contributors. Aditya what is your schedule like?

**Comment by Aditya-Sood** [comment]
@macgills I am focussing on 765 and local file transfer issues for now, plus I've got a couple of evaluations and then exams this month. But from what I understand the requirement is only to provide re-sized copies of the images, so if that is all then I can take this up now.

**Comment by macgills** [comment]
I will close this so

**Comment by macgills** [comment]
After discussion with @kelson42 we will disable density splits for now and revisit them in 3.1

**Pull request merged**
