### PR TITLE
Feature/macgills/1275 duplicate strings

### LINKED ISSUE #1275: Lint Issue: Duplicate Strings
**Is your feature request related to a problem? Please describe.**
```
Duplicate Strings
 Duplicate strings can make applications larger unnecessarily.
 This lint check looks for duplicate strings, including differences for strings where the only difference is in capitalization. 
Title casing and all uppercase can all be adjusted in the layout or in code.  
Issue id: DuplicateStrings
```

**Describe the solution you'd like**
This should be fixed to reduce app size and lessen the burden of translation. It will require a regeneration of translations after the issue is addressed for English.

### PR DESCRIPTION
**Pull request by macgills**
Fixes #1275 

Remove duplicate strings and unused resources

### CODE REVIEW

**Comment by macgills** [comment]
@Abijeet I have a few concerns about this PR and how it will interact with TW.

First of all I deleted all unused resources, to get this automatic process to work properly I had to move a few strings about the modules. Unfortunately there is no automatic procedure to move just 1 string and all its translations across a module so I just moved the english string and deleted any corresponding string in another language. See all the new additions to `app/src/main/res/values/strings.xml`, these were all moved from `core/src/main/res/values/strings.xml`

Also there are duplicate strings in non English languages so I do not have a good idea if they are valid or not, if you download this [file](https://drive.google.com/open?id=1wB2S8vAqm1y7xc_f-ni2hLkfVbUY3gDT) and open it with a browser you should see a detailed report on the affected languages.

**Comment by macgills** [comment]
@Abijeet do you have input on this PR?

Specifically on the topics of
- Will this damage the translation effort from moved strings?
- The 19 duplicate strings in non-English languages

**Comment by Abijeet** [comment]
> In summary one of the following happened to a string resource in this PR
> 
>     * found to not be used anywhere so was deleted across all languages
> 
>     * the English string move from core to app, other languages string was deleted
> 
>     * the string had a duplicate in English, all usages were directed to 1 string, it was renamed to better reflect it, the now unused duplicates were deleted across all languages

None of this should affect future translation effort, but will cause previous translations to be deleted and hence loss of work already done by translators.

> The 19 duplicate strings in non-English languages
```
crash_button_decline: NO THANKS
rate_dialog_negative: No, thanks
```
Some languages might not have comma, for example traditional Arabic, in such cases the translations will be same other than the capitalization that's present.

```
tts_stop: Stop
tts_pause: Pause
```
This is not an ideal translation but not uncommon in some languages either. Adding more message documentation explaining that this is for the string "Stop" specifically and not "Pause", since "Pause" has another message for it might help in improving the quality of the translation.

**Comment by macgills** [comment]
@Abijeet so the remaining duplicates are:

```
<string name="pref_zoom_dialog">Zoom level</string>
<string name="pref_zoom_enable">Zoom controls</string>
```
in OR

```
<string name="next">Next</string>
<string name="rate_dialog_neutral">Later</string>
```
in CKB

```
  <string name="tts_pause">pause</string>
  <string name="tts_stop">stop</string>
```
in NE/DIQ/KU

```
  <string name="next">Next</string>
  <string name="pref_extras">Extras</string>
```
in CS

```
  <string name="paused_state">Paused</string>
  <string name="tts_pause">pause</string>
```
in SL/ZH/ZH-rTW

**Comment by macgills** [comment]
@Abijeet to clarify, if I delete a string resource out of another languages strings.xml it will delete that translation work?

I may need to find a way of making lint function across modules, seeing as how moving strings across modules is difficult.

**Pull request closed without merging**
