### PR TITLE
Swipe down on toolbar to open tabs switcher

### LINKED ISSUE #1114: Add swipe down animation (was: Add swipe down toolbar gesture to open tabs switcher)
**Is your feature request related to a problem? Please describe.**
The icon for opening the tab switcher is quite small and it is used frequently. So there must be a gesture to open the tab switcher.

**Describe the solution you'd like**
Google Chrome offers a gesture to open the tab switcher which is pull down from the toolbar.

**Additional context**
ezgif-1-8ad26a80ceb7

### PR DESCRIPTION
**Pull request by ShridharGoel**
Fixes #1114 

Changes: 

Added swipe down gesture in toolbar. Swiping down would open up the tabs switcher.

GIF for the change: 

ezgif com-video-to-gif (61)

### CODE REVIEW

**Comment by ShridharGoel** [comment]
@abdulwd I have added a class OnSwipeTouchListener. Functions from the same can be used for #1113

**Comment by ShridharGoel** [comment]
@abdulwd Please review.

**Comment by kelson42** [comment]
@mhutti1 @macgills What should be we do for that PR?

**Comment by ShridharGoel** [comment]
@macgills I have changed the base branch to `develop`.

**Comment by macgills** [comment]
Ah yes, you have forked the project, bear with me over the next few minutes, I will need to merge these changes onto a branch and reopen the PR internally so that our CI can run effectively

**Pull request merged**
