### PR TITLE
Styles storage night mode

### LINKED ISSUE #630: UI Bug in "Storage" dialog box in "settings"
### Environment
  * version of the software you use : build 2.3, latest commit
  * device / operating system : Samsung S6, Android 7.0
  
### The Bug:
  * What do you obtain? A copy of the error message or a screenshot is always useful.
selecting the "storage" option in "settings" (with night mode selected) opens a dialog box with text not visible.
screenshot_20180313-112006

Here's the image when night mode is off
screenshot_20180313-112305

#### Steps to reproduce:

  1. Open "Settings"
  2. Turn Night mode "ON"
  3. tap on "storage"
  
#### Expected behavior:

most probably, the bug is because the color and the header as well as the OK button are white and they are hidden in the white background.

Ideally, in night mode, White text should be displayed in a grey dialog box, such that the color scheme matches that of the night mode

something like this is required:
screenshot_20180313-224558

### PR DESCRIPTION
**Pull request by GeVic**
Fixes #630 #792 

@siddharth2010 @mhutti1 Please review and merge.

storage_night_mode

### CODE REVIEW

**Comment by GeVic** [comment]
@mhutti1  @siddharth2010  #638  Pull Request has commits for both the dialog Storage and language. Please review and merge that instead of this.

**Comment by siddharth2010** [comment]
@GeVic Sure. Just give me some time.

**Comment by siddharth2010** [comment]
@GeVic Sure. Just give me some time.

**Comment by brijeshshah13** [comment]
@GeVic If #638 is resolving this issue then please close this PR.

**Comment by GeVic** [comment]
@brijeshah13 I didn't close in case they decide to merge only this one.

**Comment by brijeshshah13** [comment]
@GeVic Please update the other PR stating all the changes performed and mention the all the issues that it resolves. Then you can close this PR.

**Comment by GeVic** [comment]
@brijeshshah13 I gave detailed commits on that PR stating changes. Although I can still change the heading of the PR.

**Pull request closed without merging**
