### PR TITLE
Enhancement #779 : Add menu to share ZIM files

### LINKED ISSUE #779: Add ability to share ZIM files from within the app
#### Feature Description

Long clicking a downloaded file should give the option to either delete or share via a top menu as happens in bookmarks.

screenshot_20180628-225705_kiwix

### PR DESCRIPTION
**Pull request by Aditya-Sood**
Fixes #779 

Changes: Shifted delete functionality and added share functionality; for multiple selected files

Screenshots/GIF for the change:

Multiple selected files:

screenshot_20181004-022520

-------------------------------------------------------------------------------------------------------------------------------------------

Upon selecting the delete option, a confirmation is requested for each selected file:

screenshot_20181004-022527

-------------------------------------------------------------------------------------------------------------------------------------------

Upon selecting the share option, an app chooser appears with the set of all compatible apps (those which can share files):

screenshot_20181004-023157

-------------------------------------------------------------------------------------------------------------------------------------------

Email:

gmail

-------------------------------------------------------------------------------------------------------------------------------------------

Drive:

drive

-------------------------------------------------------------------------------------------------------------------------------------------

WhatsApp:

screenshot_20181004-025723 3

### CODE REVIEW

**Comment by Aditya-Sood** [comment]
@kiwix/lieutenants
Could you please review and give a feedback? Thanks

**Comment by abdulwd** [comment]
I'm getting a crash on pressing the share button. Here is the stack trace:

```
10-04 20:46:46.588 20630-20630/org.kiwix.kiwixmobile E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.kiwix.kiwixmobile, PID: 20630
    java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/6630-6330/Kiwix/wikipedia_ab_all_2017-03.zim
        at android.support.v4.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:719)
        at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:404)
        at org.kiwix.kiwixmobile.zim_manager.fileselect_view.ZimFileSelectFragment$1.onActionItemClicked(ZimFileSelectFragment.java:201)
        at android.widget.AbsListView$MultiChoiceModeWrapper.onActionItemClicked(AbsListView.java:6319)
        at com.android.internal.policy.PhoneWindow$DecorView$ActionModeCallback2Wrapper.onActionItemClicked(PhoneWindow.java:3540)
        at android.support.v7.view.SupportActionModeWrapper$CallbackWrapper.onActionItemClicked(SupportActionModeWrapper.java:170)
        at android.support.v7.app.AppCompatDelegateImplV9$ActionModeCallbackWrapperV9.onActionItemClicked(AppCompatDelegateImplV9.java:1791)
        at android.support.v7.view.StandaloneActionMode.onMenuItemSelected(StandaloneActionMode.java:140)
        at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
        at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:171)
        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:973)
        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:963)
        at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:624)
        at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:150)
        at android.view.View.performClick(View.java:5215)
        at android.view.View$PerformClick.run(View.java:21196)
        at android.os.Handler.handleCallback(Handler.java:742)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5604)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
```

As I have mentioned in the issue, you should rebase your branch on branch [3.0](https://github.com/kiwix/kiwix-android/tree/3.0) and for this PR choose the base branch as 3.0, not master. You should replace all the 20 share icon PNGs with a single vector asset and remove all the lint warnings.

**Comment by Aditya-Sood** [comment]
@abdulwd what's the actual file path for the wiki that you were trying to share?
And is it stored in the Internal or External storage?

**Comment by abdulwd** [comment]
@Aditya-Sood Sorry for the late reply.
The file path is **/storage/6630-6330/Kiwix/wikipedia_ab_all_2017-03.zim** and the file is stored on micro-SD card.
**Update:** You can rebase your branch on master now as 3.0 is now merged with master.

**Comment by abdulwd** [comment]
@Aditya-Sood It works well if I move the file to the internal storage but it will be great if you can get this working for external storage. :)

**Comment by mhutti1** [comment]
@Aditya-Sood Can you rebase this branch? I don't seem to have permission to touch your fork (I think you can enable this in Github settings).

**Comment by Aditya-Sood** [comment]
@mhutti1 Sorry, I forgot to update this branch with respect to the master yesterday. Also, I've invited you as a collaborator to my fork (if that's what you meant by the fork permissions)

**Pull request merged**
