### PR TITLE
#1429 update copyright and standardise

### LINKED ISSUE #1429: Standardise Copyright across project using Copyright Plugin
**Is your feature request related to a problem? Please describe.**
Copyrights are inconsistently placed, missing or have varying contents.

**Describe the solution you'd like**
Using the [plugin](https://www.jetbrains.com/help/idea/copyright.html) bundled with android studio we should commit this configuration to git and apply it to the project

### PR DESCRIPTION
**Pull request by jhbiggs**
Fixes #1429.  Updates copyrights for project including config file.

### CODE REVIEW

**Comment by macgills** [comment]
much much better but the files that produce this copyright should be stored in git (if they have been added I can't see them but there are a tonne of files here). I would guess when when you create the copyright profile some file is created under the `idea` folder and that should be shared between all developers so going forward whenever anyone makes a file the right copyright will be there https://www.jetbrains.com/help/idea/copyright.html google `copyright intellij plugin` for more information, I am sure there is an SO question.

**Comment by abdulwd** [comment]
Is it mandatory to have a copyright notice in `.java/.kt` files? We can remove it from them too if it's not required.

**Comment by macgills** [comment]
I would say it should only be in source files @abdulwd , from my experience of looking at the AOSP it is definitely in java files

**Comment by jhbiggs** [comment]
Is the last commit what you had in mind for committing to the configuration?  I found the copyright folder in .idea and added it.  I'll continue to work on isolating the copyright text to just .java and .kt files.

**Comment by macgills** [comment]
@jhbiggs yup those config files look great. Please continue the work on isolating the copyright to source files, I think you can apply a scope to achieve this

**Comment by macgills** [comment]
@jhbiggs I think you need to commit the scope as well, also a `.properties` file had the copyright added

**Comment by jhbiggs** [comment]
Hi @macgills I committed the scope and took out the copyright remnant from the .properties file.

**Comment by macgills** [comment]
@jhbiggs so so soooo close. You can match on file types with your pattern `file:*.java||file:*.kt` see [scope documentation](https://www.jetbrains.com/help/idea/settings-scopes.html).
You also have conflicts. All those files were deleted I think so that will be easy to resolve

**Comment by jhbiggs** [comment]
Will work through the conflicts as soon as possible.  I think I'm missing something though, the "resolve conflicts" button is grayed out.

**Comment by macgills** [comment]
You should rarely use the web ui. Just merge develop in, resolve the conflicts (which should be just deleting the files because they were deleted) and commit the merge.
The properties file still has a copyright also

**Comment by jhbiggs** [comment]
So StorageCalculator.kt imports KiwixBuildConfig.  I deleted the latter as you suggested in the last comment and now the former has an error.  Did you envision something else?

**Comment by jhbiggs** [comment]
Ok, I see the recent commits in develop eliminated the errors there.  Working on committing the changes...

**Comment by jhbiggs** [comment]
😃🎉

**Pull request merged**
