### PR TITLE
 Fixed :  issue #1163 [ App crash on Library Fragment [online tab] while refreshing and clicking List Items Simultaneously ] 

### PR DESCRIPTION
**Pull request by CodetoInvent**
Fixes #1155

Fix : App crash on Library Fragment [online tab] while refreshing and clicking List Items Simultaneously
I have fixed the issue #1163 
steps to reproduce 1: [with refreshing list ]
step 1: open ListFragment [ Online Tab ] where you will find the list of ZIM files
step 2: search let say "Math" then refresh and click list simultaneously app will crash

step to reproduce 2: [without refreshing the list ]
step 1:open ListFragment [ Online Tab ] where you will find the list of ZIM files
step 2:search let say "Math" when list appears add "s" to the searchview ["maths"] and suddenly press the list app will crashes .

Changes:

1. Added notifyDatachange() method to notify the update as soon as the List appears as the listitem position and content changes

2. Added onRefreshDisableListClick() method to prevent it from IndexOutofBoundException & IllegalException (notifyDataSetChanged())

3. Added toastOnRefresh() method to toast whenever user refreshes

4. Added noRefreshQueryChange() method on every querytextchange we will disable list action for 1sec to avoid sudden Exception IllegalStateException( notifyDataSetChanged())

This is the link to show how App is Crashing:
https://drive.google.com/file/d/1ktwPWDU4uTDzsi3w5D7tjSo2XlWIyQgD/view?usp=sharing

This is the link to show App crash Fixes :
https://drive.google.com/file/d/12o1zhk3KqSrc4nxmLbM_4vCihko_IC9K/view?usp=sharing

### CODE REVIEW

**Comment by sonusourav** [comment]
@CodetoInvent  First of all, you should open a ticket for the issue in Issues tabs and not describe both the issue and changes in pull request only.

**Comment by sonusourav** [comment]
And I guess you are using the app from play store, if this is the case, you should install the app from the repo. The app on the play store is not the updated one.

**Comment by CodetoInvent** [comment]
Thanks for reviewing,I know the app is not updated in play store yet.
I have cloned it a day ago from git. you can also check how the app is crashing.
i have shown steps to reproduce the issue. 
Now i have fixed the issue

**Comment by CodetoInvent** [comment]
sure sir i will be happy to commit a comment in code as well with new commit.
Actually i have  use handler because whenever books are visible within 0.3 sec we are notifying the Adapter of a list that listView data is set changed. so to prevent it from app crashing.
you can check it out by cloning from my forked repo you will see crash will not happen anymore or worst case very rare .
Please accept the pull request if you find it helpful as i tested it on 3 real devices and 2 emulators from
android k to p. 
Thanks again :)

**Comment by CodetoInvent** [comment]
@abdulwd @mhutti1 @kelson42 can you please review this.

**Comment by mhutti1** [comment]
Closing as this should be fixed by 2.5

**Pull request closed without merging**
