### PR TITLE
Fix Font Licensing Issues From #349

### PR DESCRIPTION
**Pull request by Ryan10145**
After #349 , a font was added that did not have a license and another was added that needed clarification. This changes one of the fonts and adds the appropriate attributions and also clarifies the license/permissions for another one.

### CODE REVIEW

**Comment by divadsn** [comment]
```
Exception in thread "Thread-32" java.lang.NoClassDefFoundError: com/android/utils/PathUtils$1
	at com.android.utils.PathUtils.deleteIfExists(PathUtils.java:47)
	at com.android.utils.PathUtils.lambda$addRemovePathHook$0(PathUtils.java:125)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.android.utils.PathUtils$1
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more
```

Will rebase your branch, should fix the build then.

**Comment by kelson42** [comment]
@Ryan10145 @divadsn The "strange" exception is still there https://travis-ci.org/kiwix/kiwix-android/builds/332111068?utm_source=github_status&utm_medium=notification. But probably not a blocker for the merge.

**Comment by divadsn** [comment]
@kelson42 but the exception doesn't seem to be anyway related to that change, otherwise it would fail in the previous PR.

**Comment by kelson42** [comment]
@divadsn OK

**Pull request merged**
