### PR TITLE
Feature/macgills/custom app icon upgrade

### LINKED ISSUE #32: Implement a automod system for the Android custom app version_name
_From @kelson42 on December 30, 2016 20:22_

gen-custom-android-build.py is the script used to create custom apps, ie. apps which include a unique content (ZIM file) and are rebranded.

If version_name is empty, then script gen-custom-android-build.py should try to take it from the ZIM file content. It can do that because:
* Custom apps versions are the date of the content, for example 2016-12
* This date is in the file name of the ZIM content.

So if there is not version_name, then gen-custom-android-build.py should try to extract the date from the ZIM file name which ends with it: for example "wikipedia_en_medicine_2016-12.zim" will give "2016-12".

_Copied from original issue: kiwix/kiwix#410_

### LINKED ISSUE #36: Allow custom app version_code to be unspecified and to instead query Google Play and increment
_From @mhutti1 on December 30, 2016 20:12_

If the version code is unspecified (not available or empty string) in a custom apps json we should query Google play and increment the version code from the latest version that is published (including alpha/beta).

_Copied from original issue: kiwix/kiwix#408_

### LINKED ISSUE #852: Read adaptive icon
Readd adaptive icon removed by https://github.com/kiwix/kiwix-android/pull/851

### LINKED ISSUE #1218: Fixes for build-custom-app
* Explain how to install ruby
* Explain how to install travis (the travis doc is big)
* Talk about "hash -r"
* Put a word about "kiwix-android-custom" that people know where to modify things
* zim_url and zim_content should be merged (in zim?)
* remove version_code fron info.json
* add httpslib2 in the deps
* add google-api-python-client in the deps
* add space before "if you found it"

### PR DESCRIPTION
**Pull request by macgills**
Fixes #1218 ticket is no longer relevant
Fixes #852 adaptive icons added for kiwix and customexample
Fixes #36 versionCode is calculated in the format "YYYDDD0"
Fixes #32 versionName is read by extracting it from a zimUrl or failing that formatting the current date as "YYYY-MM"

Complete overhaul of custom apps

### CODE REVIEW

**Comment by abdulwd** [comment]
If upgrading icons are required in future what steps are to be followed?

**Comment by macgills** [comment]
@abdulwd the documentation will be updated in `kiwix-android-custom`

**Comment by abdulwd** [comment]
Cool. If we can link it somewhere in kiwix-android that would be great.

**Comment by kelson42** [comment]
>  versionName is read by extracting it from a zimUrl or failing that formatting the current date as "YY-MM"

@macgills I hope the format is `YYYY-MM`?

**Comment by macgills** [comment]
@kelson42 
```
val versionName: String = parseVersionNameFromUrlOrUsePattern(url, "YYYY-MM")
```
I'll edit the erroneous description

**Pull request merged**
