### PR TITLE
Convert KiwixDatabase.java to Kotlin

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes: #2991 
Parent Issue: #1826 

Converted KiwixDatabase.java to Kotlin

### CODE REVIEW

**Comment by kelson42** [comment]
@MohitMaliFtechiz What is the status here? Still a draft?

**Comment by MohitMaliFtechiz** [comment]
> 

Hi @kelson42 , yes it's in draft

**Comment by MohitMaliFtechiz** [comment]
Hi @gouri-panda  this PR is Ready for Review.

**Comment by gouri-panda** [comment]
After `Room` implementation we don't need this anymore.

**Comment by kelson42** [comment]
@MohitMaliFtechiz we have to fix the conflict here

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz we have to fix the conflict here

hi @kelson42 ,
I have resolved the conflicts.

**Comment by kelson42** [comment]
@gouri-panda what is functionnalities provided by this class. Can you make a short list please?

**Comment by gouri-panda** [comment]
@kelson42 this class is responsible for accessing database objects, querying objects, migrating the database, etc.

**Comment by kelson42** [comment]
@gouri-panda OK, so - if I get it right - we need it absoluteltly to allow a smooth migration of the data from ObjectBox to Room. As such it has to be reviewed and merged before the migration.

**Comment by kelson42** [comment]
@gouri-panda Can you please review so I ultimatly can merge it?

**Comment by gouri-panda** [comment]
@kelson42 I'm waiting for the #3045 to merge first. so that we have less likely to have regression.

**Comment by kelson42** [comment]
@gouri-panda Now we are good to do that one

**Comment by kelson42** [comment]
@MohitMaliDeveloper After rebasing, this one still fails with 30... so there is still a problem IMO. Please look/fix with TOP prio.

**Review by gouri-panda — COMMENTED** [review]
@MohitMaliDeveloper Api keeps falling on the 30. Otherwise, I reviewed the code and tested it. Looks good to me!

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliDeveloper Api keeps falling on the 30. Otherwise, I reviewed the code and tested it. Looks good to me!

hi @gouri-panda ,
i have placed a fix for android 30, now CI is passed on android 30.

**Comment by gouri-panda** [comment]
@MohitMaliDeveloper There is a minor conflict here.

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliDeveloper There is a minor conflict here.

hi @gouri-panda ,
i have resolved the conflict. now you can review this PR.

**Comment by kelson42** [comment]
@gouri-panda what is the status here?

**Review by gouri-panda — APPROVED** [review]

**Pull request merged**
