### PR TITLE
Enhancement of Zoom level option color should be grayed when disabled #556

### LINKED ISSUE #556: Zoom level option color should be grayed when disabled
**Is it a ?**

- [x] Bug Report

### Step 1: Are you ready to report?
   - [x] I have tested with the last (dev) version of the software.  ( If not, and if possible, run your test again with the most recent version available.)

### Step 2: What is your environment?
  * version of the software you use :  3.0.1
  * device / operating system :  Samsung J7 / 7.0
  
### Step 3: Describe the problem:

  * What do you obtain? A copy of the error message or a screenshot is always useful.
     When the zoom control switch is disabled the color of the "Zoom level" option should be grayed 
     out, default otherwise.

     When option disabled : 

image

     When option enabled : 

image
  
  * What should be the behaviour from your point of view? How do you expect the service to work?
     Zoom level option color to be greyed when disabled, else it should be default. 

### Step 4 (optional) : Other Comments:

  * What is the context of this ticket? If not obvious, explain why you need to do this.

    Same color in both the states could cause confusion to the user and would also not give a clear 
    picture about the state of the zoom level option. 
   
Please describe the feature you want to add to the project.

I would like to work on this issue.
@mhutti1 @brijeshshah13 Do let me know what you think.

### PR DESCRIPTION
**Pull request by vansh1sh**
Fixes #556
@mhutti1 Please review it.

### CODE REVIEW

**Comment by RajaVamsi11** [comment]
@vansh1sh  6 commits in one PR is not good.Try to squash all the commits

**Comment by vansh1sh** [comment]
@mhutti1 It seems to work for my device.

fix

**Comment by mhutti1** [comment]
It is definitely not working on my API 26 emulator I suggest you try on that.

**Comment by mhutti1** [comment]
@vansh1sh I am not sure try your way and I will review it.

**Comment by vansh1sh** [comment]
@mhutti1 Please review now, fixed to work for API 26.

**Comment by kelson42** [comment]
@mhutti1 The poor @vansh1sh contributor made and fixed his PR... and nobody took time to review it... It is now really old... but better being late than never!

**Comment by abdulwd** [comment]
@kelson42 But the issue has been closed.

**Comment by kelson42** [comment]
@abdulwd Indeed! I close this PR. Thx for the input.

**Comment by mhutti1** [comment]
Sorry :( I am getting 100+ emails a week, they can fall through the cracks.

**Pull request closed without merging**
