### PR TITLE
Create new home screen and initial landing screen

### LINKED ISSUE #743: Create new home screen
The present home screen is the help screen which is not user-friendly. So a new screen has been designed.

image

This screen shows the offline books the user has downloaded. The user can just tap any of the
downloaded books to start reading from the start of the book. The book will open in the same
tab. If a user wants to open another book, the user can open another tab from which another
book can be opened. This is in accordance with the multi-ZIM paradigm. The books are
categorized on the basis of language.

### PR DESCRIPTION
**Pull request by abdulwd**
Fixes #743 and #744 

Changes: New home screen and initial landing screen added.
@mhutti1 Sorry for solving 2 issues in a single PR but they were interdependent.

image  
image

### CODE REVIEW

**Comment by abdulwd** [comment]
@siddharth2010 I think you have to refactor the tests a bit so that they pass on this PR.

**Comment by siddharth2010** [comment]
Sure @abdulwd. I will be getting right on it as soon as it's merged

**Comment by abdulwd** [comment]
@mhutti1 I have added the storage permission request and the Kiwix logo. Does it look fine? 😶
image

**Comment by mhutti1** [comment]
I would say that the kiwixlogo should ideally be the background for the whole thing so that it is not compressed, but its close.

**Comment by mhutti1** [comment]
Ok lets get rid of the text. Would it be possible to give the kiwix logo a bit more padding?

**Comment by abdulwd** [comment]
@mhutti1 I have added more padding to the left. We cannot add more padding to the top and bottom as the height of the image is quite less than its width.
image

**Comment by mhutti1** [comment]
This looks good for now.

**Pull request merged**
