### PR TITLE
Add leak canary stub as a dependency for all builds by default

### LINKED ISSUE #664: Unable to build properly (in CI too) since Leakcanary dependence has been added to project
#[Bug]While building kiwix-android app in android studio found error:package com.squareup.leakcanary does not exist

### Environment
  * version  : android studio
  * device / operating system : ubuntu 16.04
  
### The Bug:While running the app of kiwix-android on emulator there is an error occurred saying package com.squareup.leakcanary does not exist.Then I tried some of the solutions given on stackoverflow and github and have done some changes in build.gradle but still issue is not resolved.
I have added debugcompile and releasecompile in dependecies of build.gradle,but after running still I got an error.It looks like this:
screenshot from 2018-03-24 03-28-57

#### Steps to reproduce:

  1. Build kiwix-android app in android studio from github.
  2. Run kiwix app on emulator.

  I want to run this app on android studio to have a look on its working.

### PR DESCRIPTION
**Pull request by mhutti1**
Fixes #664

Changes: Use leak canary stub by default. Switch out for debug.

### CODE REVIEW

**Comment by kelson42** [comment]
@mhutti1 Is tha really a good move for prod? It seems to me we should not include this unecessarry lib in that case?!

**Comment by mhutti1** [comment]
That is what this does. We use the no-op by default and for debug builds use the standard version.

**Comment by kelson42** [comment]
@mhutti1 Ok, so the dep in it, but do nothing, because configure that way for prod?

**Comment by mhutti1** [comment]
Yeah.

**Pull request merged**
