### PR TITLE
#2437 Upgrade to AS/AGP 4.1

### LINKED ISSUE #2151: Remove explicit NDK version once AGP 4.1 is in stable
**Is your feature request related to a problem? Please describe.**
Right now we set an ndkVersion in AllProjectConfigurer, nightly.yml and coverage.yml that need to be aligned with the NDKs available on Github Actions runners. With version 4.1 of the Android  Gradle Plugin we can go back to not specifying it and it will be automatically downloaded on request.

### LINKED ISSUE #2437: Upgrade to AS/AGP 4.1
**Is your feature request related to a problem? Please describe.**

Android Studio 4.1 has been released, we should update our tooling to take advantage of the latest features

**Describe the solution you'd like**

Update Android Studio and the gradle plugin

### PR DESCRIPTION
**Pull request by macgills**
Fixes #2437 
Fixes #2151

 - bump versions

### CODE REVIEW

**Comment by abdulwd** [comment]
Coverage reports are failing.

**Comment by macgills** [comment]
Yeah annoyingly on the unit tests job but for a mysterious reason

```
* What went wrong:
Execution failed for task ':custom:processCustomexampleDebugResources'.
> Problems reading data from Binary store in /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/gradle470862514682398193.bin offset 155508 exists? false
```

I'll run some local experiments, I was hoping this would just be a quick win. Maybe just a bump in gradle version

**Comment by macgills** [comment]
can't repro locally so just throwing gradle versions at the wall and seeing what sticks. @abdulwd  you can try and replicate the error by running the unit coverage commands? Could be helpful but also might need to open a ticket with gradle which would be time consuming

**Comment by abdulwd** [comment]
I'll test it out this weekend if this is not urgent.

**Comment by macgills** [comment]
no rush

**Comment by macgills** [comment]
Maybe don't checkout the latest commit that is incoming, quite a desperate attempt to see if it works

**Comment by s-ayush2903** [comment]
I eliminated the conflicts only(just to trigger the long pending CI checks)

**Comment by macgills** [comment]
@s-ayush2903 why did you force push this?

**Comment by s-ayush2903** [comment]
I resolved the previously existing conflicts to trigger the CI check, and it produced no effect, so I deleted that commit

**Comment by macgills** [comment]
ah, thank you

**Review by abdulwd — APPROVED** [review]
🎉

**Comment by macgills** [comment]
Sadly not all guns & roses, there is nearly a 7% coverage drop which is unacceptable, I've tried another reworking of the CI commands but I am giving up if this build fails because I have much higher priority tickets

**Review by abdulwd — DISMISSED** [review]

**Comment by abdulwd** [comment]
Let's merge this. We do have to work on increasing our test coverage

**Comment by macgills** [comment]
By merging we lose **all** of our unit test coverage for the core module, it doesn't exactly thrill me.

Technically the coverage exists or at least the tests run and would fail but I am not convinced we gain enough by merging this and theoretically losing all coverage info for core forever

**Comment by abdulwd** [comment]
I thought it's using some different methods to calculate the coverage. If it's ignoring the coverage for the entire core module it's a blocker.

**Comment by macgills** [comment]
I won't be getting back to this, hopefully somebody else can pick this up

**Pull request closed without merging**
