### PR TITLE
Scrollbar Indicator Added

### LINKED ISSUE #2114: Scroll bar in the online list
**Is your feature request related to a problem? Please describe.**
When scrolling through the list of available zim files I don't see how long the list is. It would be nice if there is a scroll bar on the left or right side to see how far I have come or if it make sense to use  another search term.

**Describe the solution you'd like**
Just a normal scroll bar to the left or right. If the files are ordered by alphabet, language or date then it would be nice if I could see the position like "K" or "2020-04-30" somewhere.

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #2114

### CODE REVIEW

**Comment by kelson42** [comment]
@MohitMaliFtechiz Do you have a screenshot before/after maybe? So the implication of this PR are clearer.

**Review by gouri-panda — DISMISSED** [review]
The code looks good! I'll let the Ui review to  @kelson42

**Comment by kelson42** [comment]
@gouri-panda THX. yes waiting to the screenshots. They should be systemativally deluvered if UI changes.

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz Do you have a screenshot before/after maybe? So the implication of this PR are clearer.

Hi @kelson42  i have updated the before and after screenshots of Ui on PR description

**Comment by kelson42** [comment]
@MohitMaliDeveloper Thank you!

**Pull request merged**
