### PR TITLE
Fixed sometimes CI fails in InitialDownloadTest

### LINKED ISSUE #3159: Sometimes CI fails in ```InitialDownloadTest```
**Describe the bug**
Sometimes CI fails with error ```Waited for the root of the view hierarchy to have window focus``` in ```InitialDownloadTest```

**Expected behavior**
CI should be passed.

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #3159 , #3163

### CODE REVIEW

**Comment by kelson42** [comment]
@MohitMaliFtechiz Which big made the VI faiéing the first time?

**Comment by gouri-panda** [comment]
@MohitMaliDeveloper How do we test this?

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz Which bug/ticket made the CI failed the first time?

hi @kelson42  , I have created the issue for failing CI.

https://github.com/kiwix/kiwix-android/issues/3163

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliDeveloper How do we test this?

are you referencing to https://github.com/kiwix/kiwix-android/issues/3163 ?

**Review by gouri-panda — APPROVED** [review]

**Pull request merged**
