### PR TITLE
#1214 upload universal apk to download.kiwix on nightly build and to …

### LINKED ISSUE #1214: Universal APK have to be automatically published too
To Gihub and download.kiwix.org.

### PR DESCRIPTION
**Pull request by macgills**
Fixes #1214

Changes: Upload universal to kiwix.download and GitHub releases

### CODE REVIEW

**Comment by macgills** [comment]
@mgautierfr could I be transferred the SSH key that is used in deploy.sh on kiwix build?

**Comment by kelson42** [comment]
@macgills Do we have a corresponding PR on kiwix-build to stop there to do it? Will you still upload the architecture specific APKs?

**Comment by macgills** [comment]
@kelson42 I thought I was just uploading the universal apks? I can very easily upload all the splits.

Currently no PR to remove the uploading from kiwix-build, I will get on it. It isn't the worst if they both are working, the apks produced have very distinct filenames but obviously not desirable

**Comment by kelson42** [comment]
@macgills Not sure about that either. It is true that now that we have also a split by density, things are really complex. So ok for me to have only the universal. But please secure that we have the same APKs on download/github uploaded.

**Comment by macgills** [comment]
@mgautierfr I have unfortunately caused every other android build to fail because of my updates to travis as part of this PR. If you could review this quickly it would be appreciated.
As admin I may have to force a merge tomorrow, depending on who I am blocking besides myself

**Pull request merged**
