### PR TITLE
#1175 automate code coverage

### LINKED ISSUE #1175: Automated code coverage
* Evaluate current status with @julianharty and @mhutti1 
* Choose a technology stack (measurement, transfers, display, ...)
* Measure code coverage for all automated tests (unit, integration, UI)
* Run it every night
* Publish (consolidate results) publicly
* Document the process (if needed) on the kiwix-android wiki

See also #865 #836

### PR DESCRIPTION
**Pull request by macgills**
Fixes #1175 

Changes: Integrate with codecov, fix broken automation tests

Screenshots/GIF for the change: [If possible, please add relevant screenshots/GIF]

### CODE REVIEW

**Comment by macgills** [comment]
@soloturn Sorry I should have tagged the title of this PR as Do Not Review or something similar. Seeing as this ticket was improving the build process to test it I needed to open a PR and draft PRs don't get built by travis. I would, when the time comes to review, definitely not look at the individual commits because there are at least 30 of them as I battled with starting an emulator that doesn't crash on travis, GitHub has the files changed tab for just this scenario, seeing as I will be merge committing this PR when it is ready and I request review the integrity of the commits doesn't matter as much because they will not become the truth on master though I do agree that they were messy, I was halfway through automating the publishing process to the Play store when code coverage came up as a topic and seeing as how they were touching exactly the same files and I would have to integrate them both anyways I basically finished off publishing and then got code coverage on top and committed partial bits of files but messed it up and winded up throwing the lot in

**Comment by macgills** [comment]
So the end result of this PR is
-  full coverage integration with our unit tests
-  a commented out hopeful integration with our instrumentation tests to be integrated with once the next version of kiwixlib is published
- building of releasable apks with generated versionNames, versionCodes and abi splits
- the ability to publish to GitHub releases (as a draft)
- the ability to publish to play store alpha with a source controlled listing see src/kiwix/play/*

I am still a bit unsure about the play store publishing because I want it to happen on the tagging of release (and in the future master) but I think to allow that to happen we would have to toggle the travis setting "Build pushed branches" and that would have further ramifications that I would need to address potentially by combining conditional stages/jobs. For now I am going to operate on the hope that it will just build when a tag is created and cross that bridge when we come to it

**Comment by soloturn** [comment]
> ... when the time comes to review, definitely not look at the individual commits 
i am not sure if i understand this sentence correctly. how do you plan to get these commits onto master if you are not able to separate your work into digestable pieces?

**Comment by macgills** [comment]
@soloturn we are moving to using merge commits for PRs, this means the commits will no longer be replayed on master, just one merge commit totalling the overall changes of the branch so master's history will not look sloppy. I have never personally in my career found looking at the individual commits very useful in the review process, a class can go through many iterations before I arrive on my preferred state and to read it would just be confusing, in rare scenarios commits can shed some extra light but I only found that for much larger line changes than this one.
A lot of this work is a bit untidy as I start aligning to the process we will adhere to going forward. By the time of 3.0 it will hopefully be a lot clearer

**Comment by soloturn** [comment]
interesting. you have such an example already merged? would be curious to look how the commit history and the commit graph then looks like, as well the commit message.

**Comment by macgills** [comment]
image

Here is an example of the "Introduce Unit Testing" ticket being merged, as a branch naming scheme I think the number in the branch name and per commit gives good context when viewing history, my experience is primarily in JIRA/Bitbucket so I don't know if this will create unnecessary chaff with GitHub but I don't think so.
https://nvie.com/posts/a-successful-git-branching-model/ this is the end result I am hoping to achieve with 3.0, unfortunately 2.5's isolated nature means some workarounds at the moment.
A more comment heavy approach may be necessary, in the example of `--dump` vs `-dump` absolutely an error by myself and should be fixed, I will commit momentarily. As for the 55 files at least 40 of them can be ignored as they are bootstrapped files mirroring our play store listing

**Comment by macgills** [comment]
@soloturn @mhutti1 this PR is now blocking the 2.5 release. If it could be reviewed asap that would be appreciated but in the interest of expediency if I do not have approval by tomorrow I will go ahead with the merge and move on to merging 2.5 to the release branch

**Pull request merged**
