### PR TITLE
Change "Support Kiwix" icon in Sidebar

### LINKED ISSUE #3585: Improve Sidebar "Support Kiwix" icon
App would benefit of the replacement of the lifebuoy icon with something better:

For example:
* https://fontawesome.com/icons/info?f=classic&s=solid
* https://fontawesome.com/icons/arrow-up-right-from-square?f=classic&s=solid

### PR DESCRIPTION
**Pull request by Jawad-Hameed**
Fixes #3585

change "Support Kiwix" icon in Sidebar

**Screenshots** 
Screenshot_20231210-091139

### CODE REVIEW

**Comment by gouri-panda** [comment]
@kelson42 what do you think about the logo? What should we include? This PR is what you intend for the logo. We already have 2 different types of PR.

**Comment by Jawad-Hameed** [comment]
> @kelson42 what do you think about the logo? What should we include? This PR is what you intend for the logo. We already have 2 different types of PR.

I have solved this issue #3585 and changed the Support Kiwix icon in the sidebar menu. This icon was recommended by @kelson42 (Author). I have created this icon and replaced it in the project. That looks Good and naturally matches with text

**Comment by kelson42** [comment]
Sorry we already had PR #3588 to fix this.

**Comment by Jawad-Hameed** [comment]
> @kelson42 what do you think about the logo? What should we include? This PR is what you intend for the logo. We already have 2 different types of PR.

I have changed the Support Kiwix icon in the sidebar menu that exactly matches with text. I have created this icon in Adobe Photoshop and replace icon and solve this issue

**Pull request closed without merging**
