### PR TITLE
2.5

### PR DESCRIPTION
**Pull request by macgills**
The pull request representing the totality of changes in 2.5. The constituent parts have already been reviewed and further slight changes are incoming.

### CODE REVIEW

**Comment by kelson42** [comment]
@macgills What is the release branch? I thought we would have only master - dev - feature branches!

**Comment by macgills** [comment]
That is the aim but for now I need a release branch to create the 2.5 release. If I merged to master now it would create a version that is not 2.5. Release will be deleted as soon as 2.5 is made

**Comment by kelson42** [comment]
@macgills OK, so you plan to rewrite master to have 2.4, 2.5, 3.0 in a row? My first idea was to have 2.5 in a branch... and have 2.3 and 3.0 in a row on master (considering that a lot of 3.0 stuff is already on master).

**Comment by macgills** [comment]
I was going to create the develop branch off master after the 2.5 release, merge release to develop, when 3.0 is ready PR to master. 
Master should only ever be released software

**Comment by soloturn** [comment]
@kelson42 you thought of using the 2.5 branch for the 2.5 release, to make it clear already from the name what it is?

**Comment by kelson42** [comment]
@soloturn Have a look the changelog

**Pull request merged**
