### PR TITLE
Localisation updates from https://translatewiki.net.

### PR DESCRIPTION
**Pull request by translatewiki**
Translation updates

### CODE REVIEW

**Comment by kelson42** [comment]
@MohitMaliFtechiz Please review and merge.

**Comment by MohitMaliFtechiz** [comment]
hi @kelson42 ,

this changes looks good to me we can merge those translations.

**Review by MohitMaliFtechiz — APPROVED** [review]
looks good to me.

**Comment by kelson42** [comment]
@MohitMaliFtechiz You can merge yourself if your are the only reviewer. Please rebase on develop branch first if necessary, so we keep a clean git history.

**Comment by MohitMaliFtechiz** [comment]
> 

ok let me rebase to develop branch first.

**Pull request merged**
