### PR TITLE
Feature/shridhargoel/#1114 toolbar swipe

### LINKED ISSUE #1114: Add swipe down animation (was: Add swipe down toolbar gesture to open tabs switcher)
**Is your feature request related to a problem? Please describe.**
The icon for opening the tab switcher is quite small and it is used frequently. So there must be a gesture to open the tab switcher.

**Describe the solution you'd like**
Google Chrome offers a gesture to open the tab switcher which is pull down from the toolbar.

**Additional context**
ezgif-1-8ad26a80ceb7

### PR DESCRIPTION
**Pull request by macgills**
Fixes #1114 

Changes: see #1115

### CODE REVIEW

**Comment by macgills** [comment]
@ShridharGoel there are 3 lint issues failing the build:
```

  /home/travis/build/[secure]/[secure]-android/app/src/main/java/org/[secure]/[secure]mobile/main/MainActivity.java:341: Error: Access to private method showTabSwitcher of class MainActivity requires synthetic accessor [SyntheticAccessor]

          showTabSwitcher();

          ~~~~~~~~~~~~~~~

  /home/travis/build/[secure]/[secure]-android/app/src/main/java/org/[secure]/[secure]mobile/main/OnSwipeTouchListener.java:12: Error: Access to private member of class GestureListener requires synthetic accessor [SyntheticAccessor]

      gestureDetector = new GestureDetector(ctx, new GestureListener());

                                                 ~~~~~~~~~~~~~~~~~~~~~

  /home/travis/build/[secure]/[secure]-android/app/src/main/java/org/[secure]/[secure]mobile/main/OnSwipeTouchListener.java:16: Error: OnSwipeTouchListener#onTouch should call View#performClick when a click is detected [ClickableViewAccessibility]

    public boolean onTouch(View v, MotionEvent event) {

                   ~~~~~~~
```
Can you please open a new PR targeting this branch with them fixed?

Also after you have fixed them please run `gradlew lintKiwixDebug` to make sure you have no other errors

**Comment by macgills** [comment]
@ShridharGoel do you have the availability to make the fixes in my previous comment?

**Comment by kelson42** [comment]
@macgills Would you be able to fix the last details and merge? I have the feeling otherwise we will have to close this PR.

**Comment by ShridharGoel** [comment]
@macgills Sorry, I'm not able to find time to fix the lint issues. Anyone can feel free to take this up.

**Comment by macgills** [comment]
I will perform the fixes today

**Comment by kelson42** [comment]
@macgills thx

**Pull request merged**
