### PR TITLE
Migrate to AndroidX

### LINKED ISSUE #898: Migrate to AndroidX
**Is your feature request related to a problem? Please describe.**

Since AndroidX is released, we should migrate the support libraries to the androidx namespace.

**Describe the solution you'd like**

Migrate the stable libraries to the androidx namespace.

**Additional context**

Please refer to this [link](https://developer.android.com/jetpack/androidx/migrate).

### PR DESCRIPTION
**Pull request by abdulwd**
Fixes #898

### CODE REVIEW

**Comment by soloturn** [comment]
i force pushed your commit again.

**Comment by abdulwd** [comment]
@soloturn @kelson42 I have rebased this branch on master and it is ready to be merged.

**Comment by soloturn** [comment]
cool, @abdulwd! would you mind upgrading to the newest gradle-4.10.3 instead of 4.10.1?

i also noticed that the imports got reordered. to better understand i tried auto formatting as well, and:

(first) editorconfig missed a line "continuation_indent_size" which intellij and android studio take into account. thank you for exposing, i created a pull request for it. 

(second) using the android studio default formatting + editorconfig i get the same formatting as you. a couple of days ago @kelson42 merged @287mdsahil s pull request which had different formatting: https://github.com/kiwix/kiwix-android/pull/928/files . that formatting can be produced by using the Square Android style as suggested here: https://github.com/kiwix/kiwix-android/blob/master/docs/codestyle.md. how do you currently handle this?

**Comment by soloturn** [comment]
@abdulwd, kelson merged now the new gradle version to main, could you please rebase and remove yours if this still works?

**Comment by abdulwd** [comment]
@soloturn I have updated all the files in the project to follow the Square's code style as we must follow a consistent style and the docs is not outdated. @mhutti1 @kelson42 As this branch will be difficult to rebase, can you please merge this branch ASAP?

**Pull request merged**
