### PR TITLE
#2606 navigation fixes while pressing back button

### LINKED ISSUE #2606: Kiwix App doesn't close while pressing the back button
**Describe the bug**
While selecting another zim file( or selecting the same file by going to the library section) Kiwix app doesn't close the application by pressing the back button.

**Expected behavior**
App should close 
**Steps to reproduce the behavior:**
1. Select a zim file (if you are in the reader section then ignore the step)
2. Now again select a zim file
3. Press the back button
Observe you are in a loop

**Environment**
- Version of Kiwix Android: 3.4.3
- Device: Realme
- OS version: 10

### PR DESCRIPTION
**Pull request by gouri-panda**
Fixes #2606

### CODE REVIEW

**Comment by kelson42** [comment]
@gouri-panda Thx for this PR, could you please tebase it? Looks like there is now a conflict.

**Comment by kelson42** [comment]
@gouri-panda Can you please rebase so we can go forward with the review?

**Comment by gouri-panda** [comment]
@kelson42 Done 👍

**Comment by kelson42** [comment]
@MohitMaliFtechiz This PR is waiting to your review since 10 days. Please have a look. Reviewing PRs of orhers is the most urgent task to handle (except massive incident or regression of course)

**Review by kelson42 — APPROVED** [review]
I can not teally review this PR.... but lgtm

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz This PR is waiting to your review since 10 days. Please have a look. Reviewing PRs of orhers is the most urgent task to handle (except massive incident or regression of course)

hi @kelson42 , please check my requested changes on this review.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Ooops, my bad. Sorry. @gouri-panda Can you please move this PR forward?

**Comment by kelson42** [comment]
@gouri-panda Please remove the "draft"

**Comment by kelson42** [comment]
@gouri-panda I'm not sure about the status (I might have done an error by removing the draft). Is that really ready for a new review? If yes, can you please close the open discussion (with an answer)?

**Comment by gouri-panda** [comment]
@kelson42 it's not ready yet for new review.

**Comment by kelson42** [comment]
@gouri-panda Any news here? We should focus on release 3.6.0 now and this is one of the tickets? Any chance to complete the PR soon?

**Comment by kelson42** [comment]
@MohitMaliFtechiz If @gouri-panda has no time to complete yet, would you be able to do so?

**Comment by kelson42** [comment]
@gouri-panda Good for you?

**Pull request merged**
