### PR TITLE
#2263 reOriented the back to top fab

### LINKED ISSUE #2263: Back to top FAB should be above the top bottom toolbar in feature/navigation
**Is your feature request related to a problem? Please describe.**

Currently, the back to top fab is displaying on top of (see screenshot) the bottom toolbar, This looks weird. 

**Describe the solution you'd like**

The back to top button should be (16dp?) above the bottom toolbar.

**Describe alternatives you've considered**

Steps to reproduce:
1. Make sure back to top is enabled in settings -> Back to Top toggle
2. Open a book.
3. Scroll down
4. Scroll up so that the bottom reader nav bar is visible. 
5. Notice that the back to top FAB is overlaying the bottom bar. 
Screenshot_1596718727

**Additional context**

This problem only occurs in the feature/navigation branch.

### PR DESCRIPTION
**Pull request by s-ayush2903**
Fixes #2263

**Screenshots** 
ss

### CODE REVIEW

**Comment by macgills** [comment]
I would be very surprised if this was the fix. Did you follow the reproduction steps precisely?

`marginEnd` is (in a Left To Right language) the space on the right hand side of a view

**Comment by s-ayush2903** [comment]
Yep, i did follow steps to reproduce the issue. What surprises you here, anything wrong?

**Comment by s-ayush2903** [comment]
When i used marginRight it showed up warning, so one thing clicked me that once you told me to remove as many warnings possible, so i replaced it with marginEnd

**Comment by macgills** [comment]
Ah I misread your change, my mistake, thought it was changing `marginXXX`->`marginEnd` not the `margin` which was overriding `marginBottom`

**Comment by s-ayush2903** [comment]
I tried implementing the behavior described in the article but the `dodgeInsetView` works only with the CoordinatorLayouts, i searched for workarounds to use in the ConstraintLayout but didn't work, i still added the attribute but it didn't work, anyways, the `insetEdges` has been set on the bottomToolbar for avoiding future collapses with other view(s)

**Comment by macgills** [comment]
@s-ayush2903 Did you try moving the fab xml so it is a child of coordinator/nestedCoordinator?

**Comment by s-ayush2903** [comment]
Yep, i did but that may lead to so many changes(in order to orient it properly) in the file so i didn't do that. If i'm allowed for that, i'll be definitely pushing the changes. 
And i need some clarification regarding: _Change lesser files to Keep the reviewing focused_ as this was the prime reason for me to not change/touch the view hierarchy

**Comment by macgills** [comment]
A fix should be "The Right Fix" and the minimum number of files absolutely necessary to modify to implement the fix is the acceptable number of modifications.

A quick fix is sometimes acceptable when "The Right Fix" is too complex but it should always be strived for.

Moving the fab into the nested coordinator and setting layout gravity bottom|end is probably all that needs doing to enable the inset solution

**Comment by s-ayush2903** [comment]
Sudden close due to inactivity?

**Comment by macgills** [comment]
Accidental, I think because I closed the navigation PR

**Comment by macgills** [comment]
@s-ayush2903 can we do this without the notch at all?

**Comment by s-ayush2903** [comment]
Hey, didn't you like it? It looked good to me.
No worries, will remove it

**Comment by s-ayush2903** [comment]
Here it is now:
|Without notch|
|---------|
|fab|

**Review by macgills — APPROVED** [review]

**Pull request merged**
